### PR TITLE
Keepass OpenCL format, mk 2.

### PR DESCRIPTION
**Pull request by magnumripper**
Works fine on Intel CPU and nvidia GPU 384.x. AES decryption speed over 20 GB/s on Titan X.

### CODE REVIEW

**Comment by magnumripper** [comment]
Fails on Super, which has ancient drivers. I don't care much about that.

**Comment by magnumripper** [comment]
Merged manually

**Comment by kholia** [comment]
Good news :+1: 

```
$ ../run/john --format=keepass-opencl --test
Device 0: GeForce GTX 1050 Ti
Benchmarking: KeePass-opencl [SHA256 AES/Twofish/ChaCha OpenCL]... DONE
Speed for cost 1 (iteration count) of 50000 and 6000, cost 2 (version) of 1 and 2
Raw:	8745 c/s real, 8730 c/s virtual
```

This is with the same old `NVIDIA binary driver - version 375.66` running on this box. The earlier PR was failing on this box.

**Comment by magnumripper** [comment]
That's great news! Then it's only the several years old drivers on super/well failing, apart from *one* of the drivers at the build bots (old AMD CPU driver bundled with  fgrlx).

Note how it will autotune differently if you run `-test -cost:6000:6000`. When loading real hashes, it will autotune for (the hardest of) them.

**Comment by kholia** [comment]
AMD's OpenCL runtime supports debugging using "printf" statements. Theoretically, we could debug this problem by hex-dumping all the different buffers (keys, input data, output data) to see which portion of the code is misbehaving. However, this would be a super time consuming process!

**Comment by magnumripper** [comment]
The real fun starts when the bug moves around (or hides) along with your printf statements...

**Comment by kholia** [comment]
Some relevant hacks to skip CI testing,

* https://circleci.com/docs/1.0/skip-a-build/ (CircleCI supports the [ci skip] or [skip ci] standard for ignoring builds.)

* [skip travis]

**Comment by magnumripper** [comment]
I'm not sure I see much use for [skip ci]. If someone uses it to push a "bad" commit, it will pass through. Then next time someone (else) pushes ANYTHING, it will start failing.

**Comment by magnumripper** [comment]
Then again, if a commit only contains eg. doc changes, it could have [skip ci] just to be nice to them.

**Comment by kholia** [comment]
Good points! I will start using this trick for docs changes, and for changes in `*2john` tools.

**Comment by claudioandre** [comment]
This was used a couple of times.

https://github.com/magnumripper/JohnTheRipper/search?q=%5Bci+skip%5D&type=Commits&utf8=%E2%9C%93

**Pull request closed without merging**
