### PR TITLE
Fix JtR-TestSuite failure for RSVP format

### PR DESCRIPTION
**Pull request by kholia**
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2988.

### CODE REVIEW

**Comment by kholia** [comment]
The `new_keys` logic still works for HMAC-MD5 part. I can restore this logic for HMAC-SHA1.

Or I can totally remove this `new_keys` business. What would you prefer?

**Comment by magnumripper** [comment]
Looked closer and that makes sense. Only the MD5 type can avoid extra work with new_keys.

**Comment by kholia** [comment]
The `HMAC-SHA1` part also had working `new_keys` logic earlier. I removed it in one of my commits (my bad). I can restore it if required.

**Comment by magnumripper** [comment]
Ah, that makes sense. The bug with the SHA-2's was that the salt was used within the `if (new_keys)` block - that can't work.

**Pull request merged**
