### PR TITLE
Fix alignment problem in config.c

### PR DESCRIPTION
**Pull request by kholia**
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2868.

### CODE REVIEW

**Comment by jfoug** [comment]
Looks great to me, and this certainly WAS an alignment bug. Any configuration using this 'local' configure logic on a 'require alignment' system would have crashed, for sure.

**Comment by kholia** [comment]
Thanks @jfoug. I will merge this once the build bots are happy.

**Comment by jfoug** [comment]
The 'only' issue I see here, is if there is any system where a sizeof(void*) is different than sizeof(ARCH_WORD)  But I do not think there are any (or any that we would see).

The proper alignment for this structure is sizeof the first element (the pointer to next).  By I think ARCH_WORD was designed for that, and hopefully it will cover all cases.

**Comment by kholia** [comment]
Hmm. I wonder how JtR will behave in `x32 ABI` mode when it comes to alignment. Maybe everything will be fine as size of both long and pointers is 4 bytes for x32 mode?

**Comment by jfoug** [comment]
This should be tested.  the x32 may be 8 byte MACHINE_WORDS, but 32 bit pointers.   It may be opposite. 

If it is 32 bit pointers and longer words,. then no foul. Yes, you use more memory by looking at things with ARCH_WORD.  BUT if the reverse is the case (ARCH_WORD is 4, but pointer is 8), then the alignment done here will still not be aligned properly!!

**Comment by kholia** [comment]
I am sure that the pointers are 4 bytes on `x32`.  I believe that `x32` really didn't gain much traction. I will test JtR Jumbo on it in the near future for sure.

**Comment by jfoug** [comment]
x32 is really just a 32 bit process (4 byte pointers and longs), BUT it gives access to all of the registers we get in x86-64   https://en.wikipedia.org/wiki/X32_ABI

But that said, the sizeof(liong)==sizeof(void*)==sizeof(ARCH_WORD)  in a john build for x32.

**Comment by kholia** [comment]
Cool. One less problem to worry about ;)

**Comment by jfoug** [comment]
I was not 100% sure about x32.  It looks like you also get 64 bit arith help (vs all 64 stuff emulated). Also, calling conversion is like i86-64 which is register (much faster and no forced pre/prolog stuff).  So basically, it is enhanced 32 bit build, taking the benefits of the 64 bit CPU and using them.

I actually like 32 bit builds, EXCEPT for the big speedup gained when dealing with 64 bit formats.  With X32, it sounds like you would get the gains of 32 bit (smaller instructions, less page exceptions due to smaller memory foot print, etc), BUT not lose on the speed when the 64 bit env actually can help out.

Yes, things like huge files and huge memory buffers are missed.  But the extra speed gained all over can be used to work around a few nits for lack of memory.

I may have to look deeper into x32. It may be the best of both worlds, as far as john is concerned.  John really can get by without a LOT of the benefits of true i86_64.  There are a few exceptions (such as unique REALLY needs a huge amount of mem), sometimes at loading, john also needs a huge amount of mem, etc.  But I have not dug into x32 (but may shortly).

**Comment by kholia** [comment]
IIRC we tested the x32 stuff some years ago. I don't remember much about this stuff though.

**Pull request merged**
