### PR TITLE
Argon2 CPU basic version

### PR DESCRIPTION
**Pull request by Eterna1**

### CODE REVIEW

**Comment by kholia** [comment]
Can you please squash these commits into one? It will make merging cleaner.

https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by Eterna1** [comment]
@kholia: yes, but again tests failed

**Comment by Eterna1** [comment]
some warnigns and test of argon didnt start

**Comment by Eterna1** [comment]
its squashed

**Comment by magnumripper** [comment]
Please fix these:
```
argon2d_fmt_plug.c:467:3: warning: incompatible pointer types initializing
      'char *' with an expression of type 'struct fmt_tests [5]'
      [-Wincompatible-pointer-types]
                tests
                ^~~~~
argon2d_fmt_plug.c:467:3: warning: suggest braces around initialization of
      subobject [-Wmissing-braces]
                tests
                ^~~~~
                {    }
2 warnings generated.
argon2i_fmt_plug.c:467:3: warning: incompatible pointer types initializing
      'char *' with an expression of type 'struct fmt_tests [5]'
      [-Wincompatible-pointer-types]
                tests
                ^~~~~
argon2i_fmt_plug.c:467:3: warning: suggest braces around initialization of
      subobject [-Wmissing-braces]
                tests
                ^~~~~
                {    }
2 warnings generated.
zipmonster_fmt_plug.c:147:20: warning: unused function 'hex_encode_uppercase'
      [-Wunused-function]
static inline void hex_encode_uppercase(unsigned char *str, unsigned char *_out)
                   ^
1 warning generated.
```

**Comment by Eterna1** [comment]
isnt this bug in gcc or something? on ubuntu 12.04 (the same as in circleci) but 32bit and desktop edition I dont have this warning, and anywhere else ..

**Comment by claudioandre** [comment]
> isnt this bug in gcc or something?

Notice, on Travis you can see warnings in gcc and clang. Plus: 
```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
----------------------------------------

argon2d_fmt_plug.c:467:3: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   tests
   ^
argon2d_fmt_plug.c:467:3: note: (near initialization for ‘fmt_argon2d.params.signature[0]’)
argon2d_fmt_plug.c:442:2: warning: missing braces around initializer [-Wmissing-braces]
  {
  ^
argon2d_fmt_plug.c:442:2: note: (near initialization for ‘fmt_argon2d.params’)
argon2d_fmt_plug.c:478:3: warning: missing braces around initializer [-Wmissing-braces]
   {
   ^
argon2d_fmt_plug.c:478:3: note: (near initialization for ‘fmt_argon2d.methods.tunable_cost_value’)
argon2d_fmt_plug.c:485:3: warning: missing braces around initializer [-Wmissing-braces]
   {
   ^
argon2d_fmt_plug.c:485:3: note: (near initialization for ‘fmt_argon2d.methods.binary_hash’)
argon2d_fmt_plug.c:501:3: warning: missing braces around initializer [-Wmissing-braces]
   {
   ^
argon2d_fmt_plug.c:501:3: note: (near initialization for ‘fmt_argon2d.methods.get_hash’)
argon2d_fmt_plug.c:468:5: warning: missing braces around initializer [-Wmissing-braces]
  }, {
     ^
argon2d_fmt_plug.c:468:5: note: (near initialization for ‘fmt_argon2d.methods’)
argon2d_fmt_plug.c:441:31: warning: missing braces around initializer [-Wmissing-braces]
 struct fmt_main fmt_argon2d = {
                               ^
argon2d_fmt_plug.c:441:31: note: (near initialization for ‘fmt_argon2d’)
argon2i_fmt_plug.c:467:3: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   tests
   ^
argon2i_fmt_plug.c:467:3: note: (near initialization for ‘fmt_argon2i.params.signature[0]’)
argon2i_fmt_plug.c:442:2: warning: missing braces around initializer [-Wmissing-braces]
  {
  ^
argon2i_fmt_plug.c:442:2: note: (near initialization for ‘fmt_argon2i.params’)
argon2i_fmt_plug.c:478:3: warning: missing braces around initializer [-Wmissing-braces]
   {
   ^
argon2i_fmt_plug.c:478:3: note: (near initialization for ‘fmt_argon2i.methods.tunable_cost_value’)
argon2i_fmt_plug.c:485:3: warning: missing braces around initializer [-Wmissing-braces]
   {
   ^
argon2i_fmt_plug.c:485:3: note: (near initialization for ‘fmt_argon2i.methods.binary_hash’)
argon2i_fmt_plug.c:501:3: warning: missing braces around initializer [-Wmissing-braces]
   {
   ^
argon2i_fmt_plug.c:501:3: note: (near initialization for ‘fmt_argon2i.methods.get_hash’)
argon2i_fmt_plug.c:468:5: warning: missing braces around initializer [-Wmissing-braces]
  }, {
     ^
argon2i_fmt_plug.c:468:5: note: (near initialization for ‘fmt_argon2i.methods’)
argon2i_fmt_plug.c:441:31: warning: missing braces around initializer [-Wmissing-braces]
 struct fmt_main fmt_argon2i = {
                               ^
argon2i_fmt_plug.c:441:31: note: (near initialization for ‘fmt_argon2i’)
```

**Comment by claudioandre** [comment]
> yes, but again tests failed

You should rebase and update the PR.

**Comment by magnumripper** [comment]
> isnt this bug in gcc or something? on ubuntu 12.04 (the same as in circleci) but 32bit and desktop edition I dont have this warning, and anywhere else ..

Not necessarily a bug. Different compilers/versions will complain about different things, but usually warnings like these have a merit even if many other compilers doesn't warn. I haven't had a look at the code though so I'm not sure about this case.

**Comment by magnumripper** [comment]
Fine, now please squash and rebase, we don't want that local merge of yours upstream. You'll need to `git push -f` which is a no-no for permanent branches but fine for topic branches.

**Comment by magnumripper** [comment]
Thanks!

**Comment by magnumripper** [comment]
> no idea why virtual speed is 8 times slower than real

That's normal if you run OMPx8. Every wall-clock second, you burn 8 CPU seconds.

**Pull request merged**
