### PR TITLE
base64: changed int into size_t

### PR DESCRIPTION
**Pull request by jfoug**

### CODE REVIEW

**Comment by magnumripper** [comment]
#2132

**Comment by jfoug** [comment]
This one is ready.  All tests pass.  ASAN has no problems.  using base64_convert.exe in test mode (with my testing script in jtrts directory) all works fine.

Yes, a lot of format changes, but it was simply adding the new 'null' variable listing we do not care about the error return.

**Comment by magnumripper** [comment]
Did you try base64_convert.exe with, say, a 3 GB file? I'm thinking I'll try to produce a 3 GB (compressed) RAR file and see if it goes through rar2john and then gets cracked. But I didn't get around to it yet. However, I think we can merge this for now anyway.

**Comment by jfoug** [comment]
/c/phpbb/johnripper/bleed-64/src $ ../run/rar2john p1.rar > in1
file name: x1.rar
mem_calloc(): Cannot allocate memory trying to allocate 18446744070987741568 bytes
/c/phpbb/johnripper/bleed-64/src $ ls -l p1.rar
-rwxr-x---+ 1 barb barb 2.8G Jul  9 09:21 p1.rar*

**Comment by jfoug** [comment]
$ ../run/rar2john -v p1.rar
! HEAD_SIZE: 59, PACK_SIZE: 18446744072348646080, UNP_SIZE: 18446744072348524060
! HIGH_PACK_SIZE present
! HIGH_UNP_SIZE present
file name size: 6 bytes
file name: x1.rar
! EXT_TIME present with size 5
! Dictionary size: 4096 KB
mem_calloc(): Cannot allocate memory trying to allocate 18446744070987741568 bytes

**Comment by jfoug** [comment]
```diff
/c/phpbb/johnripper/bleed-64/src $ git diff rar2john.c
diff --git a/src/rar2john.c b/src/rar2john.c
index 1339bee..8060983 100644
--- a/src/rar2john.c
+++ b/src/rar2john.c
@@ -332,20 +332,35 @@ next_file_header:

                file_header_head_size =
                    file_header_block[6] << 8 | file_header_block[5];
-               file_header_pack_size = file_header_block[7] +
-                       (file_header_block[8] << 8) +
-                       (file_header_block[9] << 16) +
-                       (file_header_block[10] << 24);
-               file_header_unp_size = file_header_block[11] +
-                       (file_header_block[12] << 8) +
-                       (file_header_block[13] << 16) +
-                       (file_header_block[14] << 24);
+               //file_header_pack_size = file_header_block[7] +
+               //      (file_header_block[8] << 8) +
+               //      (file_header_block[9] << 16) +
+               //      (file_header_block[10] << 24);
+               file_header_pack_size = file_header_block[10];
+               file_header_pack_size <<= 8; file_header_pack_size += file_header_block[9];
+               file_header_pack_size <<= 8; file_header_pack_size += file_header_block[8];
+               file_header_pack_size <<= 8; file_header_pack_size += file_header_block[7];
+
+               //file_header_unp_size = file_header_block[11] +
+               //      (file_header_block[12] << 8) +
+               //      (file_header_block[13] << 16) +
+               //      (file_header_block[14] << 24);
+               file_header_unp_size = file_header_block[14];
+               file_header_unp_size <<= 8; file_header_unp_size += file_header_block[13];
+               file_header_unp_size <<= 8; file_header_unp_size += file_header_block[12];
+               file_header_unp_size <<= 8; file_header_unp_size += file_header_block[11];
+
                if (verbose) {
+                       int i;
                        fprintf(stderr,
                                "! HEAD_SIZE: %d, PACK_SIZE: "LLu", UNP_SIZE: "LLu"\n",
                                file_header_head_size,
                                (unsigned long long)file_header_pack_size,
                                (unsigned long long)file_header_unp_size);
+                       fprintf(stderr, "! file_header_block: ");
+                       for (i = 0; i < 15; ++i)
+                               fprintf(stderr, " %02x", file_header_block[i]);
+                       fprintf(stderr, "\n");
                }
                /* calculate EXT_TIME size */
                ext_time_size = file_header_head_size - 32;
```

**Comment by magnumripper** [comment]
I guess this is a problem of rar2john.c and not the base64 functions. We probably have a lot of such "problems" but RAR is one of the very few that is a problem IRL, if that. This should be a new issue.

**Comment by magnumripper** [comment]
```c
		file_header_pack_size = file_header_block[7] +
			(file_header_block[8] << 8) +
			(file_header_block[9] << 16) +
			(file_header_block[10] << 24);
```
This must be incomplete. There's got to be more that 32 bits in the RAR header, for larger sizes.

**Comment by magnumripper** [comment]
Here it is: http://www.forensicswiki.org/wiki/RAR#File_Header_.28File_in_Archive.29

There's another 32 bits later on **if** bit 0x100 in HEAD_FLAGS is set.

**Comment by magnumripper** [comment]
I opened an issue for this, #2170

**Comment by magnumripper** [comment]
I wonder why it ended up as 18446744070987741568 bytes though. Since we neglected to read the high bits, we should just end up with a small positive size.

**Comment by magnumripper** [comment]
And BTW since size is less than 4 GB, it should actually work with just those 32 bits. We ARE using size_t so there should be no problem.

**Comment by solardiz** [comment]
On Sat, Jul 09, 2016 at 08:24:02AM -0700, magnum wrote:
> I wonder why it ended up as 18446744070987741568 bytes though. Since we neglected to read the high bits, we should just end up with a small positive size.

This is FFFFFFFF5DC47980.  Sign extension occurred somewhere.

**Comment by magnumripper** [comment]
Yeah the code @jfoug posted fixes it. I'm not quite sure why, perhaps writing it like eg. `(file_header_block[8] << 8ULL)` would also fix it.

**Comment by jfoug** [comment]
Not sure where/why sign extension (it may be a bug or something else).  The conversion has size_t result, unsigned char for the buffer, signed int for the shift constants. But somewhere in that major conversion sign extension happens (the byte[7] which will be MSB) is sign extended.  But the way I 'see' the code, there should be no sign.  All I know is adding 1 byte at a time to the size_t and then shifting before next byte, made the problem go away.  But I still 'think' that must be some compiler error.   It may be how the size_t is usually a typedef or something  But it 'should' be unsigned, AFAIK on all systems.

I was also surprised at 4 bytes for rar length.  Do we account for the additional 32 bits of size?  Also, is it 56 bit number, or a full 64  bit number?

**Pull request merged**
