### PR TITLE
Fixed bad/good SHA1. Merged star office into libre (odf)

### PR DESCRIPTION
**Pull request by jfoug**
handles #3089.  Handles #3111

### CODE REVIEW

**Comment by kholia** [comment]
The following changes are needed to fix compilation errors,

``` diff
diff --git a/src/opencl_libreoffice_aes_fmt_plug.c b/src/opencl_libreoffice_aes_fmt_plug.c
index 311c2a91f..b77433f6f 100644
--- a/src/opencl_libreoffice_aes_fmt_plug.c
+++ b/src/opencl_libreoffice_aes_fmt_plug.c
@@ -255,14 +255,14 @@ static int cmp_all(void *binary, int count)
        int index;
 
        for (index = 0; index < count; index++)
-               if (!memcmp(binary, crypt_out[index], BINARY_SIZE))
+               if (!memcmp(binary, crypt_out[index].v, BINARY_SIZE))
                        return 1;
        return 0;
 }
 
 static int cmp_one(void *binary, int index)
 {
-       return !memcmp(binary, crypt_out[index], BINARY_SIZE);
+       return !memcmp(binary, crypt_out[index].v, BINARY_SIZE);
 }
 
 static int cmp_exact(char *source, int index)
diff --git a/src/opencl_libreoffice_fmt_plug.c b/src/opencl_libreoffice_fmt_plug.c
index 3d2ba7259..91b901869 100644
--- a/src/opencl_libreoffice_fmt_plug.c
+++ b/src/opencl_libreoffice_fmt_plug.c
@@ -275,10 +275,10 @@ static int crypt_all(int *pcount, struct db_salt *salt)
                SHA1_Init(&ctx);
                SHA1_Update(&ctx, output, cur_salt->content_length);
                SHA1_Final((unsigned char*)crypt, &ctx);
-               crypt_out[index+i][0] = crypt[0];
+               crypt_out[index][0] = crypt[0];
                if (cur_salt->original_length % 64 >= 52 && cur_salt->original_length % 64 <= 55)
                        SHA1_Libre_Buggy(output, cur_salt->original_length, crypt);
-               crypt_out[index+i][1] = crypt[0];
+               crypt_out[index][1] = crypt[0];
        }
 
        return count;
```

**Comment by jfoug** [comment]
> The sxc hashes are causing odf-opencl self-test failures.

This also needed corrected:
```diff
- SHA1_Update(&ctx, output, cur_salt->content_length);
+ SHA1_Update(&ctx, output, cur_salt->original_length);
```

**Comment by jfoug** [comment]
I believe this patch is ready.  Now, we only have 1 ODF format.  It handles all types (well there are 2 formats in opencl).  This works with the broken sha1, and the correct sha1, and works with sha256/aes.

I have tested the jtrTestSuite, and had to adjust the data file.  Since we shortened the password length to 51 bytes, where it was 125 bytes before, the tests have fewer successes.  also, I had to add the sxc type to allow that sxc stuff to work. It will work for odf or sxc

NOTE, pass_gen.pl only generates 'correct' sha1 hashes.  It also works from 'fixed' encrypted data, so it currently would be unable to generate test hashes that would exercise the bug anyway.  I do not plan on updating pass_gen.pl to place the broken sha1 code in it, nor to have variable length decrypt buffers (required to generate invalid sha1 problems.

**Comment by kholia** [comment]
I have squashed the commits, and merged this PR as commit d8ee974201e19d03897937.

Thanks :+1:

**Pull request closed without merging**
