### PR TITLE
Rename and refactor the ODF formats

### PR DESCRIPTION
**Pull request by kholia**
More cleanup work is needed but this should be a decent start.

Maybe we should combine the `odf-opencl` and `odf-aes-opencl` formats into one format?

### CODE REVIEW

**Comment by magnumripper** [comment]
Sorry, your time to rebase 😇

**Comment by magnumripper** [comment]
I'm not sure I understand why some (bots') OpenCL builds fail but not all of them?
```
In file included from opencl_libreoffice_aes_fmt_plug.c:32:0:
libreoffice_variable_code.h:5:25: error: ‘libreoffice_tests’ defined but not used [-Werror=unused-variable]
 static struct fmt_tests libreoffice_tests[] = {
                         ^
cc1: all warnings being treated as errors
make[1]: *** [opencl_libreoffice_aes_fmt_plug.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2
```
Perhaps the combination clang & OpenCL works, for some reason.

**Comment by kholia** [comment]
> Perhaps the combination clang & OpenCL works, for some reason.

Yes, seems so. I tested my code on macOS.

**Comment by kholia** [comment]
Unifying `valid` is still remaining, and will be addressed in a future PR.

**Pull request merged**
