### PR TITLE
add Rawsec's CyberSecurity Inventory badge

### PR DESCRIPTION
**Pull request by noraj1337**
### Summary

add Rawsec's CyberSecurity Inventory badge

See http://list.rawsec.ml/about.html for other style of badges / shields

### CODE REVIEW

**Comment by magnumripper** [comment]
What is this?

**Comment by kholia** [comment]
Thanks for this PR but we don't want any more badges which are not necessary.

**Comment by solardiz** [comment]
Looks like half-spam to me. On one hand, it's self-promotion by this little-known inventory project. It does link to JtR, but it also wants these "back links". On the other hand, I recognize that maintaining a curated inventory involves effort, and an inventory like this could be useful. We do link to sectools.org off the JtR homepage without any request to do so, or maybe even because there was no request nor even suggestion, and because sectools.org provided a bit more than a listing (people could also vote and comment), although I think it ended up being rather inactive.

Regarding the badges, I think we should reject. That's way too visible and distracting for something as minor and irrelevant as this. The badges are mostly for dynamic stuff pertaining to current status of the tree.

BTW, the word "cybersecurity", especially with weird CamelCaps, is for marketers and politicians. Let's not promote their agendas.

**Comment by solardiz** [comment]
@noraj1337 I don't want to discourage you personally. You're probably on the right track with the CTFs and with the inventory. IMO, you just need to rename it and cut down on the marketing. If your inventory is good, people will retweet, etc. You might also want to stop referring to yourself as "a Cyber-Security engineer and ethical hacker", where especially the former reads "a clown" or someone who is not seriously into tech even to not-so-old timers like me. Clearly, since you play CTFs you have some skills (perhaps not as rusty as mine, even), so you deserve better than that. Good luck!

**Comment by noraj1337** [comment]
> Looks like half-spam to me. On one hand, it's self-promotion by this little-known inventory project. It does link to JtR, but it also wants these "back links". On the other hand, I recognize that maintaining a curated inventory involves effort, and an inventory like this could be useful. We do link to sectools.org off the JtR homepage without any request to do so, or maybe even because there was no request nor even suggestion, and because sectools.org provided a bit more than a listing (people could also vote and comment), although I think it ended up being rather inactive.
> 
> Regarding the badges, I think we should reject. That's way too visible and distracting for something as minor and irrelevant as this. The badges are mostly for dynamic stuff pertaining to current status of the tree.
> 
> BTW, the word "cybersecurity", especially with weird CamelCaps, is for marketers and politicians. Let's not promote their agendas.

I understand that the badge is self-promotional and not really useful, but maybe for minor projects, the inventory is giving them visibility so accepting the badge is a way to do the same for the inventory.




> @noraj1337 I don't want to discourage you personally. You're probably on the right track with the CTFs and with the inventory. IMO, you just need to rename it and cut down on the marketing. If your inventory is good, people will retweet, etc. You might also want to stop referring to yourself as "a Cyber-Security engineer and ethical hacker", where especially the former reads "a clown" or someone who is not seriously into tech even to not-so-old timers like me. Clearly, since you play CTFs you have some skills (perhaps not as rusty as mine, even), so you deserve better than that. Good luck!

I'm Franch and in France the words Cybersecurity (ie Cybersécurité) and Cyberdefense (ie Cyberdéfense) are the words used by every one, professionals, industrials, national government agencies, schools, ... and referring as SSI (_Sécurité des Systèmes d'Informations_ in french, maybe a translation is _IT Security) in France is very old school. The name of my degree in France is Cyberdefense Engineer and the same term is used for my job title. That are teh right words in France, sorry if it sounds "clown" and UN-professional in other countries.

**Comment by solardiz** [comment]
Thank you for explaining this, @noraj1337. I didn't consider the country specifics. To many of us, these "cyber" words are something that became popular in this context only in 2010s, and are mostly used by politicians (so yes, that includes some "national government agencies" in other countries as well, which to me hints that they're out of touch with people who do the actual tech [1]) and marketers. I accept that the language changes, and maybe these words wouldn't sound as weird to me in another 10-20 years (if I'm still around by then).

[1] One major exception is DARPA's Cyber Grand Challenge. Clearly, DARPA, and especially organizers of this challenge, are very well in touch with the tech, no doubt there. Maybe their choice of this name means acceptance of the language change, or maybe they're making fun of the "cyber" craze.

**Comment by solardiz** [comment]
FWIW, as a reality check I ran this Twitter poll yesterday:

https://twitter.com/solardiz/status/939126305710276608

The comments I received there (unfortunately, most of them no longer part of the thread as someone who started a sub-thread appears to have deleted their tweet) have changed my perception of "cyber" somewhat. Looks like its non-ironic use in US gov & military started 10-20 years ago, albeit it was growing steadily (exponentially?) since, and especially in the most recent decade. It's the extensive use by marketing and press that appears to be even more recent (last few years).

**Pull request closed without merging**
