### PR TITLE
Add OpenCL support for cracking NetIQ SSPR hashes

### PR DESCRIPTION
**Pull request by kholia**
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2901.

I think that faster non-CTX code can be used in the inner loop.

This hashing scheme is not too bad.

### CODE REVIEW

**Comment by kholia** [comment]
Current speed,

```
$ ../run/john --test --format=sspr-opencl
Will run 32 OpenMP threads
Device 6: GeForce GTX TITAN X
Benchmarking: sspr-opencl, NetIQ SSPR [SHA1/SHA2 OpenCL]... (32xOMP) DONE
Speed for cost 1 (KDF [1:SHA1 2:SHA1_SALT 3:SHA256_SALT 4:SHA512_SALT]) of 1
Raw:	3471 c/s real, 3451 c/s virtual
```

I will remove the OpenMP stuff from this format as it is not used.

**Comment by kholia** [comment]
Thanks for bringing this up :+1: 

Initially, I started with a copy of the `gpg_kernel.cl` file, which has gone various revisions / "rewrites" along with copyright changes. However, the only stuff now left from the original `gpg_kernel.cl` file is the following code,

```
typedef struct {
    uint length;
    uchar v[PLAINTEXT_LENGTH];
} sspr_password;

typedef struct {
    uchar v[20];
} sspr_hash;

typedef struct {
    uint length;
    uint count;
    uchar salt[SALT_LENGTH];
} sspr_salt;
```

So, the current copyright text of `sspr_kernel.cl` seems to be OK in my opinion.

However, the copyright text present in the `opencl_sspr_fmt_plug.c` file is a bigger issue. I have simply mentioned `This file is based on opencl_gpg_fmt_plug.c file.` in that file. I think it would be better if I include the copyright + licensing terms of `opencl_gpg_fmt_plug.c` file in the `opencl_sspr_fmt_plug.c` file itself. What do you think?

**Comment by kholia** [comment]
Here is what I am thinking about,

``` diff
diff --git a/src/opencl_sspr_fmt_plug.c b/src/opencl_sspr_fmt_plug.c
index 74014c8a0..697fbfe3b 100644
--- a/src/opencl_sspr_fmt_plug.c
+++ b/src/opencl_sspr_fmt_plug.c
@@ -7,7 +7,11 @@
  * Redistribution and use in source and binary forms, with or without
  * modification, are permitted.
  *
- * This file is based on opencl_gpg_fmt_plug.c file.
+ * This file is based on opencl_gpg_fmt_plug.c file which is,
+ *
+ * Copyright (c) 2012 Dhiru Kholia <dhiru at openwall.com>, Copyright (c) 2012
+ * Lukas Odzioba <ukasz@openwall.net>, Copyright (c) 2016 JimF, and licensed
+ * under the same terms.
  */
 
 #ifdef HAVE_OPENCL
```

**Comment by kholia** [comment]
I have (1) updated the copyright year (2) removed OpenMP stuff (3) fixed copyright and licensing information in the latest commit.

This should be OK to merge now.

**Comment by magnumripper** [comment]
When I approved this, I didn't realize you are using a monolithic kernel that takes seconds to run even on a Titan X 😢 

Opened #3118 for that.

**Pull request merged**
