### PR TITLE
OpenCL support for PGP WDE format

### PR DESCRIPTION
**Pull request by kholia**
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2694.

### CODE REVIEW

**Comment by kholia** [comment]
@magnumripper This code doesn't work well with GTX TITAN X on the `well` box.

```
$ ../run/john --test --format=pgpwde-opencl
...
Device 6: GeForce GTX TITAN X
OpenCL UNKNOWN OPENCL ERROR error in common-opencl.c:1820 - Error creating command queue
```

The code works OK with AMD devices on the `well` box. Maybe an earlier version of my code (which was bad) has put the NVIDIA device into a weird state. This last bit might not be true as the `dmg-opencl` format is still working on the NVIDIA device just fine.

I can't spot the problem.

**Comment by magnumripper** [comment]
> This code doesn't work well with GTX TITAN X

I kind of doubt it's a real problem (like you said it could be some weird remnants from earlier runs). Ignore it for now. If there's indeed a problem with sane versions of stuff, I'll have a look at it once merged.

**Comment by magnumripper** [comment]
Disabling auto-tune and instead running with LWS=GWS=1 gets you a better hint
```
[magnum@super src]$ ../run/john -test -form:pgpwde-opencl -dev=6
Will run 32 OpenMP threads
Device 6: GeForce GTX TITAN X
Benchmarking: pgpwde-opencl [SHA1 OpenCL]... (32xOMP) OpenCL UNKNOWN OPENCL ERROR (-9999) error in common-opencl.c:1820 - Error creating command queue

[magnum@super src]$ LWS=1 GWS=1 ../run/john -test -form:pgpwde-opencl -dev=6
Will run 32 OpenMP threads
Device 6: GeForce GTX TITAN X
Benchmarking: pgpwde-opencl [SHA1 OpenCL]... (32xOMP) OpenCL CL_OUT_OF_RESOURCES (-5) error in opencl_pgpwde_fmt_plug.c:239 - Copy result back
FAILED (cmp_all(-1))
```

**Comment by magnumripper** [comment]
Perhaps not. Adding an explicit Finish gets us back to square one. It seems the kernel just crashes with no hint.
```diff
diff --git a/src/opencl_pgpwde_fmt_plug.c b/src/opencl_pgpwde_fmt_plug.c
index 9814f78..903cfce 100644
--- a/src/opencl_pgpwde_fmt_plug.c
+++ b/src/opencl_pgpwde_fmt_plug.c
@@ -233,6 +233,8 @@ static int crypt_all(int *pcount, struct db_salt *salt)
                multi_profilingEvent[1]),
                "Run kernel");
 
+       BENCH_CLERROR(clFinish(queue[gpu_id]), "clFinish");
+
        // Read the result back
        BENCH_CLERROR(clEnqueueReadBuffer(queue[gpu_id], mem_out, CL_TRUE, 0,
                outsize, outbuffer, 0, NULL, multi_profilingEvent[2]),
```
```
$ make -sj4 && LWS=1 GWS=1 ../run/john -test -form:pgpwde-opencl -dev=6

Make process completed.
Will run 32 OpenMP threads
Device 6: GeForce GTX TITAN X
Benchmarking: pgpwde-opencl [SHA1 OpenCL]... (32xOMP) OpenCL CL_INVALID_COMMAND_QUEUE (-36) error in opencl_pgpwde_fmt_plug.c:236 - clFinish
FAILED (cmp_all(-1))
```

**Comment by magnumripper** [comment]
Here's the bug
```c
void pgpwde_kdf(__global const uchar *ipassword, uint password_length,
        __constant const uchar *isalt, uint saltlen, uint cbytes,
        __global uchar *okey, uint key_length)
{
    SHA_CTX ctx;
    uint num = (key_length - 1) / SHA1_DIGEST_LENGTH + 1;
    int i, j;
    uint bytes;
    uint slen;
    const unsigned char b = 0;
    unsigned char password[PLAINTEXT_LENGTH];
    unsigned char salt[16];
    unsigned char key[40];

    _memcpy(salt, isalt, saltlen);
    _memcpy(password, ipassword, password_length);
    slen = password_length;
    if (cbytes < slen + 16)
        cbytes = (uint32_t)(slen + 16);

    for (i = 0; i < num; i++) {
        bytes = cbytes;
        SHA1_Init(&ctx);
        for (j = 0; j < i; j++) {
            SHA1_Update(&ctx, &b, 1);
        }

        while (bytes > slen + 16) {
            SHA1_Update(&ctx, salt, 16);
            SHA1_Update(&ctx, password, slen);
            bytes -= slen + 16;
        }
        if (bytes <= 16) {
            SHA1_Update(&ctx, salt, bytes);
        } else {
            SHA1_Update(&ctx, salt, 16);
            SHA1_Update(&ctx, password, bytes - 16);
        }
        SHA1_Final(key + (i * SHA1_DIGEST_LENGTH), &ctx);
    }

    _memcpy(okey, key, key_length);
}
```
key is `unsigned char key[40];` but you write more than 40 to it. It should be `unsigned char key[40 * num];` except arrays can't be variable length in OpenCL. So it should be whatever figure is ever needed IRL.

**Comment by kholia** [comment]
The maximum values of `key_length` and `num` are `32` and `2` respectively. I don't see how an overflow of `key` array can occur in such conditions. My math is failing me? :-)

**Comment by magnumripper** [comment]
LOL, that was not it. key_len is always 32 so the whole loop is dead code - we always do just a single iteration and `key[40]` is enough.

**Comment by magnumripper** [comment]
> values of key_length and num are 32 and 2 respectively

Isn't it 32 and 1? If not, it should definitely be `key[2 * 40`

**Comment by kholia** [comment]
I think we need to try this format on an another NVIDIA device to rule out "state problems" with our TITAN X device.

**Comment by magnumripper** [comment]
Oh, never mind. It's obviously `2 * 20` so even if num is 2, it should be OK. I'll try it on other devices and drivers.

**Comment by kholia** [comment]
It works fine with the AMD devices we have on `super`. It fails with the Xeon Phi device but I suspect that other formats using the `SHA1 CTX` stuff also fail on Xeon Phi. This needs to be confirmed.

**Comment by magnumripper** [comment]
I see the bug on an other Titan X using 375.66 (Ubuntu) drivers. When using `LWS=1 GWS=1` it works fine, while eg. `LWS=2 GWS=2` (or pretty much anything else) triggers the bug. I'm pretty sure we're seeing a driver bug. I re-wrote the code in a multitude of ways to no avail.

**Comment by claudioandre** [comment]
I see the bug on an other Titan X using 375.66 (Ubuntu) drivers. When
using LWS=1
GWS=1 it works fine, while eg. LWS=2 GWS=2 (or pretty much anything else)
triggers the bug.


I was able to use LWS=1 GWS=whatever. If confirmed, It works in a
"sequential" (non parallel) running.

**Comment by kholia** [comment]
The PGP Disk OpenCL format is pretty similar to this format but it works on NVIDIA devices just fine. This is surprising to me.

**Comment by magnumripper** [comment]
It was our bug, fixed in f09bb77.

**Pull request merged**
