### PR TITLE
Define only _GNU_SOURCE for Cygwin builds.

### PR DESCRIPTION
**Pull request by shinnok**
See issue #1250 for details:
https://github.com/magnumripper/JohnTheRipper/issues/1250

### CODE REVIEW

**Comment by magnumripper** [comment]
This is not the correct way to edit configure. The source is configure.ac - edit that one, then build configure using eg. `autoreconf`. I can do it if you don't have autoconf installed.

**Comment by shinnok** [comment]
@magnumripper I'm not sure these options were in the .ac in the first place? Can you take a look?

**Comment by magnumripper** [comment]
Actually you'd edit `m4/jtr_systems_specific_logic.m4` which is sourced by configure.ac.

**Comment by shinnok** [comment]
Got it. I'll do that properly tomorrow.

**Comment by magnumripper** [comment]
Jim fixed it

**Pull request closed without merging**
