### PR TITLE
Test full option

### PR DESCRIPTION
**Pull request by loverszhaokai**
1. Crack max passwords at the same time

2. Detect FMT_* flags error

### CODE REVIEW

**Comment by magnumripper** [comment]
Could you please squash these into one commit that never adds those debug messages? Just force-push into this same branch. Merging changes and the revertion of them at the same time seems like a noisy idea to me.

**Comment by loverszhaokai** [comment]
@magnumripper  Sorry. I will close this and  recommit again.

**Comment by magnumripper** [comment]
No need to close, that also just adds noise. Like I said, you can force-push to the same branch you opened this PR for.

**Comment by loverszhaokai** [comment]
> you can force-push to the same branch you opened this PR for

The two commits are in the same branch (test_full_option). So what do you mean by "force-push to the same branch" ? 

Thanks

**Comment by magnumripper** [comment]
You fix it locally and then push to this `loverszhaokai:test_full_option` branch that this PR is about. You'll need to use `git push --force` since you changed history.

**Comment by magnumripper** [comment]
Are you aware of things like "squash" or "fixup" with `git rebase -i`? If not, you should learn it.

**Comment by loverszhaokai** [comment]
> Are you aware of things like "squash" or "fixup" with git rebase -i? If not, you should learn it.

Thanks, I will learn it.

**Comment by loverszhaokai** [comment]
Thanks for your help, I think I get it.

```
$ git rebase -i HEAD~2

Change the second 'pick' to 'squash'

$ git push -f origin test_full_option 
```

**Comment by magnumripper** [comment]
:+1:

**Pull request merged**
