### PR TITLE
Pass correct salt into crypt_all() in benchmarks

### LINKED ISSUE #3897: Benchmarks should pass correct salt into crypt_all()
@magnumripper I just found out that your commit 01b384e7afebff065838f0cbfebc56ab75b24e15 broke `-test` for bcrypt-ztex, in two ways: with `-mask` I am now getting timeouts, and without `-mask` I am getting poor speeds (~60k c/s for 4 boards, whereas previously we were getting ~400k c/s in that test). I think @Apingis isn't currently available to help troubleshoot this. I'd appreciate your help.

So far, I reviewed the test vectors. The first two are cost 5, which is what we intend to benchmark, but because of the issue being fixed with that commit I'm not it's what we were actually benchmarking (even though the speeds suggested we were). The lowest cost test vectors are cost 4, which isn't that much lower - but I've tried moving those to the start of the `tests` array, which doesn't appear to have made any difference (with the above commit still present, I am still getting those same timeouts and poor speeds).

I think I need better understanding of what exactly changed with that commit - what test vectors were were using before and what we're using now.

### PR DESCRIPTION
**Pull request by solardiz**
Fixes #3897

### CODE REVIEW

**Comment by solardiz** [comment]
I don't understand why formats.c uses `dyna_salt_cmp` instead of simply `memcmp` in similar context. So I simply use `memcmp`.

```c
                if ((dbsalt = db->salts))
                do {
                        if (!dyna_salt_cmp(salt, dbsalt->salt,
                                           format->params.salt_size))
                                break;
                } while ((dbsalt = dbsalt->next));
```

**Comment by solardiz** [comment]
Some non-hash formats triggered my "Warning: Could not find salt in db" when testing on CircleCI. We need to look into that and address this.

Dynamic formats passed tests without that warning.

**Comment by solardiz** [comment]
I'm now suppressing the warning for formats with `FMT_DYNA_SALT`.

**Comment by magnumripper** [comment]
> I don't understand why formats.c uses `dyna_salt_cmp` instead of simply `memcmp` in similar context. So I simply use `memcmp`.
> 
> ```c
>                 if ((dbsalt = db->salts))
>                 do {
>                         if (!dyna_salt_cmp(salt, dbsalt->salt,
>                                            format->params.salt_size))
>                                 break;
>                 } while ((dbsalt = dbsalt->next));
> ```

I don't remember all details off the top of my head but I'm pretty sure we really **should** use `dyna_salt_cmp()` For "normal" salts, a plain `memcmp()` is what it will in up as anyway but for actual dynamic salts, your memcmp will most likely compare irrelevant stuff like pointers.

**Comment by solardiz** [comment]
@magnumripper So you suggest that instead of suppressing the warning for `FMT_DYNA_SALT`, we use `dyna_salt_cmp`?

**Comment by solardiz** [comment]
Meanwhile, a CircleCI run completed without warnings.

**Comment by magnumripper** [comment]
> @magnumripper So you suggest that instead of suppressing the warning for `FMT_DYNA_SALT`, we use `dyna_salt_cmp`?

I'm not sure those warnings are related. But simply doing memcmp with dynamic salts is kinda like comparing the pointers to two strings instead of the strings themselves. The result is useless. However, I haven't got all context around this code, *perhaps* it's fine in this very case. Using dyna_salt_cmp is never wrong though.

**Comment by solardiz** [comment]
OK, switched to using `dyna_salt_cmp` and never suppressing the warning. Let's see.

**Comment by solardiz** [comment]
No warnings in CircleCI's wine-64bits test. I didn't check the rest.

**Comment by magnumripper** [comment]
> Dynamic formats passed tests without that warning.

Dynamic salts is totally unrelated to dynamic format(s). The former is dynamic-size-salts.

**Comment by magnumripper** [comment]
I also looked for warnings but saw nothing. I saw a dmg2john warning though, issue created.

**Comment by solardiz** [comment]
Have we retested OpenCL benchmarks, with and without mask, after having merged this PR? I only tested CPU and ZTEX benchmarks, not OpenCL.

**Pull request merged**
