### PR TITLE
WPAPSK and -PMK formats: Add support for PMKID. Closes #3356.

### LINKED ISSUE #3356: Add support for WPA-PMKID
https://hashcat.net/forum/thread-7717.html

PMKID = `HMAC-SHA1-128(PMK, "PMK Name" . MAC_AP . MAC_STA)` where "PMK Name" is that very fixed string.

Test vector (password "hashcat!")
```
2582a8281bf9d4308d6f5731d0e61c61*4604ba734d4e*89acf0e761f4*ed487162465a774bfba60eb603a39f3a
```
Which is
```
<PMKID>*<MAC AP>*<MAC Station>*<ESSID as hex>
```
The ESSID is not padded so that field is varying length. Given PMK hex strings as input, the ESSID isn't needed (like WPAPSK-PMK format).

### PR DESCRIPTION
**Pull request by magnumripper**
Bot check. This is less of a hack than I fear it would be. We should unify more of WPAPSK and WPAPMK code but that's a separate issue.

### CODE REVIEW

**Comment by rofl0r** [comment]
are there plans to enhance wpapcap2john.c with the capability to create the hash type, so we don't need to use hashcat's tools ?

**Comment by kholia** [comment]
https://github.com/ZerBea/hcxtools support hashcat and JtR, both.

The project description says -> Portable solution for capturing wlan traffic and conversion to hashcat formats (recommended by hashcat) and to John the Ripper formats.

**Comment by rofl0r** [comment]
does that mean wpapcap2john is deprecated in favor of hcxtools ?

**Comment by magnumripper** [comment]
hcxtools are great but I do plan to add support for them in wpapcap2john. Added an issue #3364 for it now.

**Pull request merged**
