### PR TITLE
Add support for cracking Telegram (Android) hashes

### PR DESCRIPTION
**Pull request by kholia**
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3183.

The passcode length is limited to 4. So no GPU support is needed ;)

@Banaanhangwagen You might be interested in this. Thanks for your work on this topic!

### CODE REVIEW

**Comment by magnumripper** [comment]
There's a flag `MGF_INPBASE64m` that should be usable for this.

**Comment by magnumripper** [comment]
Hmm apparently that flag makes the hash Base64, which isn't what we want.

**Comment by magnumripper** [comment]
Since the input length totals 36, we shouldn't need MGF_FLAT. Dropping that would be a good boost.

**Comment by magnumripper** [comment]
> Since the input length totals 36, we shouldn't need MGF_FLAT. Dropping that would be a good boost.

I tried this to no avail. Also, dynamic_61 is no faster than this anyway.

**Comment by kholia** [comment]
Thanks for experimenting with this.

**Pull request merged**
