### PR TITLE
timer.h: Use CLOCK_MONOTONIC_RAW if available.

### PR DESCRIPTION
**Pull request by magnumripper**
See #3949

### CODE REVIEW

**Comment by solardiz** [comment]
Are we somehow linking with `-lrt` when that code version is enabled? If not, we should expect linkage issues on some systems - not only with this change, but also before, since apparently we were already using `clock_gettime`.

**Comment by magnumripper** [comment]
> Are we somehow linking with `-lrt` when that code version is enabled? If not, we should expect linkage issues on some systems - not only with this change, but also before, since apparently we were already using `clock_gettime`.
> 
> Edit: if we haven't run into such issues, then maybe ` _POSIX_TIMERS && defined(_POSIX_MONOTONIC_CLOCK)` somehow isn't true, and this is dead (source) code?

Oh. You introduced `clock_gettime` in 01085c0a3f, but I missed this detail when merging so we don't have anything in `Makefile.in` (except, for some other reason, for Solaris builds, see `src/m4/jtr_systems_specific_logic.m4`). Apparently no-one has had problem with it yet! But we should fix this.

**Comment by magnumripper** [comment]
> Edit: if we haven't run into such issues, then maybe ` _POSIX_TIMERS && defined(_POSIX_MONOTONIC_CLOCK)` somehow isn't true, and this is dead (source) code?

No, that very code added nanosecond resolution under Linux. Besides, your use of it in yescrypt doesn't seem to fail.

**Comment by magnumripper** [comment]
#3984 added for the lack of `-lrt`.

> (...) see my other comment here for related concerns about both the original and the changed code.

I too am not happy with it: Like I said we should definitely stop using `double` for a starter. But I'll merge this for now, after adding a fix for #3984 as well. And we'll revisit this later.

**Comment by solardiz** [comment]
> Besides, your use of it in yescrypt doesn't seem to fail.

It did fail without `-lrt` on some systems, but the use is only in the `userom.c` program, which we don't build in JtR.

**Pull request merged**
