### PR TITLE
Revision of x86-sse.h and x86-64.h after core merge. #3696

### PR DESCRIPTION
**Pull request by magnumripper**
These are hard to review here. A better way is eg. `git diff origin/master..origin/botcheck x86-64.h` to compare the core files against the Jumbo ones.

### CODE REVIEW

**Comment by magnumripper** [comment]
I haven't tested 32-bit at all, I'm not sure I can find a machine for that. Build bots to the rescue though!

**Comment by solardiz** [comment]
> I haven't tested 32-bit at all, I'm not sure I can find a machine for that.

On a 64-bit system, you can probably do `setarch i686 bash` and then build from that shell. You'll need to have 32-bit libraries installed. I think we have such libraries installed at least on "well".

**Comment by solardiz** [comment]
1. These blocks
```
#if CPU_FALLBACK && !defined(CPU_FALLBACK_BINARY)
#define CPU_FALLBACK_BINARY            "john-non-avx512bw"
#define CPU_FALLBACK_BINARY_DEFAULT
#endif
```
Can probably be changed to one-liners like:
```
#define CPU_FALLBACK_BINARY_DEFAULT    "john-non-avx512bw"
```
like I do in core, followed by this shared block I added to core recently (is it somehow missing from master branch here?!):
```
#ifndef CPU_FALLBACK
#define CPU_FALLBACK                    0
#endif
#if !defined(CPU_FALLBACK_BINARY) && defined(CPU_FALLBACK_BINARY_DEFAULT)
#define CPU_FALLBACK_BINARY             CPU_FALLBACK_BINARY_DEFAULT
#endif
```

2. The added `#ifndef BF_X2` ... `#endif` can be dropped - I think they're remnants of jumbo's checking of the HT flag in configure, now dropped. Also, x86-sse.h has this logic in only one of two places, so it's broken anyway.

3. Minor bug: x86-64.h forgets to set `CPU_DETECT` and `CPU_REQ` to 0 when these things are not needed. Perhaps it should.

4. x86-sse.h's hack of `#define __SSE2__ 1` for MSVC without OpenMP (why?) looks very dirty and might be problematic (if MSVC either defines this on its own or would refuse to recognize the intrinsics when SSE2 isn't properly enabled in the compiler - at least we'd have these issues if we tried that hack with gcc, so I'd expect similar from MSVC). It's not a new thing with this PR, though.

**Comment by magnumripper** [comment]
I found some really old Thinkpad (32-bit. only SSE2 and single core) in the garage and everything seemed fine there.

**Comment by magnumripper** [comment]
> The added #ifndef BF_X2 ... #endif can be dropped - I think they're remnants of jumbo's checking of the HT flag in configure, now dropped. Also, x86-sse.h has this logic in only one of two places, so it's broken anyway.

I'll look into this tomorrow. I'll merge this for now.

The `#ifndef BF_X2` is (I think) for being able to do things like `./configure BF_X2=3 (...)`

**Pull request merged**
