### PR TITLE
Base64_decode converted into base64_convert calls

### PR DESCRIPTION
**Pull request by jfoug**
Removed base64.[ch] and use code from base64_convert.

NOTE, base64_convert used to actually USE the functionality of base64.c, so that had to be added to base64_convert.c   

Bug #2952

### CODE REVIEW

**Comment by jfoug** [comment]
Still have a bit of CI self testing, and am leaving until later tonite.  I will get to this on Sunday.

**Comment by magnumripper** [comment]
I'll review this once it passes the build bots. This branch seem to be tested by all bots BTW.

**Comment by jfoug** [comment]
The circle is not testing.  Click on the 'x'     It shows up but does no tests.    Let me test this by hand, before merging it.

**Comment by kholia** [comment]
The associated CircleCI build job says `The following services are not supported on macOS containers: docker`. This is weird as we are not using macOS on CircleCI platform.

@jfoug The CircleCI tests are easy to replicate on a local Fedora virtual machine. Just run the `CircleCI-MinGW.sh` script after doing some minor setup work.

**Comment by jfoug** [comment]
Note, I fixed some possible bugs I found in the null termination logic.  I also redid the base64 decode logic to use a table driven set of data.  I simply made a tiny test bed program to generate the table data, based upon original iterative logic.  Now the decodes are done quite a bit faster.  The time taken for the base64_conv_tst.sh went from 46s to 38s   But note, only part of what it does is decodes.  It also does a lot of encoding, and that was not touched.  I could change encoding, but I do not see the point.  In john, about the only thing we do with mime, is decode it.  It is rare to encode, and when done, it is not speed critical, it is one-off.  At least decoding is done multiple times (during data load).  I think about the only time we encode, is on sourcing, if at all.

**Comment by jfoug** [comment]
I had MacOS build checkbox set one time. It is now cleared.

**Comment by jfoug** [comment]
Btw, this has been tested, SIMD and non SIMD.  Also did test/base64_conv_tst.sh testing on all environments, and things are happy there also.

Whoever merges this, also can close #2952   (Or I can do both).

**Comment by jfoug** [comment]
I will build with ASAN and see/fix them.  Thanks for warning me.

**Comment by jfoug** [comment]
@magnumripper   GOOD catch, and not as simple a fix as I was hoping.  Changing the code to get the null termination right is the cause, but it was wrong before, AND still had potential to have issues.

Some of the problem stems from the older +3/+4 sizes we had added to buffers for the older crap mime decode logic, and then some buffer which are simply silly oversized.  In those instances, the code does not take the 'expected' pathway, but does a normal decode of a full limb, when there was not a full limb there.

I thought i had it worked out, the TS stuff was working fully again, and a ASAN run went a long way, BUT the ASAN run still crashed much later on, so I still have work to do still :(

**Comment by jfoug** [comment]
@magnumripper I see no asan errors.  Please dismiss your review once you are satisfied that the problem is gone on your end.

Ignore the CircleCI   It is not building.

**Comment by solardiz** [comment]
I think we should keep and continue to use `base64_decode()` as a wrapper (OK to make it an (inline) function or a macro) around `base64_convert()`, rather than change all callers to the more complicated "syntax".

The lookup tables should be `const`. Then the compiler might put them in `.rodata` or `.text`, which are typically in fact on read-only pages, so any attempted overwrites would be detected and prevented, rather than result in weird behavior.

**Comment by magnumripper** [comment]
I agree with Solar, I always thought usage of the `base64_convert()` functions were nigh impossible to remember. And the const remark is good too - we still make far too little use of it.

**Comment by magnumripper** [comment]
From Travis:
```
Testing: RAdmin, v2.x [MD5 32/64]... (2xOMP) PASS
Testing: RAKP, IPMI 2.0 RAKP (RMCP+) [HMAC-SHA1 128/128 AVX 4x]... (2xOMP) PASS
Testing: rar, RAR3 (4 characters) [SHA1 128/128 AVX 4x AES]... (2xOMP) 

The job exceeded the maximum time limit for jobs, and has been terminated.
```
Are we sure this is not a problem IRL? Why would this suddenly start to time out if not due to some endless loop bug?

**Comment by magnumripper** [comment]
Also, 8081.6 of https://travis-ci.org/magnumripper/JohnTheRipper/builds/311326180?utm_source=github_status&utm_medium=notification still fails ASan

**Comment by jfoug** [comment]
> I agree with Solar, I always thought usage of the base64_convert() functions were nigh impossible to remember. And the const remark is good too - we still make far too little use of it.

Ok, wanna talk confusion.  Just explain wtf it is:    base64_decode()   to anyone that does not know.

Is it mime to raw    (yes)  but the name gives no hint ...  is is crypt base64 to raw  (no, but it looks that way) ....   Also, how do you use it??   Put 1 char extra,  Or 2, .... or 3, .... or 4???   

If we keep this, we will continue to as the exact same questions, and have the same problems years from now.   Just saying.

**Comment by magnumripper** [comment]
That is true too 😆

**Comment by jfoug** [comment]
I know the base64_convert was a bit ugly (but hell, we are 'forced' into using old C which itself gives little in the way of help, lol).    BUT it is a single function, it has ALL parameters to do everything we need.

Now, if we want to add a few wrappers, we easily can:

mime_decode(in, len, out, len)  // null terminates (so out has to be 1 byte larger than max needed)
mime_decode_bin(in, len, out, len)
crypt64_decode(in, len, out, len)  // null terminates
crypt64_decode_bin(in, len, out, len)
aix64_decode(in, len, out, len)  // null terminates
aix64_decode_bin(in, len, out, len)

Those CAN be trivially added.  in fact, they COULD simply be put into base64.h, and be inline call through to the singleton base64_convert function .....     Again, just saying.   BUT keeping that singleton base64_decode (which really should be called mime_decode, since base64 is meaningless without knowing the alphabet and other transposition issues), is just asking for continued confusion, and latent bugs which often escape until someone does a HUGE fuzzing check.

**Comment by jfoug** [comment]
If people would WANT those type functions, let me add them into a 'new' base64.h file, and they will simply be #defines using the proper syntax to WORK without having to look up all that crap every time they are used.     Thoughts ......?

**Comment by magnumripper** [comment]
Maybe we can grep out all current uses and find common ones. We should only make shortcuts for common use-cases.

FWIW, one thing that I find disturbing (albeit just cosmetical in the very source code) is that we use a function called base64decode when we're converting between eg. hex <-> binary - no base64 involved at all. It's a fantastic function, but things like that is very strange. Perhaps we shouldn't touch it too much prior to a release though.

**Comment by magnumripper** [comment]
You need to trigger a re-build of CircleCI - it failed due to some intermittent f@ckup that happens every now and then (in main repo too).

**Comment by jfoug** [comment]
I agree with that.  what would be a 'better' name   encoding_convert() ?  Unificiation of hex and base64 does make for strange bedfellows.

**Comment by jfoug** [comment]
there will like be some changes (even if just cosmetic) so we can wait on that rebuild.   I have done 32 bit non-simd testing, so I am not overly concerned with it.  I also did FULL asan testing, so again, if the CIs fail intermittently, and they failed here, I am not concerned, since this is likely not the last version.

BUT I would like some form of acknowledgement of just WTF we want to see in the end, being if it is base64.h with 'common' easy to use macro interfaces, if we want to rebase the name of the exported function, what needs to be set to const, etc.  I have an idea on a lot of it, I just would like to make sure a single commit satisfies the numerous different but almost similar opinions of how things are best done.

**Comment by magnumripper** [comment]
I'd use `convert_encoding()` rather than the reverse but that really is a matter of taste. Wait, obviously it should be call `transvert()` or, shorter, `xvert()`, or dumber, `pervert()`.

**Comment by jfoug** [comment]
I like pervert_encoding best, but dont think I will stick that in code.  Only a few would get the inside joke.    I can live with convert_encoding.   Should we also rename the source file, to lose the base64 name (and the stand alone exe also?)

**Comment by magnumripper** [comment]
> Should we also rename the source file, to lose the base64 name (and the stand alone exe also?) 

Yeah why not. Perhaps something like, simply, convert.[ch]? Is the stand-alone exe build by default? I never used it ever, I do things like that with perl one-liners.

**Comment by jfoug** [comment]
how about convert_base   vs convert_encoding ?  Or strconvbase

**Comment by magnumripper** [comment]
I like convert_base! That's what it does.

**Comment by jfoug** [comment]
I will do convert_base.  Put it in convert_base.[ch] (not in simply convert.[ch]   Convert by itself is just too generic.   This is a much more clear name (due to the ambiguity), that base64_convert any day.

**Comment by jfoug** [comment]
Here is the entire 'simple' interface.  Simple going to do this with macros.

```c
// SIMPLE to use interface into this complex function:  The standard simple format is:
//    function(const void *input, size_t input_len, void *outupt, size_t output_len)

#define mime_decode(in, ilen, out, olen)        convert_base(in,e_bConv_mime,ilen,out,e_bConv_raw,olen,flg_ConvBase_NO_FLAGS,NULL)
#define mime_decode_bin(in, ilen, out, olen)    convert_base(in,e_bConv_mime,ilen,out,e_bConv_raw,olen,flg_ConvBase_DONOT_NULL_TERMINATE,NULL)
#define crypt64_decode(in, ilen, out, olen)     convert_base(in,e_bConv_crypt,ilen,out,e_bConv_raw,olen,flg_ConvBase_NO_FLAGS,NULL)
#define crypt64_decode_bin(in, ilen, out, olen) convert_base(in,e_bConv_crypt,ilen,out,e_bConv_raw,olen,flg_ConvBase_DONOT_NULL_TERMINATE,NULL)
#define aix64_decode(in, ilen, out, olen)       convert_base(in,e_bConv_cryptBS,ilen,out,e_bConv_raw,olen,flg_ConvBase_NO_FLAGS,NULL)
#define aix64_decode_bin(in, ilen, out, olen)	convert_base(in,e_bConv_cryptBS,ilen,out,e_bConv_raw,olen,flg_ConvBase_DONOT_NULL_TERMINATE,NULL)
#define hex_decode(in, ilen, out, olen)         convert_base(in,e_bConv_hex,ilen,out,e_bConv_raw,olen,flg_ConvBase_NO_FLAGS,NULL)
#define hex_decode_bin(in, ilen, out, olen)	    convert_base(in,e_bConv_hex,ilen,out,e_bConv_raw,olen,flg_ConvBase_DONOT_NULL_TERMINATE,NULL)
```

**Comment by magnumripper** [comment]
Isn't `hex_encode` common enough too? That is, bin -> hex.

**Comment by solardiz** [comment]
I think the `mime_decode` name is very confusing. Far more so than `base64_decode` was. There's a separate RFC on the base64 encoding used by MIME, and then there are several RFCs on MIME itself, which is a pretty complex beast going way beyond this little encoding.

I think `base64` would be pretty clear to most people. It only becomes unclear in the password hashing context, where a different base 64 encoding exists for `crypt(3)` (and yet different one for `bcrypt`). But we could stick with the `base64` name anyway, for no better alternative. Calling this `mime` is just wrong and confusing. If anything, it's `mime_base64`, but even that is confusing because that encoding is not actually tied only to MIME in RFCs (there are many others that refer to the base64 encoding RFC alone).

**Comment by jfoug** [comment]
@solar, what are your suggestions here.

This whole thing is a bigger cluster fuk now, than when I started on it, and I have spent a lot of time already.   I am sorry if the concept of a single function was too difficult for some to understand, but the way things were before, with base64_convert, IMHO was by far the best solution.  It contained all params needed, in one simple function.  All of the complex shit was hidden inside the code done by that 1 call.

Yes, the name DOES suck.  base64_convert,  (much like generic_md5 was), started out as one thing, but then due to the interface being 'complete' morphed into doing more (like hex work).  Yes, a simple change like str_base_convert  or possibly simply just base_convert may have been a better name.  There is always a string involved (either input or output must be a string, this function does not go from raw to raw.  In the end, it may not end up with a 'C' string (i.e. may not null terminate), but it still falls under the str_* namespace as it is working with string in the relative sense.

For now, I am putting this work on hold. I REALLY would like others thoughts put into this.    Btw, it is a LOT of work (a lot has already been done).  This is not work that can be scripted.  It has to be done one at a time

**Comment by solardiz** [comment]
I'm sorry, I have no time for this. I just expressed my opinion that the `base64_decode` name was fine and that `mime_decode` is a lot worse. That's all.

**Comment by jfoug** [comment]
But again for the name, base64_decode, just what does it mean?  Mime character set?  Mime character set with -_ vs +/   Mime chars with ./ vs +/   base64 but crypt alphabet.   Crypt alphabet but with . padding, mime alphabet but with = padding.

that is the run when used in jumbo.  The simple name of base64_decode is very ambiguous.

Now we could change the original interface to simply be:

```C
base64_decode(in, ilen, out, olen, flags);  // the flags ARE needed to handle all the types.
base64_encode(in, ilen, out, olen, flags);
hex_decode(in, ilen, out, olen);
hex_encode(in, ilen, out, outlen);
hex_encodeU(in,ilen, out, olen);
```

and then try to come up with easy names for the length variables.   THIS is what I tried to do with the macros, while placing the base64 alphabet name into the macro name.  But this you did not like.

I am going to put this on the back burner for a while, until we get a better consensus of what to do.  The code as it exists today (minus the broken base64_decode functions), works flawlessly.  I will keep my changes in a branch in my repo, but I am moving on, until i get clear advise and consensus. I would be investing quite a bit of time (already have), and touch a lot of files, and in the end, have nothing any better, and still have everyone thinking it is not ideal.  So right now, I simply an going to close this PR, and move on.   We can pick it up later.

I will instead simply convert the base64_decode into proper calls to base64_convert() function to avoid any overflow issues.

**Comment by magnumripper** [comment]
Then let's forget about the shortcut front-ends for now, but perhaps still rename the existing `base64_convert()` function, like we said, to `convert_base()`. There's no reason to put that on hold, is it?

The rest can certainly wait eg. until after next release. Right now we should probably focus on testing and bug-fixing, not refactoring.

**Pull request closed without merging**
