### PR TITLE
Comment about rawSHA256/512 rounds reversing

### LINKED ISSUE #2227: Reverse 4 rounds more in SHA-256 and SHA-512 OpenCL kernels
Just off Twitter:

```
<hashcat> New SHA2 meet-in-the-middle optimization quick writeup: https://hashcat.net/forum/thread-5778.html
<@solardiz> @hashcat So it's 57 steps for SHA-256, 73 for SHA-512, 61 for SHA-224, 77 for SHA-384. That's what we have in simd-intrinsics.c.
<@hashcat> @solardiz I made sure it's not in JtR, but i was looking in kernels/sha256_kernel.cl -- not there
<@solardiz> @hashcat Yeah. We also lack on-GPU mask mode for raw SHA-512, but we do have it for raw SHA-256, so makes sense to add this opt.
<@hashcat> @solardiz Good, it then explains why I couldn't see it
<@solardiz> @hashcat Thanks for reminding us to add it for OpenCL. Looks like Aleksey Cherepanov was first to find it http://www.openwall.com/lists/john-dev/2015/09/23/2
```

We also have these in CUDA - perhaps we don't care to optimize the CUDA code anymore (and it also lacks mask), but maybe add comments about possible yet unimplemented optimizations in there, along with a suggestion to look at and use the OpenCL kernels instead.

### PR DESCRIPTION
**Pull request by claudioandre-br**
Closes #2227

### CODE REVIEW

**Comment by claudioandre-br** [comment]
> Please remove the words " on super" from the two instances of the comment, because this is too specific to our current machines whereas the comment should be generic enough to stay relevant for years and not only to ourselves. 

In fact, I should change from super to GeForce GTX TITAN X. Otherwise, neither I can understand.

**Comment by solardiz** [comment]
Perhaps to "Titan X Maxwell", since there's also a "Titan X Pascal".

**Comment by claudioandre-br** [comment]
I don't have enough power to merge this one.

**Comment by solardiz** [comment]
I also don't. Let's wait for CI or magnum.

**Comment by magnumripper** [comment]
Have I messed something up with the build bots, or did they spontaneously break at the same time?

**Comment by claudioandre-br** [comment]
> Have I messed something up with the build bots

In this case, GitHub did.

**Pull request merged**
