### PR TITLE
Add OpenCL support for SHA-256 based S2K

### PR DESCRIPTION
**Pull request by kholia**
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2788.

There are some hacks present (e.g. addition of `int format` ) but it works (TM).

### CODE REVIEW

**Comment by kholia** [comment]
I had the same thought while writing this format.

I don't know how to use both `sha1` and `sha256` kernels from a single OpenCL format.

Please free to hack on this on my branch.

**Comment by magnumripper** [comment]
There's nothing to it, we have formats that does similar things. I do not have time to work with this.

You could add functions and kernels to the existing GPG `.cl` file instead of adding another one. Or you could keep it this way and build/load both, from one same host format. It's not even tricky.

**Comment by kholia** [comment]
No worries. I will give it (a single OpenCL format) a shot.

**Comment by magnumripper** [comment]
office_kernel.cl is an example where there are several alternative kernels in one same file, and the host code picks the right one for each salt.

**Comment by kholia** [comment]
@magnumripper Thanks for the hints. I have the unified OpenCL format working now.

You were right. There is not much to it, and the final code is much simpler than what I had before.

**Pull request merged**
