### PR TITLE
Fix for 31-character passwords on PKCS12 (off-by-one error)

### PR DESCRIPTION
**Pull request by chris-pcguy**
Signed-off-by: Christian Inci <chris.gh@broke-the-inter.net>

### CODE REVIEW

**Comment by kholia** [comment]
@chris-pcguy Thanks for the PR. Can you explain why this change is necessary? Do you have a test case to indicate that 31 character long passwords are not handled correctly?

**Comment by chris-pcguy** [comment]
It shouldn't use an additional block for 31, 63, 127, ...-character passwords

{"$pfxng$1$20$2048$8$8a4a0ba026e93132$308204583082027706092a864886f70d010706a0820268308202640201003082025d06092a864886f70d010701301c060a2a864886f70d010c0106300e0408af17a2ebf12476a5020208008082023065ad0c71081c2d50e73692bfef56e0d6e06b48dbb0b9d4ed7fd9a49e13c38996d3885bc340d591f6ac6978cd01ac55df6d237996cc470c777019377cd123709dfd13b78b5801607e14dab2f52a4e94e58e8142217b153f11e9ddef4cd8344042007346a29c21495d674fa11b7a6ff79347cc90a0a5b4fbcce5a6c21d8b6d8be0a4c0f84041e1c846b023050009a31f7fdd63dfbe5c179b1cdc56b6c6df6b9bd215c71a1c318b619da29cdfd0bcaabff5a6835b051d2ff5a02f3d02b95115d867d77a6c692aeb9619938614598ca84e60949dc868c890b9daae50d55a1ed02ee01975b769ca8eb18b909136e1a32c096ab767b97fd60d3b182870ddabf0b5a65ef6e8c69e8918e966fb7475c6b5263dad23534c843ad87dad85f81671cafe6b52f832051314d859c196f0b5e4228dfa20085604ee4cfc99d5f2c35b76930007d0f5d4a7bad060081a93b70752f4575679320f2b8914930c19e0e59cf95276504617681d5ef745380981537846466ddd9cf8130f157c3b2688749cb071fa36ec12157b57349b932fe5d635b853b5ba399a7e4113c639b45dcb618228d1e8a2077963c2c8f670a0189432d59d7ef915f00aa7171d9653c413aea748033cc60c37e3af9b9cdea29fecaf0fcc0d960cbf2da468c7b52b61860c8cfcc841d5bc2fe5605a34686d31c9fff66cb9a7830415b8eb0d2981c757660297d7d9843309bc26f2eded4800b34027e661e22ac3f3da82749d4bac74e02c017fd0a339f0bb400627c8d31684f30fd0e81d0973154eff06c5308201d906092a864886f70d010701a08201ca048201c6308201c2308201be060b2a864886f70d010c0a0102a082018630820182301c060a2a864886f70d010c0103300e040873a3921c345b0bd702020800048201600b7098f289339c8d8756fdd00f63883126ea62ca6b7d8b27cc40075e6e3d952fbd3074084a70d54619f875ff4af0a8da823c1110a4914259cfe03ae35798d0ebbb6ac43e7272bee2365bc5beb8a80d0cb8cca06fd18e2f6db5a9410650b6f4075dae2c5bb0b373b398c18fb41bbf76a6abb921d3a92612e10275aaea600fbc3d2686c44231159e3a63206aa7188ebd0815468bdd943c3866ab34a3b4f87c848154d3dc7e006662474e41cf162738c081033668397729a3fc92919f6044b1241ff1d2f300a42e54963d3d19b5201d4ec4e6b199225e23aaaed056da321075585da9889242378f5027c4ee8d999eac2b2fb5493fa0de8f2291cf75cdb29edf4cd53ac5c702ab3c41598b0bb99453571c50ac4aa3fbf23a0070b05779886550a7fdc0f3ecae4c730d3d031ac0b91397385a10bcd98f34e132d326895a35b3132b1cdc59bb7eaa9312be82861325a5fd6b0f8208530644cc1b96277f9e7701b243f73125302306092a864886f70d0109153116041400e22764f0d0103973b2d4c26925cc9985eebf14$d9d1c9053ad4101943f883baffa11eab65f73e97", "abcdefghijklmnopqrstuvwxyz12345"}, // 31

Here's the log output for the PFX-SHA1 31-character example:
v2: 128; pwdlen: 64; pwd_block before: 006100620063006400650066006700680069006A006B006C006D006E006F0070007100720073007400750076007700780079007A003100320033003400350000006100620063006400650066006700680069006A006B006C006D006E006F0070007100720073007400750076007700780079007A003100320033003400350000
Session completed

v2: 64; pwdlen: 64; pwd_block after: 006100620063006400650066006700680069006A006B006C006D006E006F0070007100720073007400750076007700780079007A003100320033003400350000
abcdefghijklmnopqrstuvwxyz12345 (mycert31.pfx)

**Comment by magnumripper** [comment]
Merged manually. Thanks a lot for finding and fixing this.

**Comment by kholia** [comment]
I think `opencl_pkcs12.h` file needs a similar fix.

**Comment by chris-pcguy** [comment]
@kholia:

There's one.

-	v2 = ((pwdlen+64)/64)*64;
+	v2 = ((pwdlen+64-1)/64)*64;

Did I missed another place?

**Comment by kholia** [comment]
@chris-pcguy That should be the last file needing the change. Thanks!

**Comment by kholia** [comment]
I just noticed that commit a77ce6bff295d788083abc54056f807496736bfe fixed `opencl_pkcs12.h` too 👍

**Pull request closed without merging**
