### PR TITLE
Gcc extra warnings (do not merge)

### PR DESCRIPTION
**Pull request by jfoug**
#3611

There are still a few errors left.  But those have much larger footprint on source code changes.  I am working to put those commits together.

THIS PR is not merge ready yet. There will be more commits.

### CODE REVIEW

**Comment by jfoug** [comment]
Ok, if this fails again, I will put it off for the night, get some sleep, then work to log into the CI's and modify the configure.ac until things work again (or figure out which source files require improvements).

**Comment by jfoug** [comment]
FINALLY.  Now I have big log files to look over, looking through all of these warnings for data which 'may' need fixed (i.e. warnings that REALLY do matter).  A lot of them are likely fluff, or invalid compiler warnings.

I see a LOT of them being things like strict alias rules.  But this seems to be a VERY old compiler, and this warning is not apparent in more recent compilers.  This could be combinations of compiler/OS, and possibly there are issues being picked up by the CI's.    But since I am building 32/64 bit cygwin and 64 bit Fedora29 and not seeing those, them im not over concerned by them.  I DID find several 'real' alias rules being broken, and fixed those (in 646f7b1 ).  I will start digging through the CI data.

Now, as it stands, I have added a --enable-exwarn  This turns on all of the extra warnings.  It also changes a 'few' of the --error=warning  into -Wwarning so that the compile will continue.   I had to do this to get it to pass Travis.  There were simply way too many errors (which were not showing up in other areas), on travis. So I (temp) changed the travis build to do the --enable-exwarn   and removed the --enable-werror.

**Comment by jfoug** [comment]
Now that i have this where it will pass the CI's, I will get the additional things I have accounted for  ``` -Wmissing-declarations ```  And then continue looking into the warnings to see which should be addressed, and which should be ignored as false warnings providing no better quality to the code base

**Comment by claudioandre-br** [comment]
Deprecated. Not mergeable.

**Pull request closed without merging**
