### PR TITLE
BitLocker: Extend OpenCL password length and use common tests

### PR DESCRIPTION
**Pull request by kholia**
This tries to cleanup https://github.com/magnumripper/JohnTheRipper/pull/2728 and extend it a bit.

@e-ago Please review this pull request and make sure that I have included all your code changes. Thanks!

@e-ago I have two requests for you. First, can you please add code comments in the OpenCL kernel? Specifically, I would like to know which parts of the kernel are doing SHA-256 operations, and which parts are doing the AES-CCM operations. Second, can support for password lengths < 8 be also added?

### CODE REVIEW

**Comment by magnumripper** [comment]
> Second, can support for password lengths < 8 be also added?

Does Bitlocker allow that in real life? If it does, this is absolutely mandatory.

**Comment by kholia** [comment]
@magnumripper I am wondering about the same. I will try generating such a test vector soon on Windows 10.

**Comment by kholia** [comment]
The minimum password length seems to be 8 for BitLocker,

bitlocker-minimum-length-is-8

**Comment by e-ago** [comment]
Thank you. Yes, 8 is the minimum length

**Comment by magnumripper** [comment]
https://technet.microsoft.com/en-us/library/jj679890(v=ws.11).aspx
*Passwords must be at least 8 characters. To configure a greater minimum length for the password, enter the desired number of characters in the Minimum password length box.*

If I get that technote right, it's configurable - but even then you can't set it shorter than 8.

**Comment by kholia** [comment]
@magnumripper I agree with your interpretation of the technote.

**Pull request merged**
