### PR TITLE
Add support for cracking Ansible Vaults

### PR DESCRIPTION
**Pull request by kholia**
I am still working on,

* Avoiding `cracked` logic (DONE)

* OpenMP tuning (DONE according to https://github.com/magnumripper/JohnTheRipper/issues/3091)

* GPU format. Do we have HMAC-SHA256 on the GPU?

I might leave the GPU support for a new PR.

### CODE REVIEW

**Comment by kholia** [comment]
GPU support will requires `pbkdf2_hmac_sha256_kernel.cl` to support generation of 64-byte keys. It currently outputs 32-byte keys only. Maybe @jfoug or @magnumripper can be persuaded to look into this ;)

**Comment by magnumripper** [comment]
I think that's more-or-less as easy as adding the following (this from pbkdf2_final for SHA-1, a few figures need to be adjusted accordingly)
```c
        /* Was this the last pass? If not, prepare for next one */
        if (4 * base + 20 < OUTLEN) {
                _phsk_hmac_sha1(state[gid].out, state[gid].ipad, state[gid].opad,
                                salt->salt, salt->length, 1 + pass);

                for (i = 0; i < 5; i++)
                        state[gid].W[i] = state[gid].out[i];

#ifndef ITERATIONS
                state[gid].iter_cnt = salt->iterations - 1;
#endif
        }
```

**Comment by kholia** [comment]
@magnumripper How does the "skip_bytes" functionality work? Can it provide a speed-up in this case, since we don't use the starting 32 bytes? I am guessing no.

**Comment by kholia** [comment]
Current speed on i7-6600U,

```
$ ../run/john --test --format=ansible
Will run 4 OpenMP threads
Benchmarking: ansible, Ansible Vault [PBKDF2-SHA256 HMAC-256 256/256 AVX2 8x]... (4xOMP)
Speed for cost 1 (iteration count) of 10000
Warning: "Many salts" test limited: 16/256
Many salts:	984 c/s real, 244 c/s virtual
Only one salt:	950 c/s real, 240 c/s virtual
```

**Comment by magnumripper** [comment]
I don't think so but I really can't remember what it actually does... @jfoug do you?

We should find a format that uses it and try to understand that (and document!). In general I can't see how we could ever skip data and get a valid PBKDF2.

**Comment by kholia** [comment]
I used the `skip_bytes` trick, and it provided no speedup. This is OK, and it matches your "can't skip data and get a valid PBKDF2" reasoning.

**Comment by magnumripper** [comment]
Apparently it's used in the ZIP format. But I haven't figured out what it does yet.

**Comment by magnumripper** [comment]
I think it's described here: http://www.openwall.com/lists/john-dev/2016/06/02/1

**Comment by kholia** [comment]
The `pbkdf2_hmac_sha256_kernel.cl` also doesn't support a variable `OUTLEN`. I believe that fixing this will require @magnumripper or @jfoug.

**Comment by magnumripper** [comment]
OK, the use case is like "generate 64 bytes of PBKDF2 but only use the **last** 32 of them". In that case, we can generate only the second chunk because it's independent of the first. Not applicable here (I think).

**Comment by kholia** [comment]
Yes, it doesn't seem to be application here. Thanks!

**Comment by magnumripper** [comment]
> I believe that fixing this will require @magnumripper or @jfoug.

LOL you are just lazy 😉  Anything you need to know is right before your eyes!

Please open an issue for it and assign it to me. I'll just finish off my work with #3165 first. Really cool functionality once I get the bugger to work correctly in all situations.

**Comment by magnumripper** [comment]
> I used the skip_bytes trick, and it provided no speedup. This is OK, and it matches your "can't skip data and get a valid PBKDF2" reasoning.

No it doesn't, you can skip full blocks (of the underlying hash functions output length, in this case 32 bytes) and get valid data - that's what 'skip bytes' is used for. I saw now you used it incorrectly (we need to document it somewhere!): A naive implementation is outlen 64 and no skip-bytes. You used outlen 64 after skipping 32. The correct use was outlen 32 after skipping 32. Fixed now (full 2x boost) and I will fix the GPU format today.

**Comment by kholia** [comment]
Nice! When I was looking at the format today, the output key length value `64` was looking odd next to the skip_bytes value of 32. I should have experimented more with this stuff earlier!

**Pull request merged**
