### PR TITLE
Move Claudio's SHA2 file to be a '-ng' format.

### PR DESCRIPTION
**Pull request by claudioandre**
Step 1:
- To revert to Myrice version.

### CODE REVIEW

**Comment by magnumripper** [comment]
Does your second commit screw up the filename changes, or am I just confused?

**Comment by claudioandre** [comment]
The second commit is there to give you some time.
- raw-sha512-opencl now can handle a lot of hashes without speed regressions (so, people will stop complaining for a while).

**Comment by claudioandre** [comment]
You can, when you have it done, replace these two files.
- src/opencl/sha512_kernel.cl
- src/opencl_rawsha512_fmt_plug.c

**Comment by magnumripper** [comment]
I think I get it :)

**Pull request merged**
