### PR TITLE
Change deprecated optparse to argparse

### PR DESCRIPTION
**Pull request by campeador**
Change deprecated optparse to argparse in:
- aix2john.py
- bitcoin2john.py
- blockchain2john.py
To fix part of this issue:  Python helpers overhaul #1057 
------EDITED----
Added:
- efs2john.py
- openssl2john.py

### CODE REVIEW

**Comment by magnumripper** [comment]
@campeador why did you close this, did you find problems with it?

**Comment by campeador** [comment]
Hi, no I do not . I pushed the new files and I thought that I have to close that. for see the code merge in the project. I reopen again.

**Comment by magnumripper** [comment]
No, you just need to wait for someone to review it and accept it :-)

I'm merging now. Thank you!

**Comment by campeador** [comment]
Hahahahha. Sorry, and thanks you very much.

**Comment by kholia** [comment]
@campeador 

It seems that this commit broke `openssl2john.py`.

```
$ ../run/openssl2john.py
Usage: ../run/openssl2john.py [-c cipher] [-m md] [-p plaintext] <... encrypted files>
cipher: 0 => aes-256-cbc, 1 => aes-128-cbc
md: 0 => md5, 1 => sha1

$ ../run/openssl2john.py -c 0 -m 1 -p "private" openssl-encrypted-file 
usage: openssl2john.py [-h] [-p PLAINTEXT] [-c CIPHER] [-m MD]
openssl2john.py: error: unrecognized arguments: openssl-encrypted-file
```

Note: We need to maintain compatibility with Python 2.4+, so using `optparse` is OK.

**Comment by campeador** [comment]
@kholia  

I changed it because of python documentation: https://docs.python.org/2/library/optparse.html

"Deprecated since version 2.7: The optparse module is deprecated and will not be developed further; development will continue with the argparse module."

And I believed that it was compatible with python 2.4+ because in the doc it says "New in version 2.3."

Sorry about this problem! :/

**Comment by kholia** [comment]
@campeador 

According to https://pymotw.com/2/argparse/, the argparse module was added in Python 2.7. So the following commit was not good for compatibility reasons.

```
commit d297620f3760cbd3cf4675c7cd1333bd00d8585d
Author: campeador <root@localhost.localdomain>
Date:   Sat Apr 25 00:11:55 2015 +0200

    Change optparse to argparse in efs2john.py and openssl2john.py
```

We will switch to optparse when upstream Python project actually drops the optparse module.

**Comment by campeador** [comment]
@kholia 

Ok, thank you and sorry for the mistake.

**Comment by kholia** [comment]
No worries. Please keep writing patches, and test them too! 👍

**Pull request merged**
