### PR TITLE
Update the ./configure script

### PR DESCRIPTION
**Pull request by claudioandre**
### Summary

It was missing some recent changes (783d27c2faaa135e7e567479bdb7f1b4f480958b).

### Other Information

From now on, any commit/PR will be tested using (from a real run) AVX2 and AVX. It seems to be random.

### CODE REVIEW

**Comment by magnumripper** [comment]
I presume this PR was the reason for the following but I have no idea why yet:
```
(...)
checking for Hyperthreading... yes
checking for MMX... yes
checking for SSE2... yes
checking for SSSE3... /var/folders/8p/_ckrr36x2yv96fjm8x7r_6q80000gp/T//ccnL36zt.s:3:8: error: invalid alignment value
.align 1 << 6
       ^
/var/folders/8p/_ckrr36x2yv96fjm8x7r_6q80000gp/T//ccnL36zt.s:29:8: error: invalid alignment value
.align 1 << 6
       ^
/var/folders/8p/_ckrr36x2yv96fjm8x7r_6q80000gp/T//ccnL36zt.s:33:8: error: invalid alignment value
.align 1 << 6
       ^
/var/folders/8p/_ckrr36x2yv96fjm8x7r_6q80000gp/T//ccnL36zt.s:56:8: error: invalid alignment value
.align 1 << 6
       ^
/var/folders/8p/_ckrr36x2yv96fjm8x7r_6q80000gp/T//ccnL36zt.s:122:8: error: invalid alignment value
.align 1 << 6
       ^
/var/folders/8p/_ckrr36x2yv96fjm8x7r_6q80000gp/T//ccnL36zt.s:238:8: error: invalid alignment value
.align 1 << 6
       ^
/var/folders/8p/_ckrr36x2yv96fjm8x7r_6q80000gp/T//ccnL36zt.s:399:8: error: invalid alignment value
.align 1 << 6
       ^
/var/folders/8p/_ckrr36x2yv96fjm8x7r_6q80000gp/T//ccnL36zt.s:610:8: error: invalid alignment value
.align 1 << 6
       ^
/var/folders/8p/_ckrr36x2yv96fjm8x7r_6q80000gp/T//ccnL36zt.s:642:8: error: invalid alignment value
.align 1 << 6
       ^
./configure: line 9157: ./test_SIMD: No such file or directory
no
checking for arch.h alternative... x86-64.h
(...)
```
This results in an SSE2 build here. I'm pretty clueless right now but it's probably something really really trivial.

**Comment by magnumripper** [comment]
The build bots didn't seem to encounter this problem... so maybe it's macOS specific? But why would that be?!

**Comment by magnumripper** [comment]
Confirmed - it's this very commit that breaks my build. No sweat, I'm investigating.

**Comment by magnumripper** [comment]
OK... macOS and other *BSD machines might need ALIGN_LOG defined. And other stuff - and other gear might need other other stuff.

grep for ASM_MAGIC

**Comment by magnumripper** [comment]
Did we not have a macOS (OSX) build in some bot?

**Comment by claudioandre** [comment]
> Did we not have a macOS (OSX) build in some bot?

Yes, but the PR OSX build is waiting to be queued for hours. I guess I have waited for some run to finish (but I might wasn't seen any OSX succeed).

**Comment by magnumripper** [comment]
So JTR_GENERIC_LOGIC needs to be called prior to JTR_X86_SPECIAL_LOGIC. The question is if this will get us into dependency hell... I'll try it locally right now.

**Comment by magnumripper** [comment]
This change unfortunately didn't change a thing (autoreconf was run too, just not included below)
```diff
diff --git a/src/configure.ac b/src/configure.ac
index a2cd1cf3d..6ab0ff1ac 100644
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -440,10 +440,10 @@ esac
 # macros for each environment.  We probably should fall back to calling
 # make -f Makefile.legacy clean generic or failing with an echo of that message,
 # for any environment we do not handle.
+JTR_GENERIC_LOGIC
 AS_IF([test "x$cpu_family" = xintel], [echo "checking special compiler flags... Intel X86*"] [JTR_X86_SPECIAL_LOGIC])
 AC_MSG_CHECKING([for arch.h alternative])
 AC_MSG_RESULT([${ARCH_LINK}])
-JTR_GENERIC_LOGIC
 
 # Set a variable detecting x86-64 w/ X32 ABI
 if test "x$ax_intel_x32" = xyes; then
```
So either we have a circular dependency or I'm too tired to think right now

**Comment by magnumripper** [comment]
I guess the ASM_MAGIC stuff needs to be ripped out and ran before JTR_X86_SPECIAL_LOGIC but the rest of JTR_GENERIC_LOGIC should be ran after it. I have no more time right now. Not sure if we should revert this commit or just let it be broken for a while - almost all users run Linux anyway.

**Comment by claudioandre** [comment]
Really no idea about what OSX is doing. But I checked this is ok on Linux. I can revert it now.

**Comment by magnumripper** [comment]
Hold on, I might be on to something

**Comment by magnumripper** [comment]
#2975

**Comment by jfoug** [comment]
@claudioandre  / @magnumripper  are you done with configure/configure.ac for a while?   I was getting a bit confused, and have some changes to for the ppc port, and for a bit of summary update. But I was a bit confused with what was going on, so I simply put those changes on hold until you had stabilized your changes.  Are you done for now?

**Comment by magnumripper** [comment]
Unfortunately not. We should either find a fix or revert some last changes. I'm considering just sleeping on it. I'm sure it's quite simple once we find out WTH is wrong now.

**Comment by magnumripper** [comment]
OTOH in the meantime you can push stuff. I'll probably do nothing for 24h+ now.

**Comment by jfoug** [comment]
No problem.   I put a PR out there, in case Solar could pull it and test on GCC compile box.   I swear, I had the formats all running on altivec, and now there are 14 failing. So I have work to do, before I could ever push for real.

But that fix to the status page is pretty safe.  The problem is (and I already have gotten there), that working on the same file is going to make merge failures.  that is why I am kind of pushing things off for a bit.

As for the autoconf stuff, if it is an apple problem (gawd I hate them), then simply let me autoconf the thing, and check it in.  I have no autoconf problems AFAIK.

**Comment by jfoug** [comment]
I think I will push the summary fix  (trivial).  The ppc stuff, I am working on a local branch. Once things get stable, I will sync my main branch, and simply create a new ppc branch and put all patches into that, and not really worry about the merge conflict crap.

**Comment by magnumripper** [comment]
#2978 should fix all problems with the CPUID changes. The bots are working on it.

**Pull request merged**
