### PR TITLE
Descrypt opencl

### PR DESCRIPTION
**Pull request by Sayantan2048**
@magnumripper please test and merge descrypt-opencl.

### CODE REVIEW

**Comment by Sayantan2048** [comment]
Some performance numbers(on 7970):
50.8Mc/s for basic kernel (i.e HARDCODE_SALT = 0 and FULL_UNROLL = 0)
84.9Mc/s for advanced kernel (i.e HARDCODE_SALT = 1 and FULL_UNROLL = 0)
145.5Mc/s for fully unrolled kernel (i.e HARDCODE_SALT = 1 and FULL_UNROLL = 1)

**Comment by magnumripper** [comment]
Cool, but could you please squash this into just one or a few (whatever is more logical) commits first?

**Comment by magnumripper** [comment]
Also, you seem to have debug code left in there
```
Local worksize (LWS) 64, Global worksize (GWS) 16384
Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... ciphertext:CCNf8Sbh3HDfQ
C:CCNf8Sbh3HDfQ B:229867404 0
C:CCX.K.MFy4Ois B:1489831955 0
C:CC4rMpbg9AMZ. B:-1602948785 0
C:XXxzOu6maQKqQ B:-1681529149 0
C:SDbsugeBiC58A B:-1981380088 0
C:..X8NBuQ4l6uQ B:1071711288 1
DONE
```

**Comment by magnumripper** [comment]
And Super's Titan fails
```
$ ../run/john -test -form:descrypt-opencl -dev=5

Device 5: GeForce GTX TITAN
Build log: 
ptxas info    : Compiling entry function 'DES_bs_25_b' for 'sm_35'
ptxas info    : Function properties for DES_bs_25_b
 256 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 78 registers, 15872+0 bytes smem, 352 bytes cmem[0]
Build log: 
ptxas info    : Compiling entry function 'DES_bs_finalize_keys' for 'sm_35'
ptxas info    : Function properties for DES_bs_finalize_keys
 0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 35 registers, 328 bytes cmem[0]
OpenCL error (CL_OUT_OF_RESOURCES) in file (opencl_DES_bs_b_plug.c) at line (519) - (Write FAILED
)
```

**Comment by magnumripper** [comment]
Both of Super's CPU devices segfault
```
$ ../run/john -test -form:descrypt-opencl -dev=2
Device 2: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Segmentation fault

$ ../run/john -test -form:descrypt-opencl -dev=3
Device 3: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Build log: Compilation started
Compilation done
Linking started
Linking done
Kernel <DES_bs_25_b> was successfully vectorized
Done.
Build log: Compilation started
Compilation done
Linking started
Linking done
Kernel <DES_bs_finalize_keys> was successfully vectorized
Done.
Segmentation fault
```
And the MIC shows some other problem
```
$ ../run/john -test -form:descrypt-opencl -dev=4
Device 4: Intel(R) Many Integrated Core Acceleration Card
5 errors generated.
Options used: -I ../run/kernels -cl-mad-enable -DDEVICE_INFO=36 -D_OPENCL_COMPILER -DDEV_VER_MAJOR=1 -DDEV_VER_MINOR=2 
Build log: Compilation started
1:318:3: error: implicit declaration of function 's1' is invalid in OpenCL
1:234:3: note: expanded from macro 'loop_body'
1:165:2: note: expanded from macro 'H1'
1:318:3: error: implicit declaration of function 's2' is invalid in OpenCL
1:234:3: note: expanded from macro 'loop_body'
1:167:2: note: expanded from macro 'H1'
1:318:3: error: implicit declaration of function 's5' is invalid in OpenCL
1:234:3: note: expanded from macro 'loop_body'
1:175:2: note: expanded from macro 'H1'
1:318:3: error: implicit declaration of function 's6' is invalid in OpenCL
1:234:3: note: expanded from macro 'loop_body'
1:177:2: note: expanded from macro 'H1'
1:318:3: error: implicit declaration of function 's7' is invalid in OpenCL
1:234:3: note: expanded from macro 'loop_body'
1:179:2: note: expanded from macro 'H1'
Compilation failed

Error -11 building kernel $JOHN/kernels/DES_bs_kernel.cl. DEVICE_INFO=36
OpenCL error (CL_BUILD_PROGRAM_FAILURE) in file (common-opencl.c) at line (914) - (clBuildProgram failed.)
```

**Comment by magnumripper** [comment]
> Cool, but could you please squash this into just one or a few (whatever is more logical) commits first?

Actually 10 or more commits is fine too, but, for example, any two commits in a row with same name should obviously be squashed into one.

**Comment by Sayantan2048** [comment]
I can't replicate the problem on Titan. It runs just fine. But CPU is not working. I'll squash the commits with same name into a single one.

**Comment by Sayantan2048** [comment]
CPU is working with explicitly defined GWS values. Probably some problem with automated GWS finding. Working on it.

**Comment by Sayantan2048** [comment]
Fixed CPU device with a33973317df10d

**Comment by magnumripper** [comment]
Not sure what I was seeing on the Titan but it's gone now. What do you think about those MIC errors, are they driver bugs?

**Comment by Sayantan2048** [comment]
Yes and No. Those errors are bugs in the code, so I can remove them and get the kernels compiled. But the self-test still fails and this is likely a driver bug.

**Pull request merged**
