### PR TITLE
Publishing from Travis to Ubuntu Snap Store

### PR DESCRIPTION
**Pull request by claudioandre**
Please, I need to know if this patch is useful and could be merged. If so:

WIP
- I have to share a secret with travis:magnumripper/JohnTheRipper (but I can't save it using cli - I'm not magnum); I tried to submit it via web page; _Check if it is working_
- Easy to see that the 'ok' or 'fail' takes the same amount of time (not sure if anyone is online now to confirm); I did the check.
- These binaries can also became a ZIP to be used in Windows with  WSL (at some point in the 'near' future).
- Maybe something else 'secret' related.

It already works when the commit happens in 'my' fork.

---

Publishing bleeding-edge JtR to the snap store from Travis

Allow snap users to install, test and use the latest and hot bleeding-jumbo from git. The snap build process is not going to make Travis slower: build completeness will finish as soon gcc and clang have completed (as it does now).

If the user wants something hot:
$ snap refresh --channel=edge john-the-ripper

Unhappy? No problems, jump back when he/she can no longer take the heat:
$ snap refresh --channel=stable john-the-ripper

### CODE REVIEW

**Comment by magnumripper** [comment]
I'm not too happy with all the files in base dir, especially a Makefile that will confuse users. Can we create a new directory 'Travis' or '.travis' and have (some of) them there?

**Comment by claudioandre** [comment]
Done. What about the other concerns?

**Comment by magnumripper** [comment]
That was my only concern. Did you manage to share a secret? Or do we not quite know until it's actually merged?

**Comment by claudioandre** [comment]
> That was my only concern. 

After merge, any commit can be at users hands faster than before; I mean a 'Joe User'. There are commits that are not meant to be published, or shouldn't be.

> Did you manage to share a secret?

No, it seems that I can't encrypt using your public key (I used something, it is not mine but it is not accepted inside your magnumripper).

**Comment by claudioandre** [comment]
Just to document, I changed things a little:
- https://github.com/claudioandre/JohnTheRipper/commits/daily

**Comment by magnumripper** [comment]
If there's anything I can do to fix the shared secret issue, please let me know. I don't really have any idea what is needed.

**Comment by claudioandre** [comment]
I guess you have to run the 'travis --set-env' yourself - after I share the secret with you. 
****

Well, in order to test, I have been posting x64, armhf, arm64 and ppc to the edge channel (once a day, in fact). x64 with all fancy stuff using Travis. Others using canonical servers. BTW: I don't think I can do it all using only Travis CI.

That said:
- without the secret, my 'daily' branch behaves in Travis as it does now (build gcc, clang and test). Only if it knows the secret it does something else. I mean, a merge is already possible - after an approval.
- I'm not confident we can build edge packages for all archs without human intervention.
- for x64, any commit in my branch 'daily' will upload to the Store. So, a full automation is already in place.

**Comment by claudioandre** [comment]
I' going to use the build bots listed above:
- not 100% automated; A request via web is necessary.
- packages upload from build bots only [no user mistakes, sysadmins around, ...].
- the package announce itself using a commit hash.
- I know some people have installed the software, but I have no idea what real users are expecting:
  - daily builds? build more than once a day (why?)? Weekly?

So, I would like to hear from you guys:
- how often should I publish? What should be in stable channel? What about edge? 

****
Since .travis.yml is upstream, a merge is still desirable. Other files can be safely ignored.

**Comment by claudioandre** [comment]
It is not impossible to build to IBM System z (s390x). But, I guess nobody is interested.

**Pull request closed without merging**
