### PR TITLE
Add support for more ciphers in PEM format

### PR DESCRIPTION
**Pull request by kholia**
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3197.

The OpenCL format needs more attention with regards to OUTLEN (outlen) optimization.

### CODE REVIEW

**Comment by magnumripper** [comment]
From kernel comments
```c
 * For a fixed iterations count, define ITERATIONS. Otherwise salt->iterations
 * will be used (slower).
 *
 * For a fixed output length, define OUTLEN. Otherwise salt->outlen will be
 * used.
```

**Comment by kholia** [comment]
The OpenCL kernel doesn't build with the following patch,

```
$ git diff
diff --git a/src/opencl_pem_fmt_plug.c b/src/opencl_pem_fmt_plug.c
index b5f6a5dd6..9c48c36fb 100644
--- a/src/opencl_pem_fmt_plug.c
+++ b/src/opencl_pem_fmt_plug.c
@@ -191,9 +191,9 @@ static void reset(struct db_main *db)
                char build_opts[64];
 
                snprintf(build_opts, sizeof(build_opts),
-                        "-DHASH_LOOPS=%u -DOUTLEN=%u "
+                        "-DHASH_LOOPS=%u "
                         "-DPLAINTEXT_LENGTH=%u -DV_WIDTH=%u",
-                        HASH_LOOPS, OUTLEN, PLAINTEXT_LENGTH, ocl_v_width);
+                        HASH_LOOPS, PLAINTEXT_LENGTH, ocl_v_width);
                opencl_init("$JOHN/kernels/pbkdf2_hmac_sha1_kernel.cl", gpu_id, build_opts);
 
                pbkdf2_init = clCreateKernel(program[gpu_id], "pbkdf2_init", &ret_code);
```

Result,

```
Benchmarking: pem-opencl, PKCS#8 private key (RSA/DSA/ECDSA) [PBKDF2-SHA1 OpenCL 3DES]... (4xOMP) Options used: -I /home/user/JtR/run/kernels -cl-mad-enable -DSM_MAJOR=6 -DSM_MINOR=1 -D__GPU__ -DDEVICE_INFO=524306 -DSIZEOF_SIZE_T=8 -DDEV_VER_MAJOR=390 -DDEV_VER_MINOR=25 -D_OPENCL_COMPILER -DHASH_LOOPS=813 -DPLAINTEXT_LENGTH=64 -DV_WIDTH=1 $JOHN/kernels/pbkdf2_hmac_sha1_kernel.cl
Build log: In file included from <kernel>:60:
./opencl_pbkdf2_hmac_sha1.h:29:20: error: use of undeclared identifier 'OUTLEN'
        unsigned int dk[((OUTLEN + 19) / 20) * 20 / sizeof(unsigned int)];
                          ^

Error -11 building kernel $JOHN/kernels/pbkdf2_hmac_sha1_kernel.cl. DEVICE_INFO=524306
OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1115 - clBuildProgram failed.
```

**Comment by kholia** [comment]
I am merging this for now. Let's see if there is a better solution in the near future.

**Comment by magnumripper** [comment]
Oh, that's a bug then. I'll look into it later.

**Comment by kholia** [comment]
@magnumripper I have a related PR (https://github.com/magnumripper/JohnTheRipper/pull/3203) open now.

**Comment by magnumripper** [comment]
I merged that and then added b7fa69c2e which fixes the OUTLEN bug. Should double speed for some types. BTW you should probably add "cost" support.

**Comment by kholia** [comment]
Cool. I will add support for "tunable costs". Should I use the key_length as the cost? I don't have a better metric I think.

**Comment by magnumripper** [comment]
I think you should use `iterations * (key length > 20 ? 2 : 1)` as cost.

**Comment by frank-dittrich** [comment]
@magnumripper Are you sure it is OK to mix N iterations and key length > 20 and 2N iterations with key length <= 20?
Shouldn't that be two separate tunable costs: `iterations` and `key length > 20 ? 2 : 1` (not sure how to name this one)?

**Comment by magnumripper** [comment]
@frank-dittrich it's not a mix at all. The formula I listed is the actual number of iterations and nothing else: To get more than 20 bytes of key from `PBKDF2-HMAC-SHA1(n iterations)`, you need another `n` iterations. Actually for more than 40 bytes we'd need a more complete formula because it'd need `3 * n` iterations for 41-60 bytes and so on. But we only need up to 32 here, so it's either `n` or `2 * n`.

**Comment by magnumripper** [comment]
...so IMO this cost should be called "iterations" and nothing else.

**Comment by kholia** [comment]
@magnumripper I understand, and agree with your formula. Thanks!

**Pull request merged**
