### PR TITLE
"download" badge now downloads latest MinGW build

### PR DESCRIPTION
**Pull request by kholia**
The existing "download" badge was sort of redundant, since GitHub
already has a "Download ZIP" button

### CODE REVIEW

**Comment by kholia** [comment]
@frank-dittrich @jfoug what do you think about this "download" badge change?

**Comment by frank-dittrich** [comment]
@kholia you men besides the fact that the zip file doesn't contain the binary?

**Comment by kholia** [comment]
@frank-dittrich the old download badge used to download the source code (which could already be done by the "Download ZIP" button), the new download badge downloads the latest MinGW build archive (and it does have the "john.exe" file in it).

**Comment by frank-dittrich** [comment]
@kholia lack of coffe.
facepalm
In my first atrempt I tried the link in magnums repo.
In my second attempt I used your repo, but bleeding-jumbo branch 

I think there are people who want that MinGW build version, but there are also people who want to download a zip (or any other) archive with the latest source without the need to learn how to use git.
Not sure whether or not the src subdir should be included in the MinGW.zip file or not.
We also might want to include the (shortened) commit id into the file name.

**Comment by kholia** [comment]
https://github.com/magnumripper/JohnTheRipper page already has a "Download ZIP" button, which allows folks to download the latest source (without using git).

The idea of including shortened commit id into the build file name sounds great, thanks @frank-dittrich.

**Comment by frank-dittrich** [comment]
@kholia does that work without changing the README.md file with every commit?
If not it might be better to add that info into an additional file in the zip archive.

**Comment by kholia** [comment]
@frank-dittrich that is exactly what I am trying to solve now (without changing the README.md file) :)

**Comment by kholia** [comment]
@frank-dittrich try downloading again now :-)

**Comment by frank-dittrich** [comment]
looks good.
I just noticed that we might not even need the old download link, because there's also a "Download ZIP" button on the right hand side (below the `HTTPS clone URL` area
which also points to https://github.com/magnumripper/JohnTheRipper/archive/bleeding-jumbo.zip
You can even download a tar.gz archive:
https://github.com/magnumripper/JohnTheRipper/archive/bleeding-jumbo.tar.gz
(even though there's no button).

**Comment by kholia** [comment]
The "magic" behind this is in the https://github.com/kholia/daily-builds repository.

**Pull request merged**
