### PR TITLE
Just to check if it will hurt on CI

### PR DESCRIPTION
**Pull request by claudioandre**
I'm not confident yet!

### CODE REVIEW

**Comment by claudioandre** [comment]
This warning about UTF-8 is new:
```
../run/john ~/testhashes -form=raw-sha512-opencl -mask:mot?Arhead
../run/john: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ../run/john)
Using default input encoding: UTF-8
Loaded 16 password hashes with no different salts (Raw-SHA512-opencl [SHA512 OpenCL])
Warning: invalid UTF-8 seen reading $JOHN/john.pot
Remaining 1 password hash
Device 0: Tahiti [AMD Radeon HD 7900 Series]
Using Mask Mode with internal candidate generation, global worksize(GWS) set to 16384
Press 'q' or Ctrl-C to abort, almost any other key for status
mot�rhead           (?)
1g 0:00:00:00  2.380g/s 228.5p/s 228.5c/s 228.5C/s GPU:46°C util:59% fan:20% mot#rhead
```

**Comment by magnumripper** [comment]
You get that warning as a result of running non-UTF8 without telling john about it. You should use `--enc:latin1` or whatever applies to your hashes' encoding. I bet that would also fix the output for that test hash: The password is very likely "motörhead".

**Comment by frank-dittrich** [comment]
@claudioandre That warning started with  commit 90e21c5bae90258f7b6420cda8cc4a72b725c8ac, about two months ago.
It changed default encoding settings in john.conf

**Comment by claudioandre** [comment]
Oh, I can see the warning is harmless.

**Comment by claudioandre** [comment]
This seems good enough to be merge **after** the contest.

**Comment by magnumripper** [comment]
For faster testing, I'm merging now. The TS get seriously slowed down from `--list=format-details` being so slow without this.

**Comment by magnumripper** [comment]
See https://github.com/magnumripper/jtrTestSuite/issues/58#issuecomment-127463701

**Pull request merged**
