### PR TITLE
Revamp CI automated testing

### PR DESCRIPTION
**Pull request by claudioandre-br**
My 2 cents. What I would like to suggest. #3822
* simplify CI;
* run parallel tasks;
* target is a 10-15 minutes run;

Well, it fails because it is becoming really hard to test OpenCL stuff.
* pocl has too many bugs;
* AMD OpenCL for CPUs is dead.
* Ok, I can workaround it and make it pass. Anyway, we need a new OpenCL CPU driver.

We can try to test using Intel drivers, but it requires a volunteer that owns a Xeon.

``` 
#!/bin/bash -eo pipefail
.circle/circle-ci.sh TEST
-- Testing opencl '--encoding=utf8' --
Device 1: pthread-Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
Testing: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL, UTF-8]... /-\|/-\PASS
Testing: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES, UTF-8]... (2xOMP) |.circle/circle-ci.sh: line 78:  6403 Segmentation fault      $JTR -test-full=0 --format="$TARGET_TEST" --encoding=utf8
Exited with code 139
```

### CODE REVIEW

**Comment by solardiz** [comment]
> We can try to test using Intel drivers, but it requires a volunteer that owns a Xeon.

Why, Intel OpenCL runs fine on AMD x86-64 CPUs, as well as on Intel non-Xeon CPUs. The only problem is that yes - we need a volunteer who would set it up and maintain it.

**Comment by claudioandre-br** [comment]
I tried to use Intel drivers once. I failed. I does not work for me. I need
a full script (that works in someone's else machine) saying:
- wget http://site/file.file.zip-gzip-tar
- unzip file.zip-gzip-tar
- ./script

If the script works to him/her, the volunteer, I can try it inside CI.

**Comment by claudioandre-br** [comment]
Edited. works WITHOUT a reboot.

**Comment by claudioandre-br** [comment]
If we are still unconfortable with duration, I added manual task(s):

image

**Comment by claudioandre-br** [comment]
* Moved all Travis tests to Xenial;
* We are using a real Circle 2.0 now;
* OpenCL is based in Docker for reproducibility and repeatability;
* All but OpenCL tests are running in < 10 min.

**Comment by claudioandre-br** [comment]
Follow up (https://github.com/magnumripper/JohnTheRipper/pull/3823#issuecomment-483429153) 

image

**Comment by claudioandre-br** [comment]
We can run 5 parallel build in Travis.org. In Travis.com, usually 3 or 4. That said, I will move the ASAN test to Circle (where we have one empty slot).

That is all folks.

**Comment by magnumripper** [comment]
So this is ready to merge?

**Comment by claudioandre-br** [comment]
Yes. But, I'm not going merge before release to avoid noise.

**Comment by claudioandre-br** [comment]
I plan to merge all pending PRs because I'm going to clean up my repository. Otherwise, all non-merged code will be lost.

**Pull request merged**
