### PR TITLE
Added as400-des plugin and updated documentation

### PR DESCRIPTION
**Pull request by rschoem**
Addes as400-des format plugin.
Updated AS400 readme file with instructions on how to use

### CODE REVIEW

**Comment by kholia** [comment]
Some comments,

The "a2e" array is not used and can be removed I think.

@magnumripper should we keep the `$as400des$*AAAAAAA*CA2E330B2FD1820E` hash format, or should we change it to `$as400des$AAAAAAA$CA2E330B2FD1820E` (no asterisk character)? My bad for introducing the asterisk character as a delimiter.

The "des_key2[i++] = 0x2a;" line is indented with spaces. Can you please change it to tabs? 

Remember to squash your commits when you make the relevant changes.

Thanks for this awesome pull request :+1:

**Comment by frank-dittrich** [comment]
@rschoem can an AS400 user ID contain '$' or '*' characters? Or ':'?

**Comment by rschoem** [comment]
Alphanumeric plus a few special characters. $ # @ _ .

So $ as delimiter is not handy (will have a look at as400-ssha plugin as well, because we use $ signs there).

**Comment by magnumripper** [comment]
So keeping '*' seems best in this case. I did a quick review of the code and everything look good to me (but @kholia's remarks should be taken care of). And the build bots seem happy too.

**Comment by rschoem** [comment]
Fixed indentation. 
Kept a2e array as is, because array is used in ascii2ebcdic function (which in turn is used in get_salt).
Should be ok now.

**Comment by magnumripper** [comment]
Please squash those last two commits to a single one and force-push.

**Comment by rschoem** [comment]
ok, that will be an interesting "training on the job". (no idea how to do that :-P )

**Comment by magnumripper** [comment]
Assuming nothing in your working tree has changed:
```
git reset HEAD^
git add -vu
git commit --amend -C HEAD
git push -f
```

**Comment by rschoem** [comment]
@magnumripper Is it doable for you to "squash" these? I started of from the webinterface and just uploaded the files, (so I didn't use the cli). 
I didn't have time to really look into the cli, but I quickly tried some things but I don't seem to be able to get a properly synced local tree. 

Or I just close this pull request and start over again (I need to update the documentation anyway, because the IBMiscanner was also updated and now includes an export option for DES format, and also the as400-ssha1 plugin needs to be updated because that one still uses $ signs as delimiter, so that needs to be changed to '*'s as well). I can include all of these changes in a new pull request.

**Comment by kholia** [comment]
@rschoem @magnumripper I have squashed and "merged" this pull request manually.

**Pull request closed without merging**
