### PR TITLE
[skip ci] Update README*

### PR DESCRIPTION
**Pull request by solardiz**
Update README.md to more accurately describe jumbo and have fewer differences from core's doc/README. Drop README-jumbo. Replace doc/README with symlink to ../README.md.

### CODE REVIEW

**Comment by solardiz** [comment]
Somehow this is waiting for CI and thus can't be merged for a day now.

**Comment by claudioandre-br** [comment]
Only magnum can merge [skip ci] stuff.

>

**Comment by solardiz** [comment]
> Only magnum can merge [skip ci] stuff.

Oh. That's a reason for me to avoid using "[skip ci]", then. And perhaps magnum wasn't aware of this, or else he would have merged these changes instead of merely approving them for no one to merge.

**Comment by magnumripper** [comment]
> Only magnum can merge [skip ci] stuff.

I didn't know that 😆

**Pull request merged**
