### PR TITLE
Add support for cracking Apple Notes databases

### PR DESCRIPTION
**Pull request by kholia**
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2999.

### CODE REVIEW

**Comment by kholia** [comment]
I am working on OpenCL support now. I would like to commit both formats in this PR.

**Comment by kholia** [comment]
OpenCL stuff is ready now, and is included in the latest PR commit.

**Comment by kholia** [comment]
It just occurred to me that it should be possible to crack password protected Apple Notes databases with the existing `FVDE` format. However, writing a new format (which this PR does) seems be the cleaner way of supporting such hashes.

**Comment by magnumripper** [comment]
> It just occurred to me that it should be possible to crack password protected Apple Notes databases with the existing FVDE format. However, writing a new format (which this PR does) seems be the cleaner way of supporting such hashes.

Why? Is the original "hash" format very different?

**Comment by kholia** [comment]
The original hash format is indeed different. It has a different FORMAT_TAG, different ordering and number of fields. This being said, it should possible to convert the newer hash format (`$ASN$`) into older FVDE hash format using a `split` method. However, the pot file will then contain cracked Apple Notes hashes in the converted FVDE hash format and not in the original `$ASN$` format, right? This can potentially confuse users.

The newer hash format (`$ASN$...`) is used by hashcat, so it would be nice to support it. If we don't need / want to support it, then this whole problem simply goes away.

**Comment by kholia** [comment]
I will merge this for now. We can decide later if we want to combine the two formats (`FVDE` and `notes`).

**Pull request merged**
