### PR TITLE
Don't report virtual c/s if virtual time didn't advance

### LINKED ISSUE #3925: Misreported "virtual" speeds on Linux/sparc64
In testing on Linux/sparc64, I notice that `--test` reports for "c/s virtual" are 500 times higher than expected (e.g., 500 times higher than "c/s real" when running one thread). I don't yet know what causes this - could be our bug, could be a Linux kernel bug, or maybe something else.

### PR DESCRIPTION
**Pull request by solardiz**
Fixes #3925

### CODE REVIEW

**Comment by magnumripper** [comment]
Aha it was Linux/Sparc. Strange.

**Comment by solardiz** [comment]
> Is this something you could want in core as well?

Yes. I also wonder whether we should drop conditional compilation and simply set end=start to trigger this same check on systems where we have no API to read virtual times. But not now.

**Comment by solardiz** [comment]
> it was Linux/Sparc. Strange.

Definitely strange. I think I saw working virtual times on that platform before. Maybe some temporary kernel or glibc or distro bug.

**Comment by solardiz** [comment]
All tests except for more-tests passed. I think more-tests is pending forever, right? So I'll merge.

**Comment by claudioandre-br** [comment]
I run more-tests after the merge (not for all commits). The reviewer can merge before, if he wants.

**Comment by solardiz** [comment]
> > it was Linux/Sparc. Strange.
> 
> Definitely strange. I think I saw working virtual times on that platform before. Maybe some temporary kernel or glibc or distro bug.

That system is indeed quite broken - also "top" doesn't show processes consuming CPU time, and "ps" shows 0:00 for almost all processes where I'd expect non-zero.

**Pull request merged**
