### PR TITLE
Improve HACKING notes based on feedback from JimF

### PR DESCRIPTION
**Pull request by kholia**
This fleshes out the VM setup notes.

### CODE REVIEW

**Comment by jfoug** [comment]
Looks very good.  Have you gotten the 32 bit vs 64 bit working properly?  I have it working, but it is not right.  Once I know we have good instructions, I will create a new VM, make sure it is setup properly, then scrap the original i have.  But I am not making any move to do that, until I get all of the formats working on BE SIMD builds.

**Comment by kholia** [comment]
Thanks Jim. I have not tried playing with the build hacks you mentioned earlier. I am (was) still building and testing with the `Makefile.legacy` approach.

**Comment by jfoug** [comment]
Once I get the formats ported, I will move on to the configure logic.  I have a good 'plan' on what needs to be done, I just have to put it into m4 syntax (which sux ;), and make sure it is at the proper location in the script.  But the changes should not be too hard to do, now that I have an environment that actually 'does' build the base ../run/john   Currently, on the 64 bit side (where most of the hacking of make environment was needed), it dies as soon as compiling gets to the ancillary files. Not a big deal, I can work through that also.  But all in time.  We will get there.

**Comment by kholia** [comment]
I have updated the `apt-get` command to install `gcc-multilib` package. After installing this package, I am able to use the GCC's `-m64` flag.

@jfoug Can you please post the steps your took to build 64-bit OpenSSL? Looking at `~/.bash_history` can help. I would like to add these steps to the documentation.

**Comment by jfoug** [comment]
My build was NOT correctly done.  I would like to wait until I get it right before documenting.  I simply downloaded ossl, then did ./Configure PPC6   then make, then make install.  Note, I ^c during the document copy crap.  There is a make tag to install only the binaries. I should have done that. HOWEVER, what was installed was installed right into /usr/lib, etc (i.e. default FULL system stuff). The 32 bit stuff was not, thus it did not work well multilib.  (and includes were a bit messed up).  The new version was too new.  Many failures in our listoptions.c (which SHOULD be removed, IMHO)

But let me get things figured out first, please.  I also did a apt-cache search powerpc64 and installed some of that (libs and headers).  But oSSL was not part of that, :(

**Comment by kholia** [comment]
This should be safe to merge. Merging!

**Pull request merged**
