### PR TITLE
Utility to help with cracking DiskCryptor

### PR DESCRIPTION
**Pull request by ivan-freed**

### CODE REVIEW

**Comment by ivan-freed** [comment]
Yes, this format doesn't exist in JtR Jumbo yet. I will be posting the format in follow-up PRs.

**Comment by KotekCzek** [comment]
Is possible to add it to Hashcat?

**Comment by magnumripper** [comment]
You'd probably be better off asking the hashcat staff

**Comment by KotekCzek** [comment]
Hmm, I made a backup with family photos and encrypted ISO DiskCryptor Aes-Twofish-Serpent in a cascade. Is possible to try cracking with bruteforce some part of my password?

**Comment by magnumripper** [comment]
This is not a support forum, it's a bug tracker.

**Pull request merged**
