### PR TITLE
Add support for MinGW builds, with <3 from JimF!

### PR DESCRIPTION
**Pull request by kholia**
@jfoug @magnumripper @frank-dittrich this is what the MinGW build stuff will look like.

### CODE REVIEW

**Comment by jfoug** [comment]
How much time does it take travis to do this now, since oSSL has to be built?

**Comment by kholia** [comment]
@jfoug less than 12 minutes (which is pretty reasonable).

**Comment by jfoug** [comment]
Yes, 12 min is certainly reasonable.  I expected the oSSL build alone to take more time than that. I have a decent machine (core7) and am building from a VM (but I give the VM only 2 cores).  The oSSL takes a bit (well, it might be 8-10 minutes).  I was expecting more time used, but possibly it is that fast.

One big thing is to do a 

make install_sw      and NOT   make install.      oSSL has a TON of documentation that gets installed, and for this purpose, that is totally not required.

**Comment by kholia** [comment]
@jfoug cool! I will now try to get the ".dll" stuff going (along with task of publishing the builds automatically, somehow).

**Comment by kholia** [comment]
@magnumripper this should be OK to merge now (.travis.yml's "deploy" section will require small tweaks to make official releases)

**Pull request merged**
