### PR TITLE
Fix salt alignment in a bunch of formats, see #3932

### PR DESCRIPTION
**Pull request by magnumripper**

### CODE REVIEW

**Comment by solardiz** [comment]
I'm running a `--test-full=1` of this on sparc64 now.

**Comment by solardiz** [comment]
Have you reviewed the fields in each of these formats' `struct custom_salt`? We need to make sure there are no fields of types like `long` the required alignment of which varies between architectures.

**Comment by solardiz** [comment]
> I'm running a `--test-full=1` of this on sparc64 now.

```
Testing: dynamic_2014 [md5($s.md5($p).$s) (PW > 55 or salt > 11 bytes) 32/64 x2]... PASS
Testing: dummy [N/A]... PASS
Testing: crypt, generic crypt(3) [?/64]... (13xOMP) PASS
All 402 formats passed self-tests!
0.00user 0.00system 6:27.03elapsed 0%CPU (0avgtext+0avgdata 515328maxresident)k
```

**Comment by magnumripper** [comment]
> Have you reviewed the fields in each of these formats' `struct custom_salt`? We need to make sure there are no fields of types like `long` the required alignment of which varies between architectures.

Yes. I also use to replace all uses av `long` with `uint64_t` or `int` as needed whenever I see them.

**Pull request merged**
