### PR TITLE
Formats inspired by InsidePro

### PR DESCRIPTION
**Pull request by kholia**
- [ ] BlackBerry ES v10
- [ ] Blake-224
- [x] Blake-256
- [ ] Blake-384
- [x] Blake-512
- [ ] Blowfish(Eggdrop)
- [ ] Blowfish(OpenBSD)
- [ ] Blowfish($pass.$username)
- [ ] Cisco IOS
- [ ] CRC-64
- [ ] Custom(10)
- [ ] Custom(11)
- [ ] Custom(12)
- [ ] Custom(13)
- [ ] Custom(14)
- [ ] Custom(15)
- [ ] Custom(16)
- [ ] Custom(17)
- [ ] Custom(18)
- [ ] Custom(19)
- [ ] Custom(1)
- [ ] Custom(20)
- [ ] Custom(21)
- [ ] Custom(22)
- [ ] Custom(23)
- [ ] Custom(24)
- [ ] Custom(25)
- [ ] Custom(26)
- [ ] Custom(27)
- [ ] Custom(2)
- [ ] Custom(3)
- [ ] Custom(4)
- [ ] Custom(5)
- [ ] Custom(6)
- [ ] Custom(7)
- [ ] Custom(8)
- [ ] Custom(9)
- [ ] DCC2
- [ ] DES(Oracle)
- [ ] DES(Unix)
- [ ] Domain Cached Credentials
- [ ] EPiServer
- [ ] EPiServer v6.x (.NET v3.5)
- [ ] EPiServer v6.x (.NET v4.x)
- [ ] GOST R 34.11-2012 (256)
- [ ] GOST R 34.11-2012 (512)
- [ ] GOST R 34.11-94
- [ ] HAS-160
- [ ] Haval-128(HMAC1)
- [ ] Haval-128(HMAC2)
- [ ] Haval-128
- [ ] Haval-160(HMAC1)
- [ ] Haval-160(HMAC2)
- [ ] Haval-160
- [ ] Haval-192(HMAC1)
- [ ] Haval-192(HMAC2)
- [ ] Haval-192
- [ ] Haval-224(HMAC1)
- [ ] Haval-224(HMAC2)
- [ ] Haval-224
- [ ] Haval-256(HMAC1)
- [ ] Haval-256(HMAC2)
- [x] Haval-256
- [ ] iSSHA-1
- [ ] iSSHA-256
- [ ] iSSHA-384
- [ ] iSSHA-512
- [ ] Keccak-224
- [ ] Keccak-256
- [ ] Keccak-384
- [ ] Keccak-512
- [ ] LM
- [ ] Lotus v5
- [ ] Lotus v6
- [ ] MD2(HMAC1)
- [ ] MD2(HMAC2)
- [ ] MD2
- [ ] MD4(HMAC1)
- [ ] MD4(HMAC2)
- [ ] md4(md4($pass).$salt)
- [ ] md4($pass.$salt)
- [ ] MD4(Round 1)
- [x] md4($salt.$pass)
- [x] MD4
- [ ] md5(0x01.$pass.$salt)
- [ ] MD5(AIX)
- [ ] MD5(APR)
- [ ] md5(base64_encode(base64_encode($pass)))
- [ ] md5(base64_encode(md5($pass)))
- [ ] md5(base64_encode($pass))
- [ ] MD5(Cisco PIX)
- [ ] MD5(DES(Unix))
- [ ] MD5(HMAC1)
- [ ] MD5(HMAC2)
- [ ] md5(md5(base64_encode($pass)))
- [ ] md5(md5(md5(md5(md5(md5(md5(md5(md5(md5($pass))))))))))
- [ ] md5(md5(md5(md5(md5(md5(md5(md5(md5($pass)))))))))
- [ ] md5(md5(md5(md5(md5(md5(md5(md5($pass))))))))
- [ ] md5(md5(md5(md5(md5(md5(md5($pass)))))))
- [ ] md5(md5(md5(md5(md5(md5($pass))))))
- [ ] md5(md5(md5(md5(md5($pass)))))
- [ ] md5(md5(md5(md5($pass))))
- [ ] md5(md5(md5($pass).md5($pass).md5($pass).md5($pass)))
- [ ] md5(md5(md5($pass)).$salt)
- [ ] md5(md5(md5($pass)))
- [ ] md5(md5($pass).md5($pass).md5($pass).md5($pass).$salt)
- [ ] md5(md5($pass).md5($pass).md5($pass).md5($pass))
- [ ] md5(md5($pass).md5($pass).md5($pass))
- [ ] md5(md5($pass).md5($pass))
- [ ] md5(md5($pass).md5($salt))
- [ ] md5(md5($pass).$pass.sha1($pass))
- [ ] md5(md5($pass.$salt).md5($pass).$salt)
- [ ] md5(md5($pass.$salt).sha1(md5($pass.$salt).$pass))
- [ ] md5(md5($pass).$salt)
- [ ] md5(md5($pass))
- [ ] md5(md5($pass.$username).$salt)
- [ ] md5(md5($salt).md5($pass))
- [ ] md5(md5($salt).$pass)
- [ ] md5(md5(sha1(sha1(md5($pass)))))
- [ ] md5(md5($username.$pass).$salt)
- [ ] MD5(Palshop)
- [ ] md5($pass.md5($pass))
- [ ] md5($pass.md5($salt))
- [ ] md5($pass.$salt.$pass)
- [ ] md5($pass.'--'.$salt)
- [ ] md5($pass.$salt)
- [ ] md5($pass.$username)
- [ ] MD5(phpBB3)
- [ ] MD5(Round 1)
- [ ] md5($salt.0x2D.md5($pass))
- [ ] md5($salt.0x7C.$pass)
- [ ] md5($salt.hextobin(md5($pass)).$username)
- [ ] md5($salt.md5(md5($pass).$salt))
- [ ] md5($salt.md5($pass.$salt))
- [ ] md5($salt.md5($pass).$salt)
- [ ] md5($salt.md5($pass))
- [ ] md5($salt.md5($salt.$pass))
- [ ] md5($salt.$pass.$salt)
- [ ] md5($salt.$pass)
- [ ] md5($salt.$pass.$username)
- [ ] md5($salt.sha1($pass))
- [ ] md5($salt.sha1($salt.$pass))
- [ ] md5(sha1(base64_encode($pass)))
- [ ] md5(sha1(md5($pass)).sha1($pass))
- [ ] md5(sha1(md5($pass)))
- [ ] md5(sha1(md5($salt.sha1($pass))))
- [ ] md5(sha1(md5(sha1($pass))))
- [ ] md5(sha1($pass).md5($pass).sha1($pass))
- [ ] md5(sha1($pass.md5($pass)))
- [ ] md5(sha1($pass.$salt))
- [ ] md5(sha1($pass).$salt)
- [ ] md5(sha1($pass))
- [ ] md5(sha1($pass.$username))
- [ ] md5(sha1($salt.$pass))
- [ ] md5(sha256($pass))
- [ ] MD5(Skype)
- [ ] MD5(Social Engine)
- [ ] md5(strrev(md5($pass)))
- [ ] md5(strrev($pass))
- [ ] md5(strtoupper(md5($pass)))
- [ ] md5(strtoupper(md5(strtoupper(md5($pass)))))
- [ ] md5(strtoupper(md5(strtoupper(md5(strtoupper(md5($pass)))))))
- [ ] MD5(Sun)
- [ ] MD5
- [ ] MD5(Unix)
- [ ] md5($username.0x00.$pass)
- [ ] md5($username.0x0A.$pass.0x0A.$salt)
- [ ] md5($username.0x0A.$pass)
- [ ] md5($username.0x23.$pass)
- [ ] md5($username.md5($pass).$salt)
- [ ] md5($username.$pass.$salt)
- [ ] md5($username.$pass)
- [ ] md5($username.strtoupper(md5($pass)).$salt)
- [ ] MD5(Wiki)
- [ ] MD5(Wordpress)
- [ ] MD5(ZipMonster)
- [ ] MongoDB(1)
- [ ] MongoDB(2)
- [ ] MSSQL(2000)
- [ ] MSSQL(2005)
- [ ] MSSQL(2012)
- [ ] MySQL5(md5($pass))
- [ ] MySQL5
- [ ] MySQL(Net)
- [ ] MySQL
- [ ] NSEC3
- [ ] NTLM
- [ ] Panama
- [ ] PBKDF2 Cisco
- [ ] PBKDF2 GRUB
- [ ] PBKDF2 JIRA
- [ ] PBKDF2 MD5(2)
- [ ] PBKDF2 MD5(3)
- [ ] PBKDF2 MD5
- [ ] PBKDF2 SHA-1(2)
- [ ] PBKDF2 SHA-1(3)
- [ ] PBKDF2 SHA-1
- [ ] PBKDF2 SHA-256(2)
- [ ] PBKDF2 SHA-256(3)
- [ ] PBKDF2 SHA-256
- [ ] PBKDF2 SHA-512(2)
- [ ] PBKDF2 SHA-512(3)
- [ ] PBKDF2 SHA-512
- [ ] PHPS
- [ ] PostgreSQL
- [ ] RAdmin v2.x
- [ ] RipeMD-128(HMAC1)
- [ ] RipeMD-128(HMAC2)
- [ ] ripemd128($pass.$salt)
- [ ] ripemd128($salt.$pass)
- [ ] RipeMD-128
- [ ] RipeMD-160(HMAC1)
- [ ] RipeMD-160(HMAC2)
- [ ] ripemd160($pass.$salt)
- [ ] ripemd160($salt.$pass)
- [ ] RipeMD-160
- [ ] RipeMD-256(HMAC1)
- [ ] RipeMD-256(HMAC2)
- [ ] ripemd256($pass.$salt)
- [ ] ripemd256($salt.$pass)
- [ ] RipeMD-256
- [ ] RipeMD-320(HMAC1)
- [ ] RipeMD-320(HMAC2)
- [ ] ripemd320($pass.$salt)
- [ ] ripemd320($salt.$pass)
- [x] RipeMD-320
- [x] SAPB
- [x] SAPG
- [ ] SHA-1(AIX)
- [ ] SHA-1(Django)
- [ ] SHA-1(FortiOS)
- [ ] SHA-1(HMAC1)
- [ ] SHA-1(HMAC2)
- [ ] SHA-1(Linkedin)
- [ ] SHA-1(MacOS)
- [ ] sha1(md5($pass).$pass)
- [ ] sha1(md5($pass.$salt))
- [ ] sha1(md5($pass).$salt)
- [ ] sha1(md5($pass))
- [ ] sha1(md5($pass).$username.$salt)
- [ ] sha1(md5($pass.$username))
- [ ] sha1(md5($salt).$pass.sha1($salt))
- [ ] sha1(md5($salt).$pass.sha1($salt).$username)
- [ ] sha1(md5(sha1(md5($pass))))
- [ ] sha1(md5(sha1($pass)))
- [ ] SHA-1(Oracle)
- [ ] sha1($pass.$salt)
- [ ] sha1($pass.$username.$salt)
- [ ] sha1($salt.md5($pass).$salt)
- [ ] sha1($salt.md5($pass))
- [ ] sha1($salt.$pass.$salt)
- [ ] sha1('--'.$salt.'--'.$pass.'--')
- [ ] sha1($salt.$pass.'--')
- [ ] sha1($salt.$pass)
- [ ] sha1('--'.$salt.'--'.$pass.'--'.$username)
- [ ] sha1($salt.$pass.$username)
- [ ] sha1($salt.sha1($pass.$salt))
- [ ] sha1($salt.sha1($pass))
- [ ] sha1($salt.sha1($salt.sha1($pass)))
- [ ] sha1($salt.$username.$pass.$salt)
- [ ] sha1(sha1($pass).$salt)
- [ ] sha1(sha1($pass).substr($pass,0,3))
- [ ] sha1(sha1($pass))
- [ ] sha1(sha1($salt.$pass))
- [ ] sha1(sha1(sha1($pass)))
- [ ] sha1(sha256($pass))
- [ ] sha1(strtolower($username).$pass)
- [ ] sha1(strtoupper($username).0x3A.$pass)
- [ ] SHA-1
- [ ] SHA-1(Unix)
- [ ] sha1($username.0x3A.$pass)
- [ ] sha1($username.$pass.$salt)
- [ ] sha1($username.$pass.$salt.$username)
- [ ] sha1($username.$pass)
- [ ] sha1($username.$salt.$pass)
- [ ] SHA-224(HMAC1)
- [ ] SHA-224(HMAC2)
- [ ] sha224($pass.$salt)
- [ ] sha224($salt.$pass)
- [ ] SHA-224
- [ ] SHA-256(AIX)
- [ ] SHA-256(AuthMe)
- [ ] sha256(base64_encode(md5($pass)))
- [ ] sha256(base64_encode(sha1($pass)))
- [ ] SHA-256(Django)
- [ ] SHA-256(DragonFlyBSD-32)
- [ ] SHA-256(DragonFlyBSD-64)
- [ ] SHA-256(HMAC1)
- [ ] SHA-256(HMAC2)
- [ ] sha256(md5($pass).$pass)
- [ ] sha256(md5($pass.$salt))
- [ ] sha256(md5($pass).$salt)
- [ ] sha256(md5($pass))
- [ ] sha256(md5($salt.$pass))
- [ ] sha256($pass.0x5F.strtolower($username))
- [ ] sha256($pass.$salt)
- [ ] SHA-256(PasswordSafe)
- [ ] SHA-256(RuneScape)
- [ ] sha256($salt.$pass)
- [ ] sha256($salt.strtoupper(sha1($pass)))
- [ ] sha256(sha1($pass).$salt)
- [ ] sha256(sha1($pass))
- [ ] sha256(sha256($pass).$salt)
- [ ] sha256(sha256($salt.$pass).$pass)
- [ ] SHA-256
- [ ] SHA-256(Unix)
- [ ] SHA-384(Django)
- [ ] SHA-384(HMAC1)
- [ ] SHA-384(HMAC2)
- [ ] sha384($pass.$salt)
- [ ] sha384($salt.$pass)
- [ ] SHA-384
- [ ] SHA-512(AIX)
- [ ] SHA-512(Django)
- [ ] SHA-512(DragonFlyBSD-32)
- [ ] SHA-512(DragonFlyBSD-64)
- [ ] SHA-512(Drupal)
- [ ] SHA-512(HMAC1)
- [ ] SHA-512(HMAC2)
- [ ] SHA-512(MacOS)
- [ ] sha512(md5($pass).$salt)
- [ ] sha512($pass.$salt)
- [ ] sha512($salt.md5($pass))
- [ ] sha512($salt.$pass)
- [ ] SHA-512(Symfony2)
- [ ] SHA-512
- [ ] SHA-512(Unix)
- [ ] Skein-1024(384)
- [ ] Skein-1024(512)
- [ ] Skein-1024
- [ ] Skein-256(128)
- [ ] Skein-256(160)
- [ ] Skein-256(224)
- [x] Skein-256
- [ ] Skein-512(128)
- [ ] Skein-512(160)
- [ ] Skein-512(224)
- [ ] Skein-512(256)
- [ ] Skein-512(384)
- [x] Skein-512
- [ ] Snefru-128(HMAC1)
- [ ] Snefru-128(HMAC2)
- [ ] Snefru-128
- [ ] Snefru-256(HMAC1)
- [ ] Snefru-256(HMAC2)
- [x] Snefru-256
- [ ] SSHA-1
- [ ] SSHA-256
- [ ] SSHA-384
- [ ] SSHA-512
- [ ] strrev(md5($pass))
- [ ] strrev(md5(strrev(md5($pass))))
- [ ] substr(md5(md5($pass)),0,16)
- [ ] substr(md5($pass),0,10)
- [ ] substr(md5($pass),0,16)
- [ ] substr(md5($pass),0,30)
- [ ] substr(md5($pass),0,8).substr(md5($pass),27,5)
- [ ] substr(md5($pass),0,8)
- [ ] substr(md5($pass),12,20)
- [ ] substr(md5($pass),16,16)
- [ ] substr(md5($pass),8,16)
- [ ] substr(sha1($pass),0,16)
- [ ] substr(sha1($pass),0,30)
- [ ] substr(sha1($pass),0,32)
- [ ] substr(sha1($pass),0,38)
- [ ] substr(sha1($pass),0,8)
- [ ] substr(sha256($pass),0,16)
- [ ] substr(sha256($pass),0,32)
- [ ] substr(sha256($pass),0,40)
- [x] Sybase ASE
- [ ] Tiger-128(HMAC1)
- [ ] Tiger-128(HMAC2)
- [ ] Tiger-128
- [ ] Tiger-160(HMAC1)
- [ ] Tiger-160(HMAC2)
- [ ] Tiger-160
- [ ] Tiger-192(HMAC1)
- [ ] Tiger-192(HMAC2)
- [ ] Tiger-192
- [x] Ventrilo
- [x] WBB4
- [ ] Whirlpool(HMAC1)
- [ ] Whirlpool(HMAC2)
- [ ] whirlpool($pass.$salt)
- [ ] whirlpool($salt.$pass)
- [ ] Whirlpool

This is still WIP, do not merge!

@magnumripper @jfoug @frank-dittrich how useful do you think these formats will be?

I am trying to port Hash Manager v1.2 (http://insidepro.com/) formats to JtR.

### CODE REVIEW

**Comment by jfoug** [comment]
Most of these look like dyna formats. Even one I already have done shoulda been dyna. If there's a real format strong, then it's simple to do with a thin dyna format.

**Comment by magnumripper** [comment]
Yeah all of these that can be thin, really should be thin. You'll get SIMD support automagically, for a starter.

**Comment by kholia** [comment]
@jfoug @magnumripper cool, I will try to do that :)

**Comment by jfoug** [comment]
Ok, what are your 'plans' on this. I started at the first file  (BlackBerry ES v 10.txt).  It is hashes that we already handle, but they are not in a usable format. There is the raw hash, a colon and the salt.

I added the $bbes10$ and changed the ':' to '$' and was able to find all hashes easily.

I was going to look at adding some 'self contained' thin dyna formats, if there are ones that 'match' the criteria (i.e. have identifiable hashes and are 'unique' enough that a dyna format would be usable by no other hash types).

**Comment by kholia** [comment]
Hi!

Please take a look at `palshop_fmt_plug.c` file. Is it implementable using the dynamic format?

I have added a huge checklist to my initial post (look at the top of this page), please feel free to tick things off :)

**Comment by jfoug** [comment]
palshop is not able to be done in dynamic.  However, social_engine 'could' be done, with a thin format. The thin format would split the salt into 2 salts (first 4 bytes, last 4 bytes).  Then it would simply be:

md5($s.$p.$s2) type format.

**Comment by magnumripper** [comment]
A good number of these can now be cracked without adding any format nor even any lines in a config file.
```
$ ../run/john -test '-form:dynamic=sha1(md5($p.$u))'
Benchmarking: dynamic=sha1(md5($p.$u)) [128/128 AVX 4x1]... DONE
Many salts:	8117K c/s real, 8117K c/s virtual
Only one salt:	7356K c/s real, 7356K c/s virtual
```

Maybe just drop this PR? The idea of 400 new thin formats doesn't sound very appealing :scream:

**Comment by magnumripper** [comment]
>  It is hashes that we already handle, but they are not in a usable format. There is the raw hash, a colon and the salt.

1. I think in general we should allow loading untagged hashes (actual hashes, not the "non-hash" types). Originally the tags were meant for pot entries, not input entries.
2. We could opt to also try to load salts from another input field using prepare() but I'm not sure I want to go there...

**Comment by kholia** [comment]
@magnumripper cool, I will open separate pull requests for formats which can't be done using dynamic.

**Pull request closed without merging**
