### PR TITLE
Blind fix of #3924. As far as I can see, this should do it.

### PR DESCRIPTION
**Pull request by magnumripper**

### CODE REVIEW

**Comment by solardiz** [comment]
Please _don't_ merge this yet. I actually thought of this kind of fix the moment I noticed the problem, and fixing it properly didn't look as simple as this.

**Comment by solardiz** [comment]
Let's leave the original issue unfixed for the release this time, not to introduce worse issues.

**Comment by magnumripper** [comment]
No problem, we'll wait. But I couldn't spot any foot gun here, did you?

**Comment by magnumripper** [comment]
...apart from the missing semi-colon I just added 🙄

**Comment by solardiz** [comment]
> I couldn't spot any foot gun here, did you?

Maybe not. Need to also check the uses from status.c. Anyway, testing this requires manually running a mingw build and sanity-checking the speeds perhaps against what's seen just prior to these changes, for both `--test` and actual cracking. It's not something CI would test for us.

**Pull request merged**
