### PR TITLE
Add support for iTunes Backup

### PR DESCRIPTION
**Pull request by kholia**
I could not figure out a way to use `pbkdf2_sha1_sse` and `pbkdf2_sha256_sse` together. Hence the presence of various hacks (marked with `hack` keyword) in the code.

### CODE REVIEW

**Comment by jfoug** [comment]
What problems were you having?    One thing I notice is you lack SIMD code for the sha256 block.  Could that be the problem?  It is exactly the same as the SHA1 bpkdf2 code, except for size of buffers, and constants that get the right counts.    There 'should' be no reason to include both CTX and simd code at the same time UNLESS you were always using the CTX code for some reason (there are a couple formats which DO require this).  One reason for that define, is if you do not put in the SIMD code.  The build knows you are building SIMD and simply does not include the CTX code, so if you don't 'have' any SIMD used, you have to use that flag (and then you get warnings about unused functions when building for SIMD, but the code works fine.

I am buried under real work right now, so do not have much time, but when I can, I will take a look into this, if you have not found the problem by then.

**Comment by kholia** [comment]
[sample-itunes-backup-manifests.zip](https://github.com/magnumripper/JohnTheRipper/files/752115/sample-itunes-backup-manifests.zip), borrowed from hashcat forum for testing.

**Comment by kholia** [comment]
Earlier, I thought that `SSE_GROUP_SZ_SHA1` had a different value than `SSE_GROUP_SZ_SHA256`, and I could only set `MAX_KEYS_PER_CRYPT` to either one of them. Hence, I didn't implement SIMD code which called both `pbkdf2_sha256_sse` and `pbkdf2_sha1_sse`.

I will try to implement SIMD calls now.

**Comment by kholia** [comment]
@magnumripper  @jfoug do the changes in commit https://github.com/magnumripper/JohnTheRipper/pull/2410/commits/6ad49349ca642f8bbc10d1724ede0cd57143cde1 look good?

**Comment by magnumripper** [comment]
> Earlier, I thought that SSE_GROUP_SZ_SHA1 had a different value than SSE_GROUP_SZ_SHA256, and I could only set MAX_KEYS_PER_CRYPT to either one of them.

That is potentially true. Some builds interleave SHA-1.

**Comment by magnumripper** [comment]
To overcome that, I think the easiest is to set MAX_KEYS_PER_CRYPT to `(SSE_GROUP_SZ_SHA1 * SSE_GROUP_SZ_SHA256)` and adjust loops accordingly.

**Comment by kholia** [comment]
@magnumripper I tried the following hack,

```
diff --git a/src/itunes_fmt_plug.c b/src/itunes_fmt_plug.c
index 4055302..8ed440a 100644
--- a/src/itunes_fmt_plug.c
+++ b/src/itunes_fmt_plug.c
@@ -54,8 +54,8 @@ john_register_one(&fmt_itunes);
 #define BINARY_ALIGN            1
 #define SALT_ALIGN              sizeof(int)
 #ifdef SIMD_COEF_32
-#define MIN_KEYS_PER_CRYPT      SSE_GROUP_SZ_SHA1  // assumed to be same as SSE_GROUP_SZ_SHA256!
-#define MAX_KEYS_PER_CRYPT      SSE_GROUP_SZ_SHA1
+#define MIN_KEYS_PER_CRYPT      (SSE_GROUP_SZ_SHA1 * SSE_GROUP_SZ_SHA256)
+#define MAX_KEYS_PER_CRYPT      (SSE_GROUP_SZ_SHA1 * SSE_GROUP_SZ_SHA256)
 #else
 #define MIN_KEYS_PER_CRYPT      1
 #define MAX_KEYS_PER_CRYPT      1
@@ -136,12 +136,14 @@ static int crypt_all(int *pcount, struct db_salt *salt)
 #ifdef SIMD_COEF_32
 			int lens[MAX_KEYS_PER_CRYPT];
 			unsigned char *pin[MAX_KEYS_PER_CRYPT], *pout[MAX_KEYS_PER_CRYPT];
+			int loops = MAX_KEYS_PER_CRYPT / SSE_GROUP_SZ_SHA1;
 			for (i = 0; i < MAX_KEYS_PER_CRYPT; ++i) {
 				lens[i] = strlen(saved_key[index+i]);
 				pin[i] = (unsigned char*)saved_key[index+i];
 				pout[i] = master[i];
 			}
-			pbkdf2_sha1_sse((const unsigned char**)pin, lens, cur_salt->salt, SALTLEN, cur_salt->iterations, pout, 32, 0);
+			for (i = 0; i < loops; i++)
+				pbkdf2_sha1_sse((const unsigned char**)(pin + i * SSE_GROUP_SZ_SHA1), &lens[i * SSE_GROUP_SZ_SHA1], cur_salt->salt, SALTLEN, cur_salt->iterations, pout + (i * SSE_GROUP_SZ_SHA1), 32, 0);
 #else
 			for (i = 0; i < MAX_KEYS_PER_CRYPT; ++i)
 				pbkdf2_sha1((unsigned char *)saved_key[index+i], strlen(saved_key[index+i]), cur_salt->salt, SALTLEN, cur_salt->iterations, master[i], 32, 0);
@@ -153,19 +155,22 @@ static int crypt_all(int *pcount, struct db_salt *salt)
 #if defined(SIMD_COEF_64) && defined(SIMD_COEF_32)
 			int lens[MAX_KEYS_PER_CRYPT];
 			unsigned char *pin[MAX_KEYS_PER_CRYPT], *pout[MAX_KEYS_PER_CRYPT];
+			int loops = MAX_KEYS_PER_CRYPT / SSE_GROUP_SZ_SHA256;
 			for (i = 0; i < MAX_KEYS_PER_CRYPT; ++i) {
 				lens[i] = strlen(saved_key[index+i]);
 				pin[i] = (unsigned char*)saved_key[index+i];
 				pout[i] = master[i];
 			}
-			pbkdf2_sha256_sse((const unsigned char**)pin, lens, cur_salt->dpsl, SALTLEN, cur_salt->dpic, pout, 32, 0);
+			for (i = 0; i < loops; i++)
+				pbkdf2_sha256_sse((const unsigned char**)(pin + i * SSE_GROUP_SZ_SHA256), &lens[i * SSE_GROUP_SZ_SHA256], cur_salt->dpsl, SALTLEN, cur_salt->dpic, pout + (i * SSE_GROUP_SZ_SHA256), 32, 0);
 			for (i = 0; i < MAX_KEYS_PER_CRYPT; ++i) {
 				lens[i] = 32;
 				pin[i] = (unsigned char*)master[i];
 				pout[i] = master[i];
 			}
-			pbkdf2_sha1_sse((const unsigned char**)pin, lens, cur_salt->salt, SALTLEN, cur_salt->iterations, pout, 32, 0);
-
+			loops = MAX_KEYS_PER_CRYPT / SSE_GROUP_SZ_SHA1;
+			for (i = 0; i < loops; i++)
+				pbkdf2_sha1_sse((const unsigned char**)(pin + i * SSE_GROUP_SZ_SHA1), &lens[i * SSE_GROUP_SZ_SHA1], cur_salt->salt, SALTLEN, cur_salt->iterations, pout + (i * SSE_GROUP_SZ_SHA1), 32, 0);
 #else
 			for (i = 0; i < MAX_KEYS_PER_CRYPT; ++i) {
 				pbkdf2_sha256((unsigned char *)saved_key[index+i], strlen(saved_key[index+i]), cur_salt->dpsl, SALTLEN, cur_salt->dpic, master[i], 32, 0);
```

and built JtR using,

```
$ JOHN_CFLAGS=-m32 JOHN_ASFLAGS=-m32 JOHN_LDFLAGS=-m32 make -f Makefile.legacy -j4 linux-x86-sse2
```

In such a build, `MAX_KEYS_PER_CRYPT` is 32, `SSE_GROUP_SZ_SHA256` is 4 and `SSE_GROUP_SZ_SHA1` is 8.

It seems to be working. Do it seem OK to you?

**Comment by kholia** [comment]
The green "Merge pull request" button now has multiple drop-down options. For this PR, "Squash and merge" seems appropriate.

**Comment by kholia** [comment]
The more I thought about this, the safer it seemed to merge.

**Comment by magnumripper** [comment]
That's great with a squash option right in Github!

Yeah the code looks just like what I had in mind.

**Pull request merged**
