### PR TITLE
rebased resume patch

### PR DESCRIPTION
**Pull request by jfoug**
Rebased.  I did this by hand, so will also check to make sure everything was done the same way. In some areas code had changed, so I made assumptions.

NOTE I have not tested this rebase at all yet.

### CODE REVIEW

**Comment by magnumripper** [comment]
I started to test this and it introduces bugs. Example:
```
# create test file
$ ../run/john -stdout -inc:digits -max-len=3 | ../run/pass_gen.pl --count=1111 md5crypt > md5.in

# start a job
$ rm -f test.pot && ../run/john -pot:test.pot md5.in -form:md5crypt -inc:digits -min-len=0 -max-len=3 -mask:?w?d -max-run=2

#resume until done
$ while true ; do ../run/john -res && break ; sleep 1 ; done
```
This ends up with missed candidates.

**Comment by claudioandre** [comment]
Just a reminder:
- It is easy to put more tests on CI. Ok, maybe it will be hard to design such tests. 
- Just for fun, I put TS there (ah, probably, it will take too long)

https://travis-ci.org/claudioandre/JohnTheRipper/jobs/169059693

**Comment by claudioandre** [comment]
At the link below, a pure ```./jtrts.pl --restore``` test: 
- https://travis-ci.org/claudioandre/JohnTheRipper/jobs/169073706

**Comment by magnumripper** [comment]
Closing as dead. #2099 is still open.

**Pull request closed without merging**
