### PR TITLE
Add a note about PrestaShop 1.7

### PR DESCRIPTION
**Pull request by kholia**

### CODE REVIEW

**Comment by kholia** [comment]
Weird. I did not select any reviewer in this PR. I usually do a PR to get an OK signal from the build bots. I am wary of pushing directly to the repository.

**Comment by magnumripper** [comment]
That's a good habit of course 👍

**Comment by jfoug** [comment]
Do we not have a fat format for this one?

**Comment by kholia** [comment]
> Do we not have a fat format for this one?

I don't think so but I am not 100% sure.

**Pull request merged**
