### PR TITLE
Update siemens-s7_fmt_plug.c

### PR DESCRIPTION
**Pull request by loverszhaokai**
Maybe this is a **spell** mistake :)

### CODE REVIEW

**Comment by loverszhaokai** [comment]
Oh, Let me check it.

**Comment by loverszhaokai** [comment]
Thanks to @frank-dittrich , there are more spell errors.

**Comment by frank-dittrich** [comment]
No, these are not my errors. I just __noticed__ them!

**Comment by loverszhaokai** [comment]
Sorry, @frank-dittrich . Yes, I do not mean that you made the errors. I just want to thank you to give me advice that there are some more errors.

**Comment by frank-dittrich** [comment]
No problem. For some reason, you found even more errors than I did using git grep ...

**Comment by loverszhaokai** [comment]
I checked all the inint() in *_fmt_plug.c.

**Comment by magnumripper** [comment]
The ipad/opad are same size so is only a cosmetic bug. The "digest34" lead to slight over-allocation so no real problem. This can't be merged now because things changed mid-air but I'll commit the dominosec fix manually.

**Pull request closed without merging**
