### PR TITLE
Various enhancements for the TrueCrypt format

### PR DESCRIPTION
**Pull request by kholia**
Changes,

+ Support for TrueCrypt's boot mode

+ Twofish support

+ Serpent support

+ Unify XTS stuff a bit

Instead of the hack to support `boot mode`, maybe I can add a new mini-format `truecrypt_RIPEMD_160B` which would be very similar to `truecrypt_RIPEMD_160`.

Also see https://github.com/magnumripper/JohnTheRipper/issues/1876.

I am planning to add an extra field to the hash format (as explained in #1876) to support user controllable cracking of cascaded cipher modes.

### CODE REVIEW

**Comment by jfoug** [comment]
Would a single xts.h/.c file be better?  I think all it will do is perform the XTS code, and use the 'primitives'.  That way, you simply include xts.h and whatever primitive algo headers are needed.

Just an idea.

**Comment by jfoug** [comment]
```c
// xts.h
typedef void (*XTS_func) unsigned char *double_key, unsigned char *out,
		const unsigned char *data, unsigned len, int bits);
XTS_func Twofish_XTS_decrypt;
XTS_func Serpent_XTS_decrypt;
XTS_func AnyOther_XTS_decrypt;
```

Then xts.c would define all of those

**Comment by kholia** [comment]
I like the idea. It will eliminate the need to introduce new files. I am giving it a try now.

**Comment by jfoug** [comment]
The one issue we have is ability to turn on or off algo, due to lack of it on a machine.  But we can do that with #defines within the header/source.

I was not thinking to add the includes INTO the xts.h file, BUT if you do that, then all you need to do is include that 1 file, and everything needed to do XTS for any algo is available.

Using a function typedef might be good, in that it may allow some common code, that simply takes a function pointer, and then deref/calls it internally, and thus would not care or even need to know which XTS variant is being used at the time.  The calling code would provide the proper function pointer based upon what algo needs to be tried now.

Again, just review ideas.

**Comment by kholia** [comment]
@jfoug Thanks for the ideas. In the latest commit, I have introduced a generic `XTS_decrypt` function which accepts `algorithm` as an input.

**Comment by kholia** [comment]
In the latest commit, I have introduced a new mini-format `tc_ripemd160boot` to handle the boot mode hashes. This removes the need for hijacking the `nkeyfiles` field to indicate the two different kinds of ripemd160 modes (one with 2000 iterations, and the other with 1000 iterations).

Next, I would like to support double-cascaded ciphers.

**Comment by kholia** [comment]
I am merging the current set of changes. I will send new stuff in a separate PR.

**Pull request merged**
