### PR TITLE
rexgen save-restore

### PR DESCRIPTION
**Pull request by jfoug**
This is not ready yet, but I wanted the pull request, so that others could see the changes also.

NOTE, this requires v1.4.x or greater of librexgen https://github.com/teeshop/rexgen/pulls

### CODE REVIEW

**Comment by jfoug** [comment]
Issue #570

**Comment by magnumripper** [comment]
Can we merge this right now or should we wait for something in rexgen?

**Comment by jfoug** [comment]
We have to wait. This will break RUNTIME of rexgen in john if merged now. Well, actually, what it will do it 100% disable rexgen until it is updated to v1.04.   Now, someone can pull the 1.04 from my git repo, but that is not the official release.

The issue is that we went from creating a new iterator for each word (so the bug in rexgen was not apparent), to using a single iterator over and over again as words are tested.  Rexgen requires the saved iterator to be able to resume, BUT it has a bug that its state is not reset properly when the callback function lists that the run for that word is done.

**Comment by magnumripper** [comment]
So once this is fixed in rexgen we should probably bump our version requirement for that lib in configure, in order to "accept" it.

**Comment by jfoug** [comment]
Check out the first patch. Already done that, BUT we really have to wait and see what actual version gets put into the lib.  From past history, he has accepted no changes from me, and has redone them himself (often wrong), and always changes things, thus the code done will have to adapt.

**Comment by jfoug** [comment]
Created new PR, based upon current code. Closing this one out.

**Comment by jfoug** [comment]
Completed with PR #2199

**Pull request closed without merging**
