### PR TITLE
Fix alignment problem in panama format

### PR DESCRIPTION
**Pull request by kholia**
See https://github.com/magnumripper/JohnTheRipper/issues/2868 for discussion.

### CODE REVIEW

**Comment by jfoug** [comment]
Here is a much simpler fix (put a comment there also on why we are doing this)

```c
static char (*saved_key)[PLAINTEXT_LENGTH + 3];
```

**Comment by kholia** [comment]
@jfoug Neat 👍

**Comment by magnumripper** [comment]
> Here is a much simpler fix
> ```c
> static char (*saved_key)[PLAINTEXT_LENGTH + 3];
> ```

This is **begging** for future bugs. Something like `((PLAINTEXT_LENGTH + 3) / 4) * 4` (outer paren not needed but easier to understand) or even `((PLAINTEXT_LENGTH + (ARCH_WORD - 1)) / ARCH_WORD) * ARCH_WORD` should be safer.

**Comment by jfoug** [comment]
I thought the same (later).

A better fix is
```c
static char (*saved_key)[((PLAINTEXT_LENGTH + 4)/4)*4];
```

That will always make it evenly divisible by 4, and also always have space for null terminator.

**Comment by jfoug** [comment]
You can NOT do the +3   What happens if the PLAINTEXT is evenly divisible by 4.  Now you have no null terminator ;)

**Comment by jfoug** [comment]
ARCH_WORD is absolutely NOT needed here. This format requires the data to be 4 byte aligned. Thus, ARCH_WORD being ambiguous is really not the proper data item.  I did not actually look 'into' what the sph_h stuff actually did to require the alignment, but it does.  What we do for saved_key, is simply allocate a single huge buffer, but then logically return it the program in fixed sized chunks (probably requiring NULL termination).  So as long as those fixed site chunks are evenly divisible by what the sph_h for panama wants, AND are large enough for the formats password length, AND are large enough to carry the extra byte for null, then all is well.  But this is a MUCH better fix, than digging in and doing alignment handling at the point of usage.  Just make sure the data IS properly aligned, in the code where WE are in charge (i.e. where the compiler can not do things properly), and we have succeeded.

Btw, nice to see u back ;)  Havea good trip?

**Comment by magnumripper** [comment]
My holiday was excellent! Hardly even a cell phone (let alone Internet) for a full week. And then enjoying 400 unread mails from GitHub et al filled with Good Stuff! It's so nice to see `87 files changed, 1930 insertions(+), 404 deletions(-)` after I was drinking beer and getting a sun tan 😉  Perhaps I should do that more often?

**Comment by jfoug** [comment]
LOL, that type overlap may be rare.   A LOT of those changed files were simply boiler plate porting stuff.  Well, each one was nuanced FOR the exact format being dealt with, but overall, it was all the same type stuff, just a huge amount of it.

I was really glad to see the UBSAN alignment working.  Found some things which were missed by my 32 bit sparc, which was happy as could be due to ARCH_WORD only being 32 bit.  I was actually surprised that there were that few alignment issues to address.  It had been cleaned up some over time, but I knew there were things 'missed'.  Also, there were formats which I simply commented out on sparc, due to things beyond just simple alignment issues.  But when built on a system with UBSAN AND having the system able to build all formats, it flushes out those bugs.

**Pull request merged**
