### PR TITLE
sunmd5: revise OpenMP support

### PR DESCRIPTION
**Pull request by zzlei**
drop the `threadprivate` stuffs and write the OpenMP clause in a more verbose form

### CODE REVIEW

**Comment by frank-dittrich** [comment]
You might want to fix the build failure caused by your latest commit, see https://travis-ci.org/magnumripper/JohnTheRipper/builds/61716166

**Comment by frank-dittrich** [comment]
Sorry for my confusion about the sequence of commits.
I cloned your repository and tested the 32bit Linux AVX2 (Fedora 21).

```
$ for i in `seq 1 24`; do OMP_NUM_THREADS=$i ../run/john --test=10 --format=sunmd5; done
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... DONE
Speed for cost 1 (iteration count) of 5000
Raw:	959 c/s real, 960 c/s virtual

Will run 2 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (2xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1900 c/s real, 951 c/s virtual

Will run 3 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (3xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	2736 c/s real, 913 c/s virtual

Will run 4 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3276 c/s real, 831 c/s virtual

Will run 5 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (5xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	2881 c/s real, 863 c/s virtual

Will run 6 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (6xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3263 c/s real, 860 c/s virtual

Will run 7 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (7xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3326 c/s real, 867 c/s virtual

Will run 8 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3359 c/s real, 869 c/s virtual

Will run 9 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (9xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3381 c/s real, 874 c/s virtual

Will run 10 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (10xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3401 c/s real, 876 c/s virtual

Will run 11 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (11xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3433 c/s real, 878 c/s virtual

Will run 12 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (12xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3470 c/s real, 882 c/s virtual

Will run 13 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (13xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3466 c/s real, 882 c/s virtual

Will run 14 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (14xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3459 c/s real, 883 c/s virtual

Will run 15 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (15xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3501 c/s real, 887 c/s virtual

Will run 16 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (16xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3501 c/s real, 886 c/s virtual

Will run 17 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (17xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3509 c/s real, 888 c/s virtual

Will run 18 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (18xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3516 c/s real, 889 c/s virtual

Will run 19 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (19xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3500 c/s real, 888 c/s virtual

Will run 20 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (20xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3524 c/s real, 890 c/s virtual

Will run 21 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (21xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3526 c/s real, 892 c/s virtual

Will run 22 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (22xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3540 c/s real, 892 c/s virtual

Will run 23 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (23xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3537 c/s real, 892 c/s virtual

Will run 24 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (24xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3541 c/s real, 893 c/s virtual
```

This is on a quad core CPU Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz, so the default OMP_NUM_THREADS value is 4.

As you can see, the real c/s rate even gets better with higher OMP_NUM_THREADS, at least for multiples of 4.

(I'll repeat the test with 64bit systems, since 32bit really isn't that important, even more so with a 64bit CPU.)

**Comment by frank-dittrich** [comment]
While the self test passed, I got an error with the test suite https://github.com/magnumripper/jtrTestSuite for my 32bit build.

```
[fd@u16gb test]$ ./jtrts.pl -type sunmd5 -stoponerror
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.4-jumbo-1-bleeding_omp [linux-gnu 32-bit AVX2-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=sunmd5                       guesses: 1493 -show=1493 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
Exiting on error. The .pot file tst.pot contains the found data
The command used to run this test was:

../run/john -ses=tst  -pot=tst.pot sunmd5_tst.in --wordlist=pw-200.dic -form=sunmd5
```

First, I thought that this would be an instance of another issue, see https://github.com/magnumripper/JohnTheRipper/issues/1273

But now I doubt that, and I think it is something else, because issue https://github.com/magnumripper/JohnTheRipper/issues/1273 always disappeared with OMP_NUM_THREADS=1, but this issue doesn't:
```
[fd@u16gb test]$ OMP_NUM_THREADS=1 ./jtrts.pl -type sunmd5 -stoponerror -v
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.4-jumbo-1-bleeding_omp [linux-gnu 32-bit AVX2-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.
--pot=NAME option is valid
--encoding=NAME option is valid
all.chr (../run/all.chr) not found
alnum.chr found, inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8 added as a capability
Types to filter on:
sunmd5
Capabilities in this build of john:
jumbo core inc local_pot_valid encode_valid utf8 cp1252 cp1251 koi8r cp437 cp737 cp850 cp858 cp866 iso8859-1 iso8859-15 inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8

form=sunmd5                       guesses: 1488 -show=1488 0:00:00:02 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
Exiting on error. The .pot file tst.pot contains the found data
The command used to run this test was:

../run/john -ses=tst  -pot=tst.pot sunmd5_tst.in --wordlist=pw-200.dic -form=sunmd5
[fd@u16gb test]$ OMP_NUM_THREADS=1 ../run/john -ses=tst  -pot=tst.pot sunmd5_tst.in --wordlist=pw-200.dic -form=sunmd5
Loaded 1500 password hashes with 10 different salts (SunMD5 [MD5 256/256 AVX2 8x3])
Remaining 12 password hashes with no different salts
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Press 'q' or Ctrl-C to abort, almost any other key for status
fukOFF           (u89-sunmd5)
develsdue        (u90-sunmd5)
bartlby          (u91-sunmd5)
%72ha�a�(        (u95-sunmd5)
dffffffffffff__1 (u105-sunmd5)
alsfdkja;__1     (u106-sunmd5)
qwerty__1        (u109-sunmd5)
12345__1         (u112-sunmd5)
summer__1        (u122-sunmd5)
aksarban__1      (u123-sunmd5)
johnny__1        (u124-sunmd5)
admin__1         (u125-sunmd5)
12g 0:00:00:00 DONE (2015-05-09 17:41) 14.28g/s 228.5p/s 228.5c/s 2742C/s boneheadded..enterNow__1
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```
As you see, when I repeat the command, john cracks the remaining hashes.

**Comment by frank-dittrich** [comment]
On a 64bit Linux laptop with CPU `Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz` (4 physical, 8 logical cores, default OMP_NUM_THREADS=8), I used `--test=1` and `sleep 20`, to hopefully reduce the impact of throttling.
```
 $ for i in `seq 1 20`; do OMP_NUM_THREADS=$i ./john --test=1 --format=sunmd5; sleep 20; done
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... DONE
Speed for cost 1 (iteration count) of 5000
Raw:	665 c/s real, 672 c/s virtual

Will run 2 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (2xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1107 c/s real, 556 c/s virtual

Will run 3 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (3xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1556 c/s real, 517 c/s virtual

Will run 4 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1777 c/s real, 448 c/s virtual

Will run 5 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (5xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1358 c/s real, 356 c/s virtual

Will run 6 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (6xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1502 c/s real, 298 c/s virtual

Will run 7 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (7xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1723 c/s real, 265 c/s virtual

Will run 8 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1858 c/s real, 233 c/s virtual

Will run 9 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (9xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1645 c/s real, 248 c/s virtual

Will run 10 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (10xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1777 c/s real, 246 c/s virtual

Will run 11 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (11xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1774 c/s real, 241 c/s virtual

Will run 12 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (12xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1786 c/s real, 236 c/s virtual

Will run 13 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (13xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1770 c/s real, 234 c/s virtual

Will run 14 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (14xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1780 c/s real, 234 c/s virtual

Will run 15 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (15xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1800 c/s real, 232 c/s virtual

Will run 16 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (16xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1817 c/s real, 234 c/s virtual

Will run 17 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (17xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1773 c/s real, 226 c/s virtual

Will run 18 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (18xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1781 c/s real, 227 c/s virtual

Will run 19 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (19xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1788 c/s real, 228 c/s virtual

Will run 20 OpenMP threads
Benchmarking: SunMD5 [MD5 128/128 AVX 4x3]... (20xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1761 c/s real, 227 c/s virtual
```
As expected, OMP_NUM_THREADS=8 provides the best c/s rate, but OMP_NUM_THREADS=16 comes close to that c/s rate.

On this laptop, this is the test suite result, so no problem here (so may be the 32bit issue isn't your fault):
```
(master)test $ ./jtrts.pl -type sunmd5                
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.4-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=sunmd5                       guesses: 1500 0:00:00:01 DONE  [PASSED]
.pot CHK:sunmd5                   guesses: 1500 0:00:00:01 DONE  [PASSED] (1500 val-pwd)

All tests passed without error.  Performed 1 tests.  Time used was 8 seconds
```

**Comment by frank-dittrich** [comment]
BTW:
Apparently, yougot rif of the "mixed declarations and statemenrs" warning, but not of the "implicit declaration of function" warning.
You need to add
```
#ifdef _OPENMP
#include <omp.h>
#endif
```
like it is done for other OpenMP enabled formats.

**Comment by frank-dittrich** [comment]
For a 32bit non-AVX2 build (`CFLAGS="-g -O2 -mno-avx2" ./configure`), the error when running the test suite is gone.
Now I think the issue is indeed the same as https://github.com/magnumripper/JohnTheRipper/issues/1273

**Comment by frank-dittrich** [comment]
These are the results on the same hardware I used for the 32bit test, but this time 46bit Fedora 22 Beta with gcc 5.1.1

```
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... DONE
Speed for cost 1 (iteration count) of 5000
Raw:	1285 c/s real, 1287 c/s virtual

Will run 2 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (2xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	2337 c/s real, 1172 c/s virtual

Will run 3 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (3xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	3260 c/s real, 1123 c/s virtual

Will run 4 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4143 c/s real, 1086 c/s virtual
```

Here also a higher OMP_NUM_THREADS value helps:
```
Will run 8 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4468 c/s real, 1160 c/s virtual

Will run 12 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (12xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4608 c/s real, 1180 c/s virtual

Will run 16 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (16xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4682 c/s real, 1185 c/s virtual

Will run 20 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (20xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4729 c/s real, 1194 c/s virtual

[...]

Will run 48 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (48xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4813 c/s real, 1208 c/s virtual

Will run 52 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (52xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4809 c/s real, 1208 c/s virtual

Will run 56 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (56xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4823 c/s real, 1209 c/s virtual

Will run 60 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (60xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4826 c/s real, 1209 c/s virtual

Will run 64 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (64xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4818 c/s real, 1210 c/s virtual
```

So I think introducing and tuning OMP_SCALE, as suggested by @magnumripper might be a good idea.

**Comment by magnumripper** [comment]
> So I think introducing and tuning OMP_SCALE, as suggested by @magnumripper might be a good idea.

Perhaps. It's not quite the same thing though. Maybe OMP_SCALE will be even better, or maybe it won't be quite as good.

**Comment by zzlei** [comment]
> So I think introducing and tuning OMP_SCALE, as suggested by @magnumripper might be a good idea.

I experimented with `OMP_SCALE` a bit, and here's the result:

**On my laptop** (dual core, 4 threads)
```
[OMP_SCALE=1]
Raw:	1248 c/s real, 328 c/s virtual
[OMP_SCALE=2]
Raw:	1280 c/s real, 333 c/s virtual
[OMP_SCALE=4]
Raw:	1259 c/s real, 331 c/s virtual
[OMP_SCALE=8]
Raw:	1280 c/s real, 336 c/s virtual
```
**On super**
```
[OMP_SCALE=1]
Raw:	7492 c/s real, 235 c/s virtual
[OMP_SCALE=2]
Raw:	8246 c/s real, 259 c/s virtual
[OMP_SCALE=4]
Raw:	8302 c/s real, 259 c/s virtual
[OMP_SCALE=8]
Raw:	8302 c/s real, 259 c/s virtual
```

Seems it helps a little, but not much.

**Comment by magnumripper** [comment]
I guess this is ripe for merging now.

**Pull request merged**
