### PR TITLE
Support Python 3 in ml2john.py utility

### PR DESCRIPTION
**Pull request by kholia**
On a related note, isn't the name `ml2john.py` a little obscure? Should we rename it to something else? Perhaps `mac2john.py`?

Suggestions are welcome!

### CODE REVIEW

**Comment by magnumripper** [comment]
> On a related note, isn't the name ml2john.py a little obscure?

Agreed! In fact I had absolutely no clue what it was.

**Comment by solardiz** [comment]
I agree about renaming to `mac2john.py` or maybe `plist2john.py`.

Should we also rename `lion2john*.pl`? What to rename them to? One idea is `maclion*` or `plistlion*` for consistency with new name of this script.

**Comment by kholia** [comment]
> Does this reuse pieces of third-party code? Is the extent of changes possibly because of updating embedded third-party code snippets to newer versions?

Yes to both. I used this opportunity to grab recent compatible versions of the embedded libraries.

**Comment by kholia** [comment]
> I agree about renaming to mac2john.py or maybe plist2john.py.

I will raise a new PR for this change. Thanks!

**Comment by kholia** [comment]
@magnumripper Hi! I think we will need to merge this PR manually. Travis CI is taking a long break.

**Comment by magnumripper** [comment]
I mised that. Done!

**Pull request merged**
