### PR TITLE
Add pdf2john.pl tool for extracting hashes from PDF files

### PR DESCRIPTION
**Pull request by kholia**
This is more reliable than the "pdf2john.py" script.

Upstream is at https://github.com/kholia/npdf2john URL. This PR is based
on the older "master" branch rather than the newer "ng" branch.

Fixes issue #2388.

### CODE REVIEW

**Comment by magnumripper** [comment]
Perhaps we should have it as npdf2john.pl for clarity?

**Comment by kholia** [comment]
Yes, npdf2john.pl seems better. Latest revision uses this new filename.

**Comment by magnumripper** [comment]
Hmm how about updating doc/README-PDF also?

**Comment by magnumripper** [comment]
Actually, why not also rename npdf2john.pl to pdf2john.pl? Is the 'n' for "new" or something?

**Comment by kholia** [comment]
Yes, the 'n' stood for "new".

The latest revision changes the name to "pdf2john.pl" and updates the docs as well.

**Pull request merged**
