### PR TITLE
Report glibc version with --list=build-info

### PR DESCRIPTION
**Pull request by frank-dittrich**
another try, this time hopefully correct

### CODE REVIEW

**Comment by magnumripper** [comment]
So where does this `__GLIBC__` define come from? I thought we had a hen-or-egg situation.

**Comment by magnumripper** [comment]
This works fine (does not include the sections) on my Mac.

**Comment by frank-dittrich** [comment]
What libc do you have on Mac? Do you know how to report that libc version?
I tried to google that info, but didn't succeed.

**Comment by frank-dittrich** [comment]
What if I have a libc at build time, but not at run time? Can this ever happen (and work)?

**Comment by magnumripper** [comment]
I have absolutely no idea but on Macs it may simply be tied to the general OS X version (as in 10.10.3). Why would we care about libc version anyway? Is it really needed or are we bloating build-info?

**Comment by frank-dittrich** [comment]
I added that glibc version info because the new version on Fedora 22 caused that compile time warning.
So I thought it might be helpful to diagnose problems.

**Comment by magnumripper** [comment]
> What if I have a libc at build time, but not at run time? Can this ever happen (and work)?

You mean another version at run time. I'm pretty sure it can happen.

**Comment by magnumripper** [comment]
> on Fedora 22 caused that compile time warning.

I think we should limit build-info to things that might help with run-time problems, or we'll end up with an amount of code/output that can't be justified.

**Comment by frank-dittrich** [comment]
I didn't just mean another version.
I mean, you build with glibc, however, you don't have glibc at run time,but another libc implementation.
Unlikely, but possible.
May be we really should revert reporting of glibc version, or just drop reporting the runtime libc version.

**Comment by magnumripper** [comment]
> I mean, you build with glibc, however, you don't have glibc at run time,but another libc implementation.

That would not execute at all. The dynamic linker wouldn't even try to resolve it.

**Comment by frank-dittrich** [comment]
Then there is no problem (except bloat). Even a very old libc should have  gnu_get_libc_version().

**Pull request merged**
