### PR TITLE
Keep default Log file permissions, but add option to set in john.conf.

### PR DESCRIPTION
**Pull request by walkerk1980**
Please see previous pull request for use case https://github.com/magnumripper/JohnTheRipper/pull/2247

Added config file parameters LogFilePermissions, PotFilePermissions, IgnoreLogChmodErrors.

Small issue: open() on line 102 of logger.c ignores perms_t on O_CREAT and perms are still set on create to the less permissive defaults.  Perms don't actually get set to more permissive perms until second run of John when chmod() is called in log_file_init().  I'm not that familiar with C or the John code, so it may be a umask I'm not seeing somewhere.  Besides this issue, feature works properly in my testing so far.

### CODE REVIEW

**Comment by magnumripper** [comment]
We do not want your local merges upstream. Please learn git, rebase and re-submit (push force).

**Comment by magnumripper** [comment]
It looks like cherry-picking 2e9093f would suffice.

**Comment by walkerk1980** [comment]
Sorry, will resubmit.

**Comment by walkerk1980** [comment]
Resubmitted as https://github.com/magnumripper/JohnTheRipper/pull/2270

**Pull request closed without merging**
