### PR TITLE
Make ssh-ng saner by using a tiny ASN.1 decoder

### PR DESCRIPTION
**Pull request by kholia**
Thanks to Martin Kleppmann, Jens Getreu, Jouni Malinen (Reaver WPS),
and TinyBER!

### CODE REVIEW

**Comment by kholia** [comment]
This tries to solve https://github.com/magnumripper/JohnTheRipper/issues/427.

**Comment by kholia** [comment]
This is undergoing testing currently - I would like to reduce false positives even more.

Hold on :-)

**Comment by kholia** [comment]
@magnumripper does this look legit?

**Comment by magnumripper** [comment]
Sure, looks like the dog's danglies to me.

**Pull request merged**
