### PR TITLE
fgetl and fgetll lines with NULLs.  fgetll memory leak

### PR DESCRIPTION
**Pull request by jfoug**
#3574

Both functions would (usually) skip the next line, if there was a NULL byte in the current line.

fgetll returned the wrong pointer if there was a NULL in the line (on long lines). Looks like a cut/paste bug from the code handling nulls prior to the section to handle long lines.

### CODE REVIEW

**Comment by jfoug** [comment]
The whole issue came from 3 things. 

1 looking at fgetll and 'seeing' that the handling of lines with NULLs in them was wrong, and dropping a line.
2. I could see the same problem in fgetl (hidden a bit).
3. I saw near the bottom of fgetll an obvious bug (returned s, even though cp was the newly allocated buffer, which the caller must clean up).  This was almost certainly a cut/paste bug when the null logic was added to the 'normal' sized lines within fgetll

Now, we can handle this in several ways.
1. we have to fix the memory leak bug.
2. the code as supplied in this commit fixes the drop of the next line of a binary file.  We can go with this.
3. we can ignore the problem, users should not be using these functions for binary data.

It appears that mgetl worked fine for the binary data.  I tested this with wordlist.c  (simply using ./john inp --stdout)   I then changed the read 1 line statement in wordlist, to get the function I wanted to test.

the mgetl worked out of the box.
both fgetl and fgetll would skip the line following a line with a NULL in it.
my VC started out with fgetl and showed the bug.  my cygwin build started out with mgetl, and hid the bug (and made me scratch my head a bit about why it was working when it should not have been).

But since this is a core function, we do have to get buy in from Solar on this one.

**Comment by jfoug** [comment]
in wordlist mode, there was no warning about embedded NULL bytes, at least in my testing.

**Comment by magnumripper** [comment]
I think we should accept all of this, I just wanted Solar to have a look see first. The fgetll part is definitely going in.

> in wordlist mode, there was no warning about embedded NULL bytes, at least in my testing.

I guess it only happens in some cases, ie. when using memory buffer and rules, or something like that. I'm sure it does warn in *some* situations.

**Comment by magnumripper** [comment]
Solar took a walkover. I assume you've tested this fairly well, so I merged it

**Comment by jfoug** [comment]
> Solar took a walkover. I assume you've tested this fairly well, so I merged it

I tested this on 4 environments (linux 32/64 bit, cygwin64 bit and VC. I tested with normal unix txt files (\n), and dos files \r\n  and f'd up files with some lines \n and some \r\n  (3 files only).  I wrote the lines to be easily tested, to make it very visible if lines were not read.  Prior to changes, both functions would drop a line following a line with an embedded null.  After the change, both functions would read the line with the null, and printf 'up to' the null (expected behavior), and then the next line would be properly read.
I tested from within john, but modifying wordlist.c, so that the function I wanted tested would always be used.   Then I simply used ``` ./john input-test.txt --stdout ```  Observing the output lines.  Note this was not comprehensive, but I was assuming that most files were properly handled by the functions, so other than running a single file that contained no nulls, through both functions, all testing was on null embedded files.  However, stating all of that, I am very happy with the code changes turned in.

**Comment by solardiz** [comment]
I looked into including a fix for this issue into core's `fgetl`, but unfortunately the fix committed here looks subtly wrong - I think it'll look for `'\n'` in uninitialized or stale memory when `fgets` encounters EOF or an error without first seeing a linefeed - e.g., if the last line in a file doesn't end with `'\n'`. I'm not aware of a way to fix the original issue properly while continuing to use `fgets`. So I'll probably leave it unfixed in core for now.

**Pull request merged**
