### PR TITLE
Add tool "kerberom" to /run

### PR DESCRIPTION
**Pull request by Fist0urs**
As discussed by email with @magnumripper here is the PR

This tool is aimed to retrieve ARC4-HMAC encrypted tickets to be cracked with john. 
Usage is provided in the README.md. I will write an HOWTO following, to explain what are the prerequisite within kerberos to use the tool.

I've put it in /run as I didn't know where exactly it should be. 

If I make any modification within the main git repository that are useful I'll backport them here.

If you have any requests/suggestions, do not hesitate.

### CODE REVIEW

**Comment by magnumripper** [comment]
Wow, 133 files? How much of this is required dependencies, as in standard ones? It seems a bit too much. I need to assess this.

**Comment by Fist0urs** [comment]
Indeed. I'll test if the tool works with the actual dependencies imported and modify that

**Comment by Fist0urs** [comment]
Ok, I've removed all dependencies, the actual version of ldap3 seems to work (it was not the case before, with hash)

I'll try to write the HOWTO as soon as I can

**Comment by magnumripper** [comment]
Great, it looks more sane now. Can you please also squash them and force-push, so we don't get the gigantic commits in our history.

**Comment by kholia** [comment]
Can the different files be merged into a single .py file (at the cost of maintenance overhead)?

**Comment by magnumripper** [comment]
> Can the different files be merged into a single .py file (at the cost of maintenance overhead)?

That might be overkill, especially if that makes us different from upstream.

**Comment by Fist0urs** [comment]
I may try to do a single .py file, but it will not be the best for readibilty. Concerning evolutions, there's not much to add to this tool so this would not be a problem (and I would backport changes here)

**Comment by magnumripper** [comment]
Could you please just squash these three commits into a single one? I'll merge it right away then. I just don't want the 133 files in the git history.

**Comment by Fist0urs** [comment]
Sure, I'll do it on monday as I don't have access to all I need

**Comment by Fist0urs** [comment]
It should be ok now :+1:

**Comment by magnumripper** [comment]
Thanks! Very trivial fixes in 593a3a9.

**Pull request merged**
