### PR TITLE
Add support for cracking SNMPv3 hashes

### PR DESCRIPTION
**Pull request by kholia**
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/423.

Special thanks goes to @Lekensteyn for making this work possible.

### CODE REVIEW

**Comment by kholia** [comment]
I could not figure out a way to distinguish between SNMPv3 messages using HMAC-MD5-96 or those using HMAC-SHA1-96. It seems like there is no such way.

**Comment by magnumripper** [comment]
So only 12 bytes of HMAC is used, so we don't know if it was made with SHA-1 or MD5?

**Comment by kholia** [comment]
Thanks! :-)

**Comment by kholia** [comment]
> So only 12 bytes of HMAC is used, so we don't know if it was made with SHA-1 or MD5?

True. I could not find a field / "distinguisher" in the SNMPv3 packets which might indicate the actual algorithm being used.

**Pull request merged**
