### PR TITLE
Refactor Travis tests

### PR DESCRIPTION
**Pull request by claudioandre**
An idea of reorganization to allow random tests. E.g.
- 2john tools;
- option --foo is working/cracking;

### CODE REVIEW

**Comment by jfoug** [comment]
I have always thought we should do more than the simple ```--test-full```   We should be careful to not make the CI tests take too long, but additional core type functionality (i.e. different options) certainly should get some auto testing.  At least simple smoke tests which will quickly ferret out (or keep them from crawling in)things like ASAN, memory leaks, etc.

**Comment by claudioandre** [comment]
> things like ASAN, memory leaks, etc

Indeed.

* I was expecting some complains for zip2john (I will try memdbg).
* It is easy to 'design' a john session that finishes in less than 1-2 minutes. [1]
* some fast (but good) tests for --mask, --single-seed, ... might result valuable after a complicated patch; even for ARCH_WORD or "const" migration.

[1] For example, I had to skip --single for the rar test in this PR.

**Comment by jfoug** [comment]
Would it make sense to look at testing the *2john stuff also (at least some of them) ?

**Comment by claudioandre** [comment]
The PR has gpg2john, rar2john and zip2john because (my memory saying) real users was talking about them recently.

From now on, I intend collect test cases from issues/real cases.

**Comment by claudioandre** [comment]
memdbg found some leaks:
- not in JtR itself, only in 2john tools;
- no bugs in ASAN itself + memdbg;
- I'll PR soon.

**Comment by magnumripper** [comment]
Shouldn't we merge this? I'm not good at build bots stuff so I can't say I understand it fully.

**Comment by kholia** [comment]
I took a quick look, and this PR seems to be fine.

@claudioandre Can you please rebase, and squash your multiple commits into one?

**Comment by claudioandre** [comment]
I will remove this branch and create a new one.

**Pull request closed without merging**
