### PR TITLE
Drop a whole bunch of obsolete stuff from "unused" directory

### PR DESCRIPTION
**Pull request by magnumripper**
Please review. I'm pretty sure we can simply drop all these files.

### CODE REVIEW

**Comment by jfoug** [comment]
I would have liked to keep  src/unused/SHA512_qnx.pm out there.  It is the only code I know of that properly handles the buggy QNX implementation of sha512 (other than the changes we made in john's format).  It is used by pass_gen.pl.  It was put into unused because it requires 'special' care to play nice with perl's normal sha512 module.

**Comment by magnumripper** [comment]
> I would have liked to keep src/unused/SHA512_qnx.pm out there

Fair enough, fixed now.

**Comment by magnumripper** [comment]
@kholia I'll let you speak before we merge. Some of the files might be the only "docs" for something. If you see some case like that, we should move/rewrite it to something in docs/

**Comment by kholia** [comment]
@magnumripper I am OK with merging this. Go right ahead.

I had a quick look, and dump-apex-hashes.sql file seems to be useful. It is also referenced in doc/README.apex file. I will open a PR later to move this .sql script to README.apex file itself. This action should not block the merging of this PR.

**Pull request merged**
