### PR TITLE
some fixes in the building system

### PR DESCRIPTION
**Pull request by zzlei**
some minor fixes

### CODE REVIEW

**Comment by jfoug** [comment]
Change should be made in configure.ac not on configure Then autoconf run to Regen configure

**Comment by zzlei** [comment]
Actually configure.ac was modified in last commit, but I forgot to regenerate configure...

**Comment by jfoug** [comment]
Great, my bad

**Comment by jfoug** [comment]
I just Wanted to make sure changes were not blown away next time someone edited the .ac File

**Pull request merged**
