### PR TITLE
docs: alert about a distro package of JtR

### PR DESCRIPTION
**Pull request by claudioandre**
If nobody complains, I'll merge this.

### CODE REVIEW

**Comment by frank-dittrich** [comment]
If we add such a comment, we should at least partly blame ourselves for not releasing a new stable jumbo version for a very long time.
After all, what should a distro do here?
Distribute just a john core package, without any jumbo additions?
Distribute a jumbo package based on our last jumbo release?
Pick some random git commit for packaging?

And when we finally manage a new jumbo release, we need to rephrase this comment again.

**Comment by frank-dittrich** [comment]
@magnumripper 
> However, it's a bad idea to run a distro's (old) version and then report bugs to us. If running a distro, user should report bugs to them, not us.

And what are the distros supposed to do with these bug reports? Report them upstream? Cherry-pick individual git commits for new distro releases?

**Comment by claudioandre** [comment]
> I wouldn't say it's generally a bad idea 

In fact, it is up to you to define what should be stated (and keep it, as is, maybe, is the best choice). But, personally, I would like to make it clearer somewhere.
* distro packages are from a remote past (years);
* why report a bug based on "literally several thousands of commits" in the past)
* report bugs to the distro is a waste of time, IMO;
* report bugs in the distro and here is 2x waste of time; 

Ok (in my opinion), it is always a bad idea to use the distro package.

**Comment by magnumripper** [comment]
> And what are the distros supposed to do with these bug reports? Report them upstream? Cherry-pick individual git commits for new distro releases?

I have no idea but I do know that such bug reports are just useless noise to me. This is why I think we should either release at least 1-2 times a year (I wish we could but we simply can't because we don't have the resources) or drop the notion of releases.

**Comment by solardiz** [comment]
> I think we should either release at least 1-2 times a year

Yes, I think we should.

> (I wish we could but we simply can't because we don't have the resources)

I think we do have the resources, we're just not trying to make releases - but we should.

**Comment by magnumripper** [comment]
I'll rewrite this a little

**Pull request closed without merging**
