### PR TITLE
Add WPA2-PSK-SHA256 (802.11w) support

### PR DESCRIPTION
**Pull request by kholia**
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2635.

This PR depends on "new" OpenSSL functionality, namely `CMAC_Init` and family. I can try to implement this functionality in a native manner.

This works well with https://github.com/magnumripper/JohnTheRipper/pull/2642 too.

### CODE REVIEW

**Comment by kholia** [comment]
Thanks for the review 👍 

Hopefully, this code won't cause us problems down the line.

**Comment by kholia** [comment]
I merged the wrong PR! Hopefully merging this is also OK.

**Comment by magnumripper** [comment]
If there's a need for a new(ish) version of OpenSSL, these changes should be #ifdef'd so we get the old WPA2 functionality with older OpenSSL and all functionality when possible.

Other than that, good stuff 👍 👍 

We should open an issue for SIMD support and another one for OpenCL support (if we didn't already).

**Comment by kholia** [comment]
Thanks! :-)

This code works on TravisCI bots which run an old Ubuntu version. So we should be mostly OK with the OpenSSL version part.

The computationally intensive parts already have SIMD support. The existing `wpapsk_sse` function is also used for the new hash type.

I will open an issue for adding OpenCL support.

**Comment by magnumripper** [comment]
> The computationally intensive parts already have SIMD support

That's great! For OpenCL however, we need to do all calculations on GPU, so we'll need to find some public code for a new kernel function.

**Comment by kholia** [comment]
For a pure GPU kernel, we need to do SHA-256, HMAC-SHA256, AES, and "CMAC" on the GPU.

For adding initial OpenCL support, we can run the slow KDF on the GPU, and do the fast `sha256_prf` part on the CPU.

**Comment by magnumripper** [comment]
The only thing we don't have OpenCL gears for already is the CMAC. I never heard of it btw, I need to google it.

**Comment by kholia** [comment]
I barely know how to use CMAC.

http://ftp.usa.openbsd.org/pub/OpenBSD/src/sys/crypto/cmac.c seems like a fairly portable CMAC implementation.

The wpa_supplicant project has another implementation of the CMAC function in `src/crypto/aes-omac1.c` function.

Both these implementations are under the BSD license.

**Pull request merged**
