### PR TITLE
Break source in small code units

### PR DESCRIPTION
**Pull request by claudioandre-br**
Is there any acceptable way to deal with "source packages" in C? 
* one way I can create small units of code and include them once in other source files.

To simplify code management since.
- `-list=opencl-devices` code is self-contained;
- kernel build code is self-contained;
- etc.

I can move them all to another `.c` files (but I dont want to change the `#include common-opencl.h`).

The `common-opencl.h` is the **package**, included once.
****

The PR is an example

### CODE REVIEW

**Comment by magnumripper** [comment]
There's nothing wrong with sourcing (with `#include`) a C source file. I would eg. break out the list-devices stuff in some new file (eg. `opencl_list_dev.c`) and simply include it from `opencl_common.c`.

Some people would call that new file `opencl_list_dev.h` even though it contains code - just because it's meant to be sourced but IMHO that's very confusing. Headers are one thing, code is another. Both can be sourced with `#include`.

**Comment by magnumripper** [comment]
I approved but didn't merge. In general, you can merge at will once any of us has approved.

**Comment by claudioandre-br** [comment]
People would say that a `.c` file is meant to produce a `.o` file. 
* Anyway, I would wait to see if any C-ist guy complains.

**Comment by solardiz** [comment]
Thanks, Claudio. I like having more smaller files with good logical separation between them. However:

I strongly dislike the introduction of a subdirectory called `code`. I think this is confusing. Why introduce a subdirectory at all?

I mildly dislike `#include` of a `.c` file. I sometimes do that myself, but in unusual cases where I think I have more significant reasons to do it. In this case, I think it can be a usual `.c` file compiled into an `.o` file on its own if we simply export 3 functions from the "base" file - right? If so, maybe namespace those functions by adding some name prefix to them, and export them, so that the files can be compiled separately and by usual means.

**Comment by claudioandre-br** [comment]
> I strongly dislike the introduction of a subdirectory called `code`.

We are procrastinating #2789. We will need to, at least:
```
_ src
|_ opencl
     |_ kernels
     |_ include
     |_ code (another src. Should all formats and helper routines be at OpenCL root?)
```

**Pull request closed without merging**
