### PR TITLE
Use CircleCI for MinGW builds instead of Travis CI

### PR DESCRIPTION
**Pull request by kholia**
@magnumripper @jfoug this is still WIP!

### CODE REVIEW

**Comment by kholia** [comment]
Things are already looking good, https://circleci.com/gh/kholia/JohnTheRipper/24 (go to "Artifacts" option).

**Comment by kholia** [comment]
Automated testing of the builds using Wine is now done :)

**Comment by kholia** [comment]
@magnumripper it would be great if you could register for a CircleCI account (using your GitHub account).

Once that is done, this pull request should be ready to merge.

**Comment by jfoug** [comment]
Is there any way to have wine already installed on the container, then simply disable it prior to ./configure and then re-enable to do the testing?

**Comment by kholia** [comment]
@jfoug there should be a way, I will run some more experiments (probably after the merge, once things are at least working).

**Comment by jfoug** [comment]
It sounds nice to be able to pre-install stuff into your own container.  Yes it is nice to have a 'clean' environment to start from every time, but 'too' clean (i.e. not enough stuff installed), simply makes the process take a ton time longer, and causes a lot of unneeded internet traffic downloading/installing so many packages.   The CircleCI method seems much more robust than TravisCI

**Comment by kholia** [comment]
@jfoug wine is now pre-installed in the container, all seems to be well :)

**Comment by kholia** [comment]
@jfoug here are the current bench-marking numbers,

```
$ OMP_NUM_THREADS=2 wine john.exe --format=net-md5 --test
Will run 2 OpenMP threads
Benchmarking: net-md5, "Keyed MD5" RIPv2, OSPF, BGP, SNMPv2 [MD5 32/64]... (2xOMP) DONE
Many salts:	4537K c/s
Only one salt:	3609K c/s

$ OMP_NUM_THREADS=2 ../run/john --format=net-md5 --test
Will run 2 OpenMP threads
Benchmarking: net-md5, "Keyed MD5" RIPv2, OSPF, BGP, SNMPv2 [MD5 32/64]... (2xOMP) DONE
Many salts:	5851K c/s real, 5851K c/s virtual
Only one salt:	4939K c/s real, 4989K c/s virtual
```

The MinGW builds are doing decently well, I think.

**Comment by jfoug** [comment]
Can we configure properly with wine already installed???  Be sure to look to make sure that the configure says we are cross compiling. If it says NO to cross compiler, then the configure may not be setting things up right.

**Comment by kholia** [comment]
@jfoug yes, we can configure properly with wine installed (pretty weird I know).

You can check the logs at https://circleci.com/gh/kholia/JohnTheRipper/43 URL.

The logs do say,

```
checking whether we are cross compiling... yes
```

**Comment by kholia** [comment]
In the container, the "binfmt_misc" stuff isn't configured at all. This prevents Wine from greedily running the .exe files generated by the configure itself.

This is my current theory (TM).

**Comment by jfoug** [comment]
So there is nothing 'mounted' for wine by default, you build, and then later mount so that wine works?  Sounds good.  As long as configure can not execute the mingw compiles natively (even if emulated), we should be fine.  That was the problem I saw after installing wine. Configure thought it was a native build, and all hell broke loose.

**Comment by magnumripper** [comment]
> @magnumripper it would be great if you could register for a CircleCI account (using your GitHub account).

Done.

**Comment by magnumripper** [comment]
WTF it selected the "master" branch without asking me. There is absolutely no reason whatsoever to assume that is the default branch.

**Comment by magnumripper** [comment]
Will it build bleeding-jumbo once we merge this? I can't see any setting for picking a branch.

**Comment by magnumripper** [comment]
Hmm now it did build bleeding-jumbo. Seems to be totally random.

**Comment by magnumripper** [comment]
Now let's see what happens :fearful:

**Comment by magnumripper** [comment]
It seems to use --test instead of --test=0 (or just "make check"). That will take a good while.

**Comment by jfoug** [comment]
How do we view build status now on this new CI ?

**Comment by kholia** [comment]
@magnumripper I will fix the "--test=0" thing (was just thinking of that in the gym shower) :D

**Comment by kholia** [comment]
@jfoug try https://circleci.com/gh/kholia/JohnTheRipper/43 URL for now, @magnumripper will have some official links soon :)

**Comment by kholia** [comment]
https://circleci.com/gh/magnumripper/JohnTheRipper seems to be it.

**Comment by kholia** [comment]
@jfoug Fedora's MinGW OpenSSL bits can match https://slproweb.com/products/Win32OpenSSL.html in  speed.

With "Win64 OpenSSL v1.0.2b Light", I get the following numbers,

```
$ OMP_NUM_THREADS=2 wine john.exe --test --format=net-md5
Will run 2 OpenMP threads
Benchmarking: net-md5, "Keyed MD5" RIPv2, OSPF, BGP, SNMPv2 [MD5 32/64]... (2xOMP) DONE
Many salts:	4496K c/s
Only one salt:	3653K c/s
```

So, the default MinGW build should be usable as it is, I think.

**Comment by jfoug** [comment]
You do not have a deploy section yet, correct?  So there is no way for external users to yet get the MinGW prebuilt

**Comment by kholia** [comment]
@jfoug yep, that's right.

I am talking with Circle CI support to get this stuff working. However, I suspect that this might take a while.

**Pull request merged**
