### PR TITLE
use scatter instruction in sse-intrinsics

### PR DESCRIPTION
**Pull request by zzlei**
tested on MIC, no noticeable performance improvement

### CODE REVIEW

**Comment by magnumripper** [comment]
Right. Are there more instances of vswap we need to fix?

**Comment by magnumripper** [comment]
OK we have one
```C
#define vswap64(n)                                          \
  {                                                         \
    n = vshufflehi_epi16(vshufflelo_epi16(n, 0xb1), 0xb1);  \
    n = vxor(vslli_epi16(n, 8), vsrli_epi16(n, 8));         \
    n = vshuffle_epi32(n, 0xb1);                            \
  }
```
Will this not "return" the right thing though? I think in gcc it will. The last statement will be the value.

**Comment by zzlei** [comment]
This works:
```c
int a = 0;
int b = ({a += 1, a += 2, a += 3});
```
while this doesn't:
```c
int a = 0;
int b = {a += 1, a += 2, a += 3};
```
The parentheses around the curly braces are necessary. So every time we use `vswap64` defined as above, we must guarantee it's enclosed by parentheses.

**Comment by magnumripper** [comment]
Cool. Is this guaranteed by the C standards? I have a feeling we're on somewhat thin ice here.

We should add the parens to the definitions.

**Comment by zzlei** [comment]
Well, I made a mistake in my last comment. 
I intended to write `{a += 1; a += 2; a += 3;}` instead of `{a += 1, a += 2, a += 3}`. 
And actually `(a += 1, a + 2, a += 3)` would work, which is a standard use of comma operator.

**Comment by magnumripper** [comment]
I have some faint memory we're not guaranteed execution order when using a comma. I might be wrong.

**Comment by magnumripper** [comment]
It seems I was wrong, commas should be fine. The whole thing will evaluate to whatever is after the last comma.

**Comment by magnumripper** [comment]
Fixed the SSE2 version of vswap64 in a0407fe

**Pull request merged**
