### PR TITLE
iwork-opencl: move all work to GPU, v2

### PR DESCRIPTION
**Pull request by kholia**
`../run/john --test-full=0 --device=0 --format=iwork-opencl` says `FAILED (iwork-opencl sets FMT_CASE but all test-vectors are case-insensitive)`. However, there is a test-vector with a mixed-case password! Weird?

### CODE REVIEW

**Comment by kholia** [comment]
This is not passing the Travis CI testing, and I am out of debugging ideas.

**Comment by magnumripper** [comment]
I also get this
```
$ ../run/john --test --format=iwork-opencl -dev=2
Device 2: GeForce GT 650M
Benchmarking: iwork-opencl, Apple iWork '09 / '13 / '14 [PBKDF2-SHA1 AES OpenCL]... FAILED (cmp_all(1))
```

**Comment by magnumripper** [comment]
Here's a catch (due to my poor documentation): The PBKDF2 has this salt struct
```c
typedef struct {
        unsigned int  length;
        unsigned int  outlen;
        unsigned int  iterations;
        unsigned char salt[SALTLEN];
} pbkdf2_salt;
```

Your new iwork_salt HAS to start exactly like that, just add the rest last:
```c
typedef struct {
	uint salt_length;
	uint outlen;
	uint iterations;
	uchar salt[SALTLEN];
	uchar iv[IVLEN];
	uchar blob[BLOBLEN];
} iwork_salt;
```

However, fixing that did not help much.

**Comment by magnumripper** [comment]
Another bug:
```diff
                for (i = 0; i < 32; i++) {
-                       if (hash.c[i] != hash.c[32+i]) {
+                       if (hash.c[i] != plaintext[i]) {
                                success = 0;
                                break;
                        }
```
Still didn't help though.

**Comment by magnumripper** [comment]
OK, here's what works (the mentioned struct fixes needed too)
```diff
@@ -132,7 +131,7 @@ void iwork_final(MAYBE_CONSTANT iwork_salt *salt,
 
                // SHA256(plaintext + 32)
                for (i = 0; i < 32; i++)
-                       md.c[i ^ 3] = plaintext[32 + i];
+                       md.c[i ^ 3] = plaintext[i];
                md.c[i ^ 3] = 0x80;
                md.w[15] = i << 3;
 
@@ -143,7 +142,7 @@ void iwork_final(MAYBE_CONSTANT iwork_salt *salt,
                        hash.w[i] = SWAP32(hash.w[i]);
 
                for (i = 0; i < 32; i++) {
-                       if (hash.c[i] != hash.c[32+i]) {
+                       if (hash.c[i] != plaintext[32 + i]) {
                                success = 0;
                                break;
                        }
```
With this, it passes --test BUT it still doesn't pass --test-full=0 so there's at least one more bug to catch.

**Comment by magnumripper** [comment]
There was probably a race condition in that any_cracked-bit trick. I mailed you a patch that seems to work.

**Comment by kholia** [comment]
Thanks @magnumripper! I was doing SHA256(plaintext + 32) while SHA256(plaintext's first 32 bytes) was required. Thanks for catching this blunder.

**Comment by kholia** [comment]
With your changes, the Travis CI bots are very happy :)

I will be merging this soon.

**Pull request merged**
