### PR TITLE
Fix a warning in sunmd5 seen in gcc 9

### PR DESCRIPTION
**Pull request by claudioandre-br**

### CODE REVIEW

**Comment by claudioandre-br** [comment]
If I do that:

Linux
```
Testing: SunMD5 [MD5 512/512 AVX512BW 16x3]... (3xOMP) .circleci/circle-ci.sh: line 136:  5809 Segmentation fault      $WINE $JTR_BIN --test-full=0
Exited with code 139
```

Wine
```
Testing: SunMD5 [MD5 32/32]... (3xOMP) wine: Unhandled page fault on write access to 0x03f20000 at address 0x7ee62fdd (thread 009c), starting debugger...
err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Unhandled exception: page fault on write access to 0x03f20000 in 32-bit code (0x7ee62fdd).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7ee62fdd ESP:04cae850 EBP:04cae858 EFLAGS:00010a02(  R- --O I   - - - )
 EAX:00000000 EBX:03c2107b ECX:3ff3e41e EDX:ffff7ff8
 ESI:03c19038 EDI:03f20000
Stack dump:
0x04cae850:  03c19020 04cae928 03c1907c 6db4891b
0x04cae860:  03c2107b 00000000 ffff7ffd 03ba018f
0x04cae870:  6381d080 00000000 00000000 03c1907c
0x04cae880:  00000001 04cae928 04cae948 006333e5
0x04cae890:  03c1907c 03c19020 00000001 64b46b04
0x04cae8a0:  0000005c fffffffe 00000030 00000002
Backtrace:
=>0 0x7ee62fdd MSVCRT_memset+0x58() in msvcrt (0x04cae858)
  1 0x6db4891b in libcrypto-10 (+0x891a) (0x03c1907c)
0x7ee62fdd MSVCRT_memset+0x58 in msvcrt: repe stosl	%es:(%edi)
Modules:
Module	Address			Debug info	Name (35 modules)
PE	  400000- 23a3000	Deferred        john
PE	63800000-638f3000	Deferred        libgomp-1
PE	64b40000-64b55000	Deferred        libwinpthread-1
PE	65280000-6529c000	Deferred        zlib1
PE	69ec0000-69ed8000	Deferred        libbz2-1
PE	6aec0000-6af2c000	Deferred        libgmp-10
PE	6d0c0000-6d198000	Deferred        libgcc_s_sjlj-1
PE	6db40000-6dcb3000	COFF            libcrypto-10
ELF	7b400000-7b7f9000	Deferred        kernel32<elf>
  \-PE	7b410000-7b7f9000	\               kernel32
ELF	7bc00000-7bd24000	Deferred        ntdll<elf>
  \-PE	7bc30000-7bd24000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7e9c5000-7e9ea000	Deferred        imm32<elf>
  \-PE	7e9d0000-7e9ea000	\               imm32
ELF	7e9ea000-7ea27000	Deferred        ws2_32<elf>
  \-PE	7e9f0000-7ea27000	\               ws2_32
ELF	7ea27000-7ea42000	Deferred        version<elf>
  \-PE	7ea30000-7ea42000	\               version
ELF	7ea42000-7ec35000	Deferred        user32<elf>
  \-PE	7ea50000-7ec35000	\               user32
ELF	7ec35000-7ed6a000	Deferred        gdi32<elf>
  \-PE	7ec40000-7ed6a000	\               gdi32
ELF	7ed6a000-7ede9000	Deferred        advapi32<elf>
  \-PE	7ed80000-7ede9000	\               advapi32
ELF	7ede9000-7eeaa000	Dwarf           msvcrt<elf>
  \-PE	7ee00000-7eeaa000	\               msvcrt
ELF	7eeaa000-7eebe000	Deferred        libnss_files.so.2
ELF	7eebe000-7f000000	Deferred        libm.so.6
ELF	f7bc5000-f7bca000	Deferred        libdl.so.2
ELF	f7bca000-f7d8b000	Deferred        libc.so.6
ELF	f7d8b000-f7daa000	Deferred        libpthread.so.0
ELF	f7daa000-f7f7a000	Dwarf           libwine.so.1
ELF	f7f8d000-f7fb7000	Deferred        ld-linux.so.2
ELF	f7fba000-f7fbc000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
0000000c services.exe
	00000053    0
	0000000e    0
	0000000d    0
00000051 winedevice.exe
	00000055    0
	00000054    0
	00000052    0
0000009b (D) Z:\home\JtR\project\run\john.exe
	[Z:\home\JtR\project\run\john.exe --test-full=0]
	0000009e    0
	0000009d    0 <==
	0000009c    0
000000a1 explorer.exe
	000000a4    0
	000000a3    0
	000000a2    0
System information:
    Wine build: wine-2.20 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 4.15.0-1027-aws
Exited with code 5
```

**Comment by solardiz** [comment]
@claudioandre-br Those segfaults shouldn't be happening with that change. This indicates there's another bug... or maybe you inadvertently dropped the keyword `for`?

**Comment by solardiz** [comment]
@claudioandre-br Also, can you post the specific compiler errors you were getting, corresponding to what you describe in:

```
 * - gcc 9 refuses to compile the code as it is.
 * - gcc 6 and 7 (at least) refuse to compile the patched/updated code.
```

Maybe this will enable me or someone else to suggest a better fix. Thanks!

**Comment by claudioandre-br** [comment]
> @claudioandre-br Those segfaults shouldn't be happening with that change. This indicates there's another bug

My first thought.

> ... or maybe you inadvertently dropped the keyword for?

No. https://github.com/claudioandre-br/JohnTheRipper/commit/269004c1ee69a3dd1e969c5721a8284c66820431
*******
* gcc 9
sunmd5_fmt_plug.c:819:5: error: 'constant_phrase' not specified in enclosing 'parallel'
  819 |     MD5_Update(&px->context, (unsigned char *) constant_phrase, constant_phrase_size);

* gcc 6 says you can't specify blablabla.

**Pull request merged**
