### PR TITLE
Fix AVX512BW detection

### LINKED ISSUE #3888: AVX512BW detection is buggy
This works as expected:
``` 
./configure # OR ./configure CPPFLAGS='-mavx512bw'
[...]
Target CPU ................................. x86_64 AVX512BW, 64-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. linux-gnu
Cross compiling ............................ no
Legacy arch header ......................... x86-64.h
```

But this fails:
```
./configure --disable-native-tests CPPFLAGS='-mavx512bw'
[...]
checking for MMX... yes
checking for SSE2... yes
checking for SSSE3... yes
checking for SSE4.1... yes
checking for SSE4.2... yes
checking for AVX... yes
checking for XOP... no
checking for AVX2... yes
checking for AVX512F... yes
checking for AVX512BW... no
[...]
Target CPU ................................. x86_64 AVX512F, 64-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. linux-gnu
Cross compiling ............................ no
Legacy arch header ......................... x86-64.h
```

```
configure:11595: checking for AVX512BW
configure:11607: gcc -o conftest -m64 -g -O2 -I/usr/local/include   -O0 -mavx512bw -I/usr/local/include -m64  -L/usr/local/lib -L/usr/local/lib64 -L/usr/lib64 -L/lib64 conftest.c  >&5
conftest.c: In function 'main':
conftest.c:30:9: error: can't convert a vector of type '__m512i' {aka '__vector(8) long long int'} to type 'int' which has different size
         int main(){__m512i t, t1;*((long long*)&t)=1;t1=t;t=_mm512_slli_epi16(t1,t);if((*(long long*)&t)==88)printf(".");exit(0);}
         ^~~
configure:11607: $? = 1
configure: failed program was:
```

### PR DESCRIPTION
**Pull request by claudioandre-br**
Closes #3888

### CODE REVIEW

**Comment by claudioandre-br** [comment]
It works as it is now. Anyway: 
* the if is not necessary, we are testing only the compilation process;
* we can't run the binary (it is for a cross build);
* but, if we do, the result will be 0x2000...

**Comment by solardiz** [comment]
>     * we can't run the binary (it is for a cross build)

Is this really only for a cross build? What do we use to detect AVX512BW support by the hardware when we build on a machine actually supporting this instruction set? I'm confused.

**Comment by claudioandre-br** [comment]
For non cross is JtR `CPU_detect()`

**Comment by solardiz** [comment]
> For non cross is JtR `CPU_detect()`

Ah, yes, IIRC we discussed that on some issue a year or so ago and magnum made the change to reuse the `CPU_detect` code during build. That was a very welcome change.

**Comment by magnumripper** [comment]
Right. Before that, we had two version of almost same tests (like the one now changed). One version tried to build and run it, the other (for cross-compile) just tries to build and link it and if that works, the test passes.

What I don't understand though, is what was wrong with the original version, prior to e3e1f1d0? I did use the correct instruction, then you changed it in e3e1f1d0 and now you changed it back.

**Comment by claudioandre-br** [comment]
It is `_mm512_slli_epi16(vector_type, **scalar_type**)`. What was failing is related to `scalar_type`.

**Comment by magnumripper** [comment]
I see. So much for dry-running code :-)

**Pull request merged**
