### PR TITLE
compiles cleanly with rexgen 1.2.8

### PR DESCRIPTION
**Pull request by teeshop**
Hi Magnum,

some colleagues complained that john doesn't build with rexgen support enabled. Unfortunately, they were right, and it was due to API changes in rexgen. I updated john accordingly, and it seems to be working.

I'm not sure if I understood your callback function correctly. Do you have some test suite for this?

Regards, Jan

### CODE REVIEW

**Comment by frank-dittrich** [comment]
I did apply your changes on top of commit d2c272da520893a39669e432b1ad8e4afb908e99.
Then I built and installed the latest rexgen version (1.2.8)
Then I did
```
$ make -s distclean; ./configure --disable-openmp --enable-asan --enable-ubsan && make -s clean && make -s -j 8 && ../run/john --list=build-info
```
I disabled OpenMP, so that I don't have to deal with threads when running john in gdb.
I enabled ASan (address sanitizer) and UbSan (undefined behavior sanitizer).
Rexgen library was detected automatically, so rexgen support was enabled. 

If you don't already have the test suite installed, please run
```
git clone https://github.com/magnumripper/jtrTestSuite test
```
so that the test suite ends up in the test directory, under the same directory where john's run and src directories are.
Otherwise, cd into the test directory and run a `git pull` to get the latest version.


```
$ cd ../test/ && ./jtrts.pl -stoponerror -q -passthru="--regex='\0'"
```

The './jtrts.pl -stoponerror -q -passthru="--regex='\0'"` is running the self tests with a dummy regex mode (`\0` means, just use the default candidate generated in word list mode).

```
$ ./jtrts.pl -stoponerror -q -passthru="--regex='\0'"
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1802-gd2c272d+ ASan UbSan [linux-gnu 64-bit AVX-ac]
--------------------------------------------------------------------------------
form=dynamic_0                    guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)(-show1502)  [!!!FAILED2!!! ret_val=256 exited, return code 1]
```

Something went wrong here, so repeat the test with more verbose output.

```
$ ./jtrts.pl -stoponerror -v -v -passthru="--regex='\0'"
...
Capabilities in this build of john:
jumbo core inc local_pot_valid regex encode_valid utf8 cp1252 cp1251 koi8r cp437 cp737 cp850 cp858 cp866 iso8859-1 iso8859-15 inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8
Execute john: ../run/john -ses=tst-  --regex='\0' -pot=tst-.pot dynamic_0_tst.in --wordlist=pw.dic -form=dynamic_0 2>&1 >/dev/null


Cmd_data = 
Press 'q' or Ctrl-C to abort, almost any other key for status
ASAN:SIGSEGV
=================================================================
==20802==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f8868714bf4 bp 0x60400000df90 sp 0x7ffdbecb64f0 T0)
    #0 0x7f8868714bf3 in StreamRegexIterator::readNextWord() (/lib64/librexgen.so.1.2+0x13bf3)
    #1 0x7f886871272b in StreamRegex::iterator(IteratorState*) const (/lib64/librexgen.so.1.2+0x1172b)
    #2 0x7f886871153f in RegexAlternatives::iterator(IteratorState*) const (/lib64/librexgen.so.1.2+0x1053f)
    #3 0x7f886871885d in c_regex_iterator (/lib64/librexgen.so.1.2+0x1785d)
    #4 0x84b1c1 in do_regex_hybrid_crack /home/fd/git/JtR/src/regex.c:209
    #5 0x82e568 in do_wordlist_crack /home/fd/git/JtR/src/wordlist.c:1305
    #6 0x7e5286 in john_run /home/fd/git/JtR/src/john.c:1697
    #7 0x7e6092 in main /home/fd/git/JtR/src/john.c:1973
    #8 0x7f88677ed6ff in __libc_start_main (/lib64/libc.so.6+0x206ff)
    #9 0x4065f8 in _start (/home/fd/git/JtR/run/john+0x4065f8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 StreamRegexIterator::readNextWord()
==20802==ABORTING



Execute john: ../run/john -show    -pot=tst-.pot dynamic_0_tst.in -form=dynamic_0 2>/dev/null

d_show_line = 
0 password hashes cracked, 1502 left

form=dynamic_0                    guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)(-show1502)  [!!!FAILED2!!! ret_val=256 exited, return code 1]
Exiting on error. The .pot file tst-.pot contains the found data
The command used to run this test was:

../run/john -ses=tst-  --regex='\0' -pot=tst-.pot dynamic_0_tst.in --wordlist=pw.dic -form=dynamic_0
and
../run/john -show    -pot=tst-.pot dynamic_0_tst.in -form=dynamic_0
```

```
$ gdb ../run/john
...
(gdb) run -ses=tst-  --regex='\0' -pot=tst-.pot dynamic_0_tst.in --wordlist=pw.dic -form=dynamic_0
Starting program: /home/fd/git/JtR/run/john -ses=tst-  --regex='\0' -pot=tst-.pot dynamic_0_tst.in --wordlist=pw.dic -form=dynamic_0
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.21-8.fc22.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Loaded 1500 password hashes with no different salts (dynamic_0 [md5($p) (raw-md5) 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6391bf4 in StreamRegexIterator::readNextWord() () from /lib64/librexgen.so.1.2
Missing separate debuginfos, use: dnf debuginfo-install gmp-6.0.0-9.fc22.x86_64 keyutils-libs-1.5.9-4.fc22.x86_64 krb5-libs-1.13.2-10.fc22.x86_64 libasan-5.3.1-2.fc22.x86_64 libcom_err-1.42.12-4.fc22.x86_64 libgcc-5.3.1-2.fc22.x86_64 libicu-54.1-4.fc22.x86_64 libselinux-2.3-10.fc22.x86_64 libstdc++-5.3.1-2.fc22.x86_64 nss-softokn-freebl-3.21.0-1.1.fc22.x86_64 openssl-libs-1.0.1k-13.fc22.x86_64 pcre-8.37-7.fc22.x86_64 zlib-1.2.8-7.fc22.x86_64
(gdb) bt
#0  0x00007ffff6391bf4 in StreamRegexIterator::readNextWord() () from /lib64/librexgen.so.1.2
#1  0x00007ffff638f72c in StreamRegex::iterator(IteratorState*) const () from /lib64/librexgen.so.1.2
#2  0x00007ffff638e540 in RegexAlternatives::iterator(IteratorState*) const () from /lib64/librexgen.so.1.2
#3  0x00007ffff639585e in c_regex_iterator () from /lib64/librexgen.so.1.2
#4  0x000000000084b1c2 in do_regex_hybrid_crack (db=db@entry=0x1009680 <database>, regex=regex@entry=0x631000014875 "\\0", 
    base_word=base_word@entry=0x7ffffff9dd70 "Skippin\347 an\344*", regex_case=<optimized out>, regex_alpha=<optimized out>) at regex.c:209
#5  0x000000000082e569 in do_wordlist_crack (db=<optimized out>, name=<optimized out>, rules=<optimized out>) at wordlist.c:1305
#6  0x00000000007e5287 in john_run () at john.c:1697
#7  0x00000000007e6093 in main (argc=7, argv=0x7fffffffe038) at john.c:1973
```

**Comment by frank-dittrich** [comment]
Even when rebuilding without ASan or UbSan support, I still get a segfault, even without the test suite:

```
(bleeding-jumbo)run $ ./john --wordlist --regex='[ab]\0' --stdout
Segmentation fault (core dumped)
```

**Comment by frank-dittrich** [comment]
Not even standalone regex mode works:

```
(bleeding-jumbo)run $ ./john --regex='[ab][0-4]' --stdout
Warning: regex mode currently can't be resumed if aborted
./john: symbol lookup error: ./john: undefined symbol: c_simplestring_to_utf8_string
```

**Comment by teeshop** [comment]
It seems that your ./john is linked against an older version of rexgen, which did not yet have c_simplestring_to_utf8_string.

`make install` of rexgen does not run `ldconfig`, which seems to be a best practice (https://bugs.launchpad.net/hidravfx/+bug/1025262). Could you please retry after running `ldconfig`. If this does not help, I'd be interested in the result of `ldd ./john` and `rexgen -v`.

On my system, where john is running, I get the following result:
```
» otool -L ../run/john
../run/john:
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/local/lib/libgmp.10.dylib (compatibility version 13.0.0, current version 13.0.0)
	librexgen.1.2.dylib (compatibility version 1.2.0, current version 1.2.8)
	/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
```

I'm very unhappy with the current way of informing the user that she has to run `ldconfig`. I'm sure nobody reads the output of `make install` ;-) How would you handle the problem of updating the loader cache?

However, I've just seen that rexgen comes as compatibility version 1.2.0, which is not correct, as the api has changed. I'll create a new version and recreate a pull request...

Kind regards, Jan

**Comment by frank-dittrich** [comment]
> It seems that your ./john is linked against an older version of rexgen, 
> which did not yet have c_simplestring_to_utf8_string.

Yes, indeed. there was another, older librexgen version, and the linker found that one first.
Now it is clear why I failed when I tried to address the API change issues several weeks ago.

**Pull request closed without merging**
