### PR TITLE
Shared OpenCL DES code, and use it in DMG-OpenCL

### PR DESCRIPTION
**Pull request by magnumripper**
WIP for #3129. This works on some devices, crashes on others. Apart from some clean-up needed, I'm sure there's some bugs present.

I think we'll get a really nice speed-up once this works as it should. As in 15x or better... @kholia if you test this, try `-cost=-cost=:,1:1` and `-cost=:,2` for benchmarks.

### CODE REVIEW

**Comment by kholia** [comment]
Nice! `mbed TLS` is a good place to get readable implementations :+1:

**Comment by magnumripper** [comment]
```
[magnum@super src]$ ../run/john -test -form:dmg-opencl -cost=:,2
Device 6: GeForce GTX TITAN X
Benchmarking: dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 1000, cost 2 (version) of 2
Raw:	885621 c/s real, 893672 c/s virtual

[magnum@super src]$ ../run/john -test -form:dmg-opencl -cost=:,1:1
Device 6: GeForce GTX TITAN X
Benchmarking: dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL]... OpenCL UNKNOWN OPENCL ERROR (-9999) error in common-opencl.c:1470 - Error creating command queue
```

**Comment by magnumripper** [comment]
> mbed TLS is a good place to get portable and readable implementations

Yes. I tried musl first (as @solardiz suggested) but I haven't yet figured out how to write an EDE3-CBC function with it. I will re-visit that once everything works, and see if it's faster.

**Comment by magnumripper** [comment]
Found the problem. Good boost 😎 
```
[magnum@super src]$ ../run/john -test -form:dmg-opencl -cost=:,2
Device 6: GeForce GTX TITAN X
Benchmarking: dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 1000, cost 2 (version) of 2
Raw:	472615 c/s real, 477203 c/s virtual

[magnum@super src]$ ../run/john -test -form:dmg-opencl -cost=:,1:1
Device 6: GeForce GTX TITAN X
Benchmarking: dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 1000, cost 2 (version) of 1
Raw:	1036K c/s real, 1036K c/s virtual
```

Old figures, running on a single CPU core:
```
[magnum@super src]$ OMP_NUM_THREADS=1 ../run/john -test -form:dmg-opencl -cost=:,2
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Device 6: GeForce GTX TITAN X
Benchmarking: dmg-opencl, Apple DMG [PBKDF2-SHA1 OpenCL 3DES/AES]... DONE
Speed for cost 1 (iteration count) of 1000, cost 2 (version) of 2
Raw:	8623 c/s real, 8623 c/s virtual

[magnum@super src]$ OMP_NUM_THREADS=1 ../run/john -test -form:dmg-opencl -cost=:,1:1
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Device 6: GeForce GTX TITAN X
Benchmarking: dmg-opencl, Apple DMG [PBKDF2-SHA1 OpenCL 3DES/AES]... DONE
Speed for cost 1 (iteration count) of 1000, cost 2 (version) of 1
Raw:	298586 c/s real, 298586 c/s virtual
```
That's, eh, a 54x boost for version 2 with old iteration count of 1000.
```
[magnum@super src]$ GOMP_CPU_AFFINITY=0-31 ../run/john -test -form:dmg-opencl -cost=:,2
Will run 32 OpenMP threads
Device 6: GeForce GTX TITAN X
Benchmarking: dmg-opencl, Apple DMG [PBKDF2-SHA1 OpenCL 3DES/AES]... (32xOMP) DONE
Speed for cost 1 (iteration count) of 1000, cost 2 (version) of 2
Raw:	113777 c/s real, 3939 c/s virtual
```
Even compared to running the old code on 32 CPU cores, there's a 4x boost.

**Comment by kholia** [comment]
@magnumripper You are a magician! Nice work :+1:

**Pull request merged**
