### PR TITLE
OpenCL support for Ethereum presale wallets

### PR DESCRIPTION
**Pull request by kholia**
I wonder how much difference will OpenMP make.

@magnumripper Do you prefer `unsigned char *` over `unsigned char*` formatting when doing type-casting?

My BTC address is `17GCX8uht258YMssByJqXzcsK6YVVRCHNs`. Thanks for supporting the development! :-)

### CODE REVIEW

**Comment by kholia** [comment]
OpenMP makes good difference for this format. 313 Kc/s increases to 401 Kc/s with OpenMP on GeForce GTX TITAN X.

**Comment by magnumripper** [comment]
> @magnumripper Do you prefer `unsigned char *` over `unsigned char*` formatting when doing type-casting?

I prefer `(unsigned char*)keys` over `(unsigned char *) keys`. In most other situations I dislike dropping spaces (our code style says to write `a * b + c` and not `a*b+c`) but casted lines tend to be very long.

What I really despise is writing pointers as multiplications. I can live with `foo_t *bar` or `foo_t* bar` but I can't stand `foo_t * bar`.

**Comment by kholia** [comment]
@magnumripper This PR is all set for a review, thanks!

**Comment by FredericHeem** [comment]
Would it be possible to add the AES decryption in GPU too? See the branch https://github.com/FredericHeem/JohnTheRipper/tree/ethereum-presale-opencl for a work in progress. I've started this work without knowing you were already working on it.
Next step would be to implement Keccak on the GPU, but is it worth it?

**Comment by kholia** [comment]
AFAIK the encrypted data size can be around 600 bytes or greater. Would it be reasonable to transfer this amount of data to-and-from the GPU? I don't know. Feel free to experiment, and send a PR.

**Comment by kholia** [comment]
@FredericHeem

I am unable to compile the code in your `ethereum-presale-opencl` branch. I am using GCC 4.4 on RHEL 6.6. While running `make` I see,

```
opencl_ethereum_presale_fmt_plug.c:61: error: expected specifier-qualifier-list before ‘bool’
opencl_ethereum_presale_fmt_plug.c:304: error: ‘seed_t’ has no member named ‘cracked’
```

Have you tested and benchmarked your code? What speeds are you getting? Do you have a Ethereum hash with a long (600+ bytes) `encseed` for measuring the speed accurately?

**Comment by FredericHeem** [comment]
The code has been compiled on macosx and Ubuntu 16.04. Bear in mind that this branch is really mac giver style code and there is room for improvement.
I am still waiting for a GPU to be delivered for a proper benchmark. 
Right now, it's around 800pw/sec on a modest MacBook pro 2011 CPU only.
What's the rate you can get with your graphics card?

**Comment by FredericHeem** [comment]
The ubuntu 16.04 has gcc version 5.4.0 and seems to support the bool native type.

**Comment by FredericHeem** [comment]
The branch has been updated to add `#include <stdbool.h>`
Do you mind to give a try?

**Comment by kholia** [comment]
While running `./run/john --test --format=ethereum-presale` I now get,

```
Build log: ptxas application ptx input, line 33999; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors

Error -42 building kernel $JOHN/kernels/ethereum_presale_kernel.cl. DEVICE_INFO=262162
OpenCL CL_INVALID_BINARY error in common-opencl.c:1096 - clBuildProgram failed.
```

It seems that OpenCL kernel fails to build with the NVIDIA OpenCL compiler.

I am trying to pull changes from your branch to my branch. Stay tuned!

**Comment by kholia** [comment]
@FredericHeem The PBKDF2 call in this format requires the salt to be the same as the password. I am unable to see how you manage this part in your code. Can you please point out the relevant parts of your code which handle this?

**Comment by FredericHeem** [comment]
`./john --test --format=ethereum-presale` is working fine on my machine (no GPU) and is able to decrypt a known test wallet with "password" as password:
```
ethwallet.json:$ethereum-presale$w*0b2fa2c63a8b5603e1104fbada15a609aa9736ed41db1678d91a9b1a1f7c1628e711dbc250c4c289b06b0faa56cd499dc4af9daf878202db22cc61df1a91c918314c77ce92e5c8b1265580edd79a852acf40fe2138653ac16524c08247381d9802cf5ef3f8c4baf69fb869f2b7fb796bae853cfbdc3c5b788a14e75f39e0cf7df2e90779181a5dd45cce8e8df938af3c6b6c8a92ce123338e6ed87eb16ff11a02cd4a2a07aff8a3a57097fcf137501e07a941a7ce9bc19498252d98769125fbd2c9a14f1c56212a6bf2a7e374474c60e7a3a1cf443ce8194c4c960474472d6ca761ada075169fa8c7017bf1274b99df898deb65f51ed8eb29fbc0997d69c9800ad9b8351155bec5d8e7f73e7e2882a6e1b62883d0158c44fed8e4412fb18e75757e1355aaadd8a2dab50ae40c800d032dc77d3e84904085d628b5a13b60317d6f12ede26b7b38e7c6805bea1d2e11e3a7d7153b76ebfd99ae2536dfdd071ff8111a86fbd63e7b17155162263ef45471ac5b4c517520572cd19410cc4cbde77914fad12326fe5a4cbd5fc4a297740d6b5e64001196b0531e2464b7e4cee77136a38844b94dc59a9a72eec3ff49bca3d5bf0c29652ee6ff028e22f8936aac58fa3cf05ce4c8de8883204e43b57e4ebed922ad7b3a8953042033d34d7e94bc8ff393d1df4c8b062f5228b4f9dbc5d157af96772af1ef2c84f6562049b1c44f0359c07f193623a8b0f1b7e34b31481ddf54a24128e5a21b929f57fd07f8911ad8eb8d8bfe928ae9dfa2d35663764161094552a43b43a0a43dca687d4d04b79c8dbb2d4f87b7d8e0805a77adddfd5149741faa594009639fb730dccfbee1f99286aaf94052c06a1c68efc29dcd57a8b1a421e*f9438b7121a15fd127ec0d8a72ee2b3e8da04a5a*74fdb879ece341dd590a769f2cd39d6717aac4bd87b0e5c82084dd65a40750b4
```

Unfortunately, I cannot reproduce your error.

**Comment by FredericHeem** [comment]
The change https://github.com/FredericHeem/JohnTheRipper/commit/952b533e2f577e38b73417c9d65ef1d42d9253f9 has been pushed and eventually solves this issue.

**Comment by kholia** [comment]
It seems that moving AES decryption to GPU is not beneficial for this format.

AES on CPU,

```
$ git checkout PresaleWalletGPU  # code from this PR
$ ./configure; make
$ OMP_NUM_THREADS=16 ../run/john --test --format=ethereum-presale-opencl
Will run 16 OpenMP threads
Device 6: GeForce GTX TITAN X
Benchmarking: ethereum-presale-opencl, Ethereum Presale Wallet [PBKDF2-SHA256 OpenCL AES]... (16xOMP) DONE
Speed for cost 1 (iteration count) of 2000
Raw:	405504 c/s real, 266778 c/s virtual
```

AES on GPU,

```
$ git checkout PresaleWalletGPUv2  # with AES decryption on GPU
$ ./configure; make
$ OMP_NUM_THREADS=16 ../run/john --test --format=ethereum-presale-opencl
Will run 16 OpenMP threads
Device 6: GeForce GTX TITAN X
Benchmarking: ethereum-presale-opencl, Ethereum Presale Wallet [PBKDF2-SHA256 OpenCL AES]... (16xOMP) DONE
Speed for cost 1 (iteration count) of 2000
Raw:	364990 c/s real, 249081 c/s virtual
```
OMP_NUM_THREADS=4 results also favor the `PresaleWalletGPU` branch which does AES on the CPU.

**Comment by FredericHeem** [comment]
Thanks a lot, i'm glad i can rid of my branch and use yours.
However, `ethereum2john.py` seems to have an issue when writing the bkp for a real world presale wallet which has an encoded seed length of 1248, here is a test wallet with the same length:

```
{"encseed": "0b2fa2c63a8b5603e1104fbada15a609aa9736ed41db1678d91a9b1a1f7c1628e711dbc250c4c289b06b0faa56cd499dc4af9daf878202db22cc61df1a91c918314c77ce92e5c8b1265580edd79a852acf40fe2138653ac16524c08247381d9802cf5ef3f8c4baf69fb869f2b7fb796bae853cfbdc3c5b788a14e75f39e0cf7df2e90779181a5dd45cce8e8df938af3c6b6c8a92ce123338e6ed87eb16ff11a02cd4a2a07aff8a3a57097fcf137501e07a941a7ce9bc19498252d98769125fbd2c9a14f1c56212a6bf2a7e374474c60e7a3a1cf443ce8194c4c960474472d6ca761ada075169fa8c7017bf1274b99df898deb65f51ed8eb29fbc0997d69c9800ad9b8351155bec5d8e7f73e7e2882a6e1b62883d0158c44fed8e4412fb18e75757e1355aaadd8a2dab50ae40c800d032dc77d3e84904085d628b5a13b60317d6f12ede26b7b38e7c6805bea1d2e11e3a7d7153b76ebfd99ae2536dfdd071ff8111a86fbd63e7b17155162263ef45471ac5b4c517520572cd19410cc4cbde77914fad12326fe5a4cbd5fc4a297740d6b5e64001196b0531e2464b7e4cee77136a38844b94dc59a9a72eec3ff49bca3d5bf0c29652ee6ff028e22f8936aac58fa3cf05ce4c8de8883204e43b57e4ebed922ad7b3a8953042033d34d7e94bc8ff393d1df4c8b062f5228b4f9dbc5d157af96772af1ef2c84f6562049b1c44f0359c07f193623a8b0f1b7e34b31481ddf54a24128e5a21b929f57fd07f8911ad8eb8d8bfe928ae9dfa2d35663764161094552a43b43a0a43dca687d4d04b79c8dbb2d4f87b7d8e0805a77adddfd5149741faa594009639fb730dccfbee1f99286aaf94052c06a1c68efc29dcd57a8b1a421e", "ethaddr": "f9438b7121a15fd127ec0d8a72ee2b3e8da04a5a", "bkp": "74fdb879ece341dd590a769f2cd39d6717aac4bd87b0e5c82084dd65a40750b4", "email": "pippo@gmail.com", "btcaddr": "1DcQxkURtPhtX1wH3DVkdz75UD4RdoefqG"}
```

```
./ethereum2john.py ethwallet.json 
ethwallet.json:$ethereum$w*0b2fa2c63a8b5603e1104fbada15a609aa9736ed41db1678d91a9b1a1f7c1628e711dbc250c4c289b06b0faa56cd499dc4af9daf878202db22cc61df1a91c918314c77ce92e5c8b1265580edd79a852acf40fe2138653ac16524c08247381d9802cf5ef3f8c4baf69fb869f2b7fb796bae853cfbdc3c5b788a14e75f39e0cf7df2e90779181a5dd45cce8e8df938af3c6b6c8a92ce123338e6ed87eb16ff11a02cd4a2a07aff8a3a57097fcf137501e07a941a7ce9bc19498252d98769125fbd2c9a14f1c56212a6bf2a7e374474c60e7a3a1cf443ce8194c4c960474472d6ca761ada075169fa8c7017bf1274b99df898deb65f51ed8eb29fbc0997d69c9800ad9b8351155bec5d8e7f73e7e2882a6e1b62883d0158c44fed8e4412fb18e75757e1355aaadd8a2dab50ae40c800d032dc77d3e84904085d628b5a13b60317d6f12ede26b7b38e7c6805bea1d2e11e3a7d7153b76ebfd99ae2536dfdd071ff8111a86fbd63e7b17155162263ef45471ac5b4c517520572cd19410cc4cbde77914fad12326fe5a4cbd5fc4a297740d6b5e64001196b0531e2464b7e4cee77136a38844b94dc59a9a72eec3ff49bca3d5bf0c29652ee6ff028e22f8936aac58fa3cf05ce4c8de8883204e43b57e4ebed922ad7b3a8953042033d34d7e94bc8ff393d1df4c8b062f5228b4f9dbc5d157af96772af1ef2c84f6562049b1c44f0359c07f193623a8b0f1b7e34b31481ddf54a24128e5a21b929f57fd07f8911ad8eb8d8bfe928ae9dfa2d35663764161094552a43b43a0a43dca687d4d04b79c8dbb2d4f87b7d8e0805a77adddfd5149741faa594009639fb730dccfbee1f99286aaf94052c06a1c68efc29dcd57a8b1a421e*f9438b7121a15fd127ec0d8a72ee2b3e8da04a5a*74fdb879ece341dd590a769f2cd39d67
```

The resulting bkp is chopped.

**Comment by kholia** [comment]
The `bkp` chopping is intentional. 16 bytes of `bkp` are enough for cracking.

What is the password for this presale wallet? I would like to add it as a test vector.

**Comment by kholia** [comment]
@FredericHeem Some questions,

1. Do you know which software generated this presale wallet? https://github.com/ethereum/pyethsaletool uses a 16 byte `bkp`.

2. Is Keccak-256 being used for generating this `bkp` value?

3. Can current JtR crack this presale wallet?

**Comment by kholia** [comment]
The password for your presale wallet seems to be `password`. I just cracked it using JtR ;)

**Comment by FredericHeem** [comment]
`pyethsaletool`  does not generate the same kind of wallet, first of all, it doesn't output the bkp field, then the length of the encoded seed is much smaller.
Thanks to this article https://www.reddit.com/r/ethereum/comments/5ees2q/is_the_bkp_component_of_a_presale_json_file_a/ , i found out about the bkp: https://github.com/tagawa/website/blob/master/pyethtool/pyethtool.py#L61
`pyethsaletool`  has been modified locally to add the bkp and set the correct input seed length to get a 1248 encoded seed length. 

The current JtR doesn't recognize the hash because of the bkp size. 
Indeed, the presale wallet given is a test wallet with password as password.

**Comment by FredericHeem** [comment]
Actually, it works fine, sorry for the noise, the current JtR just rejects the bkp in the original size.

**Comment by kholia** [comment]
Thanks for confirming that things are working well now 👍

**Comment by magnumripper** [comment]
> It seems that moving AES decryption to GPU is not beneficial for this format.

Then something is likely wrong. 600 bytes is nothing and it's just 600 bytes per *salt*. You obviously have to make that transfer in `set_salt()` and not `crypt_all()`... did you?

Also, our AES code can be tweaked to use local memory or not.

**Comment by kholia** [comment]
@magnumripper There is 600 (to 1024) bytes per salt which doesn't impact speed much but there is also 1024 bytes of decrypted data per key which is the speed killer.

https://github.com/kholia/JohnTheRipper/commits/PresaleWalletGPUv2 (top commit) has the AES-decryption-on-GPU code.

**Comment by magnumripper** [comment]
OK so that can only be avoided with Keccak on GPU?

Anyway I'd like this code to be merged. Perhaps you can include it but only optionally use it, eg. `#if GPU_AES`. I might be able to tweak it. If nothing else, we really should add a `opencl_keccak.h` with GPU-side Keccak - that would mean we don't have to transfer it. Perhaps hashcat has a good kernel to nick.

**Comment by magnumripper** [comment]
Also please note that I consider a boost (or just same numbers) compared to CPU-side *not running OMP* a definite win, even if CPU-side AES is faster at 4 threads.

**Comment by kholia** [comment]
Yes, the transfer of 1024 bytes of decrypted data per key can be avoided by having Keccak on the GPU.

I am looking at the following options (for writing `opencl_keccak.h`),

* https://github.com/coruus/keccak-tiny/blob/singlefile/keccak-tiny.c (seems easy to port to OpenCL, has various modes and delimiter can be specified as well)

* https://github.com/dave-andersen/fastrie/blob/master/xptMiner/opencl/keccak.cl (unknown license, unknown mode and unknown delimiter value)

Note: AES-on-CPU code is faster than AES-on-GPU code even for OMP_NUM_THREADS=1.

**Comment by kholia** [comment]
@magnumripper https://github.com/kholia/JohnTheRipper/tree/PresaleWalletGPUv3 (top commit) moves AES decryption + Keccak to the GPU. Weirdly enough, there is a slight speed decrease compared to the AES-on-CPU code. Can you please double-check my code to see if I am doing something wrong?

**Comment by FredericHeem** [comment]
Here is my naïve question, what if we merge `pbkdf2_sha256_loop` and `ethereum_presale_process` so no data needs to go back and forth from CPU to GPU ?

**Comment by kholia** [comment]
I don't think that any GPU <--> host data transfers happen between `pbkdf2_sha256_loop` and `ethereum_presale_process` operations. I don't see any `clEnqueueReadBuffer` / `clEnqueueWriteBuffer` calls between those two operations.

**Comment by kholia** [comment]
Update:

AES on CPU,

```
$ OMP_NUM_THREADS=1 ../run/john --test --format=ethereum-presale-opencl  # AES on CPU
Device 6: GeForce GTX TITAN X
Benchmarking: ethereum-presale-opencl, Ethereum Presale Wallet ...
Speed for cost 1 (iteration count) of 2000
Raw:	313223 c/s real, 310182 c/s virtual
```
This increases to `409600 c/s` for OMP_NUM_THREADS=16.


AES + Keccak on GPU,

```
$ OMP_NUM_THREADS=1 ../run/john --test --format=ethereum-presale-opencl
Device 6: GeForce GTX TITAN X
Benchmarking: ethereum-presale-opencl, Ethereum Presale Wallet ...
Speed for cost 1 (iteration count) of 2000
Raw:	385505 c/s real, 385505 c/s virtual
```

There is a decent speed increase for OMP_NUM_THREADS=1 compared to AES-on-CPU code. I will open a PR shortly.

**Comment by FredericHeem** [comment]
By the way, the performance test is using a short encoded seed or a real world seed ?

**Comment by kholia** [comment]
@FredericHeem I believe that the real-world `encseed` is being used for bechmarking.

**Comment by magnumripper** [comment]
Hopefully I can optimize the code a little for GPU at some point in time. One problem is that all current GPUs are 32-bit. Manual optimizing can do wonders.

**Comment by FredericHeem** [comment]
The latest code is now compiling and running fine on a Nvidia 1080 TI, when running in test mode,
 it computes around 800k/sec, when running with a 10GB files, it runs around 600k-650k/sec.
 
However, on a MacbookPro 2017, it fails to run and here is error:
```
../run/john --test --format=ethereum-presale-opencl
Device 2: AMD Radeon Pro 560 Compute Engine
Benchmarking: ethereum-presale-opencl, Ethereum Presale Wallet [PBKDF2-SHA256 AES OpenCL]... 

Build log: In file included from <program source>:14:
/Users/fredericheem/JohnTheRipper/run/kernels/opencl_sha2.h:589:2: warning: implicit declaration of function 'amd_bitalign' is invalid in C99
        SHA512(A, B, C, D, E, F, G, H, W)
 ^
/Users/fredericheem/JohnTheRipper/run/kernels/opencl_sha2.h:379:2: note: expanded from macro 'SHA512'
        ROUND512_A(A,B,C,D,E,F,G,H,K[0],W[0]) \
 ^
/Users/fredericheem/JohnTheRipper/run/kernels/opencl_sha2.h:366:26: note: expanded from macro 'ROUND512_A'
        t = (ki) + (wi) + (h) + Sigma1_64(e) + Ch((e), (f), (g)); \
                         ^
/Users/fredericheem/JohnTheRipper/run/kernels/opencl_sha2.h:352:24: note: expanded from macro 'Sigma1_64'
#define Sigma1_64(x) ((ror64(x,14))  ^ (ror64(x,18)) ^ (ror64(x,41)))
                       ^
/Users/fredericheem/JohnTheRipper/run/kernels/opencl_sha2.h:341:16: note: expanded from macro 'ror64'
         ((n) < 32 ? (amd_bitalign((uint)((x) >> 32), (uint)(x), (uint)(n)) | ((ulong)amd_bitalign((uint)(x), (uint)((x) >> 32), (uint)(n)) << 32)) : (amd_bitalign((uint)(x), (uint)((x) >> 32), (uint)(n) - 32) | ((ulong)amd_bitalign((uint)((x) >> 32), (uint)(x), (uint)(n) - 32) << 32))) : \
               ^
<program source>:329:13: warning: incompatible pointer types passing 'uint [8]' to parameter of type 'uint8_t *' (aka 'unsigned char *')
        keccak_256(hash, 16, seed, seed_length + 1);
            ^~~~
/Users/fredericheem/JohnTheRipper/run/kernels/opencl_keccak.h:171:1: note: passing argument to parameter 'out' here
defkeccak(256)
^
/Users/fredericheem/JohnTheRipper/run/kernels/opencl_keccak.h:166:38: note: expanded from macro 'defkeccak'
  inline void keccak_##bits(uint8_t* out, uint outlen,            \
                                     ^

FAILED (cmp_all(1))

```

**Comment by magnumripper** [comment]
@FredericHeem does fd16a37f help?

**Comment by FredericHeem** [comment]
Thanks a lot, this issue is now gone, however, another error occurred:
```
 $ ../run/john --test --format=ethereum-presale-opencl
Device 2: AMD Radeon Pro 560 Compute Engine
Benchmarking: ethereum-presale-opencl, Ethereum Presale Wallet [PBKDF2-SHA256 AES OpenCL]... 
FAILED (cmp_all(1))

```

**Comment by kholia** [comment]
I think macOS and Intel Linux OpenCL runtimes are known to be problematic.

On Linux with Intel OpenCL runtime, this format fails with,

```
$ ../run/john --test --device=0 --format=ethereum-presale-opencl
Device 0: Intel(R) HD Graphics Skylake ULT GT2
Benchmarking: ethereum-presale-opencl, Ethereum Presale Wallet... 
FAILED (cmp_all(6144))
```

However lot of formats do work with the same OpenCL runtime.

```
$ ../run/john --test --device=0 --format=electrum-modern-opencl
Device 0: Intel(R) HD Graphics Skylake ULT GT2
Benchmarking: electrum-modern-opencl, Electrum Wallet 2.8+...
Raw:	2021 c/s real, 3011 c/s virtual
```

Maybe some OpenCL runtime platform specific hacks are required?

**Pull request merged**
