### PR TITLE
md5crypt-opencl: only detect divergence in 64 lid's near current

### PR DESCRIPTION
**Pull request by solardiz**
This speeds up the check when LWS is greater than 64 _and_ it avoids unnecessary disabling of length specialization when there are different length passwords somewhere within the local group, but not in the immediate group of 64.

### CODE REVIEW

**Comment by solardiz** [comment]
Mysteriously, the increase of `length` array size from 0x100 to 0x400 elements that I included here has resulted in a 9% speedup on well's Tahiti at length 8 (from 3909K to 4267K on a test I just ran), even though it tunes to LWS=64 anyway (so the rest of the changes are no-op for this case). I was able to isolate the speedup to just this one change by making edits to just this one digit in the kernel - yes, this is what causes the change.

**Comment by magnumripper** [comment]
My favorite 4x boost was b755050c

**Comment by solardiz** [comment]
That one with RC4 actually makes sense to me - it looks like bank conflict avoidance.

**Comment by magnumripper** [comment]
Absolutely. But how would you know, other than trial and error? Things like that should ideally be taken care of by the toolchain.

**Pull request merged**
