### PR TITLE
MainProcess forward sigint/sigterm to children.

### PR DESCRIPTION
**Pull request by math07**
When I started doing the --fork option on Johnny, it seems to me that John only kills its children when ascii code 3 ( CTRL-c) or 'q'. is pushed on the keyboard, not with signals. I looked at the code in "signal.c" of JtR and it seems to be consistent with my tests. So now when main process receive sigterm/sigint, I forward it to its children.

If you want more details, here are the most important messages on the list where Shinnok, Frank and me talked about it:
http://www.openwall.com/lists/john-dev/2015/04/28/16
http://www.openwall.com/lists/john-dev/2015/04/30/4
http://www.openwall.com/lists/john-dev/2015/04/30/5
http://www.openwall.com/lists/john-dev/2015/04/30/6

I tested it but I'm not a john pro yet so I'm not sure to know if placing the forwarding at that place doesn't have unwished behaviour. So I'll take your comments.

### CODE REVIEW

**Comment by magnumripper** [comment]
Thanks, I see no obvious problem with this but I'll think it over for a while.

**Comment by magnumripper** [comment]
Oh, but we can't merge stuff to the master branch here. That branch is merely a one-way mirror of Solar's CVS repo for convenience. We need Solar to apply the patch to core and commit it to CVS.

I could apply it to bleeding-jumbo though. But if Solar is willing to add this to core that's much better, and it'd be merged to jumbo.

**Comment by math07** [comment]
Update : it has now been fixed in CVS.

**Comment by magnumripper** [comment]
OK, will merge when I get the time.

**Comment by magnumripper** [comment]
Done

**Comment by magnumripper** [comment]
> Done

It seems I forgot to push it to GitHub %-). But NOW it's done.

**Comment by math07** [comment]
Thanks :)

**Pull request closed without merging**
