### PR TITLE
Use OS X support in Travis CI

### PR DESCRIPTION
**Pull request by kholia**
This PR enables building of JtR on OS X. The building and testing on OS X completes in under 8 minutes, it seems.

This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2454.

### CODE REVIEW

**Comment by kholia** [comment]
I can try enabling OpenCL testing too but would it be usable or will it have too many failing formats? Stay tuned.

**Comment by magnumripper** [comment]
As long as you test with a CPU device (which I presume will happen anyway), all or nearly all OpenCL formats should work fine. And this will work around our current problem with testing on Ubuntu w/ fglrx.

**Comment by kholia** [comment]
I have enabled testing of OpenCL formats in the latest commit. The total building + testing time is around 14 minutes now.

**Comment by magnumripper** [comment]
And all 54 OpenCL formats (that aren't disabled) passed - good stuff!

**Pull request merged**
