### PR TITLE
OpenCL: self test using sane GWS and LWS

### PR DESCRIPTION
**Pull request by claudioandre-br**
See #3516

### CODE REVIEW

**Comment by claudioandre-br** [comment]
This only affects a self test of a cracking session.

What will happen is:
* LWS=0 GWS=0 `?a` `reset` for tuning 
* LWS=x GWS=y `?a?a` `reset` for re-tuning (it is up to autotune code to retune or use x and y)
* LWS=x GWS=y `?a?a?a` `reset` for re-tuning (it is up to autotune code to retune or use x and y)

Are telling me I have to set LWS=0 GWS=0 to force a re-tune?

**Comment by magnumripper** [comment]
I was just afraid you kept the auto-tuned values for first length and re-used it.

I'm thinking if `-lws` and `-gws` are supplied (by variables or options) they should always be used (except possibly for self-test, which could still use get_sane_defaults or whatever it's called). If LWS/GWS are *not* supplied, we need to re-autotune any time `reset()` is called.

Now, `reset()` could obviously recognize that nothing's changed and just give the same values again without re-tuning and that would be perfectly fine **but** it's much better if we can instead ensure it's not called in the first place! In this case it's mask.c that should never call `reset()` unless actually needed, but I think it sometimes does. It's fairly tricky to know whether internal things changed or not IIRC.

**Comment by claudioandre-br** [comment]
Now I get it. The PR is wrong.

**Comment by claudioandre-br** [comment]
I'm still looking for a solution. But, the idea is [what in a remove past was `if (db == NULL)`]:

```
if (_self_testing)
    get_small_sane_lws_gws_values() // Never self test using GWS=4M
    create_buffers() 
else
    tune(db)
```

**Comment by magnumripper** [comment]
6ea7946f09 added a global `autotune_real_db` variable. If it's true, the db sent with `opencl_init_auto_setup()` was a real db and not a test db. However, this may still happen during a self-test call, so it mostly just tell us this is not a `--test` session.

We also have recently reviewed and now correct variables `self_test_running`, `benchmark_running` and `bench_or_test_running`.

My problem when I last looked at this (for nt-opencl) was that even using all the above it wasn't quite always possible to know whether to use `small_sane` or perform an autotune. I can't remember why and I'll look at it later.

**Comment by claudioandre-br** [comment]
I'm looking at `self_test_running` and `benchmark_running` now. They look very promising.

**Comment by magnumripper** [comment]
Here's a good debug line to place at top of `reset()` for ensuring things are what we think they are:
```c
	fprintf(stderr, "%s(), %s, %s\n", __FUNCTION__,
	        (db && db->real && db->real == db) ? "real db" : "test db",
	        self_test_running ? "self-test" :
	        benchmark_running ? "benchmark" : "real crack session");
```

**This is fine:**
$ ../run/john -test -form:nt-opencl
Device 2: AMD Radeon Pro 560 Compute Engine
Benchmarking: NT-opencl [MD4 OpenCL]... **reset(), test db, self-test**
DONE
Note: This format may also be benchmarked using --mask (see doc/MASK).
Raw:	28504K c/s real, 48131K c/s virtual

**This too is fine:**
$ ../run/john scraped.sam -form:nt-opencl -w
Device 2: AMD Radeon Pro 560 Compute Engine
Using default input encoding: UTF-8
Loaded 5294 password hashes with no different salts (NT-opencl [MD4 OpenCL])
Remaining 3470 password hashes with no different salts
**reset(), test db, self-test**
Note: This format may be a lot faster with --mask acceleration (see doc/MASK).
**reset(), real db, real crack session**
Local worksize (LWS) 256, global worksize (GWS) 32768 (128 blocks)
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:01 DONE (2018-12-17 00:31) 0g/s 2175p/s 2175c/s 7548KC/s 123456..sss
Session completed

**This has one superflous reset() but I believe we do that according to format interface spec. However, we should not re-tune the second time because nothing changed. But it looks we are.**
$ ../run/john scraped.sam -form:nt-opencl -w -skip
Device 2: AMD Radeon Pro 560 Compute Engine
Using default input encoding: UTF-8
Loaded 5294 password hashes with no different salts (NT-opencl [MD4 OpenCL])
Remaining 3470 password hashes with no different salts
**reset(), real db, real crack session**
Local worksize (LWS) 256, global worksize (GWS) 32768 (128 blocks)
Note: This format may be a lot faster with --mask acceleration (see doc/MASK).
**reset(), real db, real crack session**
Local worksize (LWS) 256, global worksize (GWS) 65536 (256 blocks)
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:00 DONE (2018-12-17 00:31) 0g/s 8865p/s 8865c/s 30761KC/s 123456..sss
Session completed

**I need to debug the last session's double resets for length 0:**
$ ../run/john scraped.sam -form:nt-opencl -mask=?a -max-len=4 -v:4
Device 2: AMD Radeon Pro 560 Compute Engine
Using default input encoding: UTF-8
Loaded 5294 password hashes with no different salts (NT-opencl [MD4 OpenCL])
Remaining 3470 password hashes with no different salts
**reset(), test db, self-test**
Local worksize (LWS) 64, global worksize (GWS) 768 (12 blocks)
**reset(), real db, real crack session** <-- length 0
**Internal mask not utilized (target: 1024)** <-- length 0
**Internal mask not utilized (target: 1024)** <-- length 0 again?
Local worksize (LWS) 256, global worksize (GWS) 32768 (128 blocks)
Press 'q' or Ctrl-C to abort, almost any other key for status
**reset(), real db, real crack session** <-- length 1
**Internal mask, multiplier: 95 (target: 1024)** <-- length 1
Local worksize (LWS) 256, global worksize (GWS) 131072 (512 blocks)
0g 0:00:00:01  (1) 0g/s 0p/s 0c/s 0C/s
0g 0:00:00:01 1.04% (2) (ETA: 00:35:43) 0g/s 75.39p/s 75.39c/s 261626C/s aa..aa
0g 0:00:00:01 1.05% (3) (ETA: 00:35:42) 0g/s 7181p/s 7181c/s 24918KC/s aaa..aaa
0g 0:00:00:01 1.06% (4) (ETA: 00:35:41) 0g/s 682279p/s 682279c/s 2367MC/s aaaa..aaaa
0g 0:00:00:01 N/A 0g/s 61430Kp/s 61430Kc/s 285640MC/s #u3:..#u3:
Session completed

**Comment by magnumripper** [comment]
Anyway the problem is in mask.c and I'll look at it.

**Comment by claudioandre-br** [comment]
The PR now:
* use sane LWS and GWS for self testing;
* skip tune during the 1st `reset()` if `--skip-self-test`;

Both are `reset()` responsability.

**Pull request merged**
