### PR TITLE
Notes on testing JtR on big endian systems

### PR DESCRIPTION
**Pull request by kholia**
The plan is to expand this file with more development, and testing tips in the near future.

### CODE REVIEW

**Comment by jfoug** [comment]
Other than Pomelo (and you showed mscash which does not fail for me), I think all BE and align-required bugs have been addressed (for now).

Yes, having an open issue is good.  It is something I have been doing every 6 months to a year (going through and correcting BE / alignment issues introduced).

We really need to find some way to CI this.  I had a fake CI running (daily builds on my BE box), but that has upgraded, lost my rights, lots the working install of git, and I will be off of this job in 2 months, so it is a mute point anyway.     So, we still need some way to CI on a be system.

Does anyone know if there is any form of ICE/emulator which will run 'giving' us a BE system ?

**Comment by kholia** [comment]
> Does anyone know if there is any form of ICE/emulator which will run 'giving' us a BE system ?

https://github.com/kholia/JohnTheRipper/blob/HACKING/doc/HACKING.md

I am running the emulated VM as described here :-)

**Comment by jfoug** [comment]
Oh, here is a real joy, for the Rpi3:    http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0500d/CHDCGHEA.html    It lists that the cpu works for both BE and LE memory models.  Wtf!  :)

**Comment by jfoug** [comment]
yes, but the build on the emulator you listed was ppc64le  (NOTE the LE).  That means yes, you are emulating the ppc64 instructions. BUT it is on LE memory access.

**Comment by jfoug** [comment]
@kholia do a configure on that VM, and post the bottom summary. I am pretty sure you are NOT getting BE memory model, but I could be wrong.

Yes, the GCC compile farm is an option.  I have not applied for an account, but may at some time.

**Comment by kholia** [comment]
@jfoug It is a BE system. I am actually running, and testing stuff on it.

**Comment by solardiz** [comment]
Jim, I think it was Claudio who mentioned a ppc64le system (no idea if it was emulated or real), not Dhiru.

**Comment by jfoug** [comment]
Ah, I just remember seeing the qeme and the ppc64le   I guess it is not this system.

@kholia What performance do you get with this?   I do not expect a full 'usable' system, but if it is not 100% neutered, it would not be bad.   I will work down the rasberry pi route also.  Mine (i have 3 of them) are in a box in the drawer of my desk (I have not run them in about a year).  I was using them for some PEN testing a while back. They are wonderful tools for that.  The infrastructure manager was shocked at the amount of information I provided him, by simply setting a pi up in the ceiling tiles in a downstairs bathroom for 48 hours, doing a graybox test.  Even a blackbox test showed a LOT of information.  There were many changes implemented based upon results of that, and they were shocked that the entire setup could be gotten over the internet for under $50.  Very eye opening.

But I will see if I can possibly setup a BE CI environment using one of these little gems.

**Comment by jfoug** [comment]
Sounds like rpi3 is LE (can do be).  Some have tried to build a BE kernel and toolchain, but to no avail.  Looks like the boot loader has to set things up, and it sounds like that might be closed source. 

So I will look at the GCC farm stuff at some point.

**Comment by kholia** [comment]
The QEMU emulated PPC64 VM is pretty usable I would say. Do give it a try. If you run into any problems, I am here to help :-)

**Comment by kholia** [comment]
Information about the emulated PPC64 VM,

```
$ cat /proc/cpuinfo 
processor	: 0
cpu		: POWER8 (architected), altivec supported
clock		: 1000.000000MHz
revision	: 2.1 (pvr 004b 0201)

processor	: 1
cpu		: POWER8 (architected), altivec supported
clock		: 1000.000000MHz
revision	: 2.1 (pvr 004b 0201)
```

```
$ cat whoami.c  # from http://cs-fundamentals.com
/* 
   Write a C program to find out if the underlying 
   architecture is little endian or big endian. 
 */
 
#include <stdio.h>
int main ()
{
  unsigned int x = 0x76543210;
  char *c = (char*) &x;
 
  printf ("*c is: 0x%x\n", *c);
  if (*c == 0x10)
  {
    printf ("Underlying architecture is little endian. \n");
  }
  else
  {
     printf ("Underlying architecture is big endian. \n");
  }
 
  return 0;
}
```

```
$ gcc whoami.c 

$ ./a.out 
*c is: 0x76
Underlying architecture is big endian
```

**Comment by jfoug** [comment]
Try this command
```sh
echo -n I | od -to2 | head -n1 | cut -f2 -d" " | cut -c6 
```

It will return 1 for LE and 0 for BE  :)

**Comment by kholia** [comment]
Neat :)

```
$ echo -n I | od -to2 | head -n1 | cut -f2 -d" " | cut -c6 
0
```

**Comment by jfoug** [comment]
This one is even 'better'  :)

```sh
if [ `echo -n I | od -to2 | head -n1 | cut -f2 -d" " | cut -c6` = "1" ] ; then echo LE ; else echo BE ; fi
```

Same command but now will list LE or BE ;)

**Comment by kholia** [comment]
Heh.

I am not sure if the SMP stuff is really working though. On a quad-core host, I do see 400% CPU utilization when the VM is compiling stuff.

**Comment by solardiz** [comment]
Jim, you could also try the $100 EdgeRouter Lite like we had been briefly using a while ago, which is dual-core mips64. It's BE at least when running FreeBSD: http://rtfm.net/FreeBSD/ERL/ http://www.daemonology.net/blog/2016-01-10-FreeBSD-EdgeRouter-Lite.html

**Comment by kholia** [comment]
What could possible go wrong? Merging!

**Pull request merged**
