### PR TITLE
docs: add guidelines for contributing

### PR DESCRIPTION
**Pull request by claudioandre**
I'm not 100% sure, but it seems that if we add this file (its content can be improved, I know) the issue window will have a better/clearer header text.

### CODE REVIEW

**Comment by magnumripper** [comment]
So will the same text show when opening a PR? In that case we should mention licensing and code-style.

**Comment by claudioandre** [comment]
IF I get it right, GitHub will update some pages with exactly these texts.

Issues
```
Want to submit an issue to magnumripper/JohnTheRipper?
If you have a bug or an idea, read the contributing guidelines before opening an issue.
```
And this for MR
```
First time contributing to magnumripper/JohnTheRipper?
If you know how to fix an issue, consider opening a pull request for it.
You can read this repository’s contributing guidelines to learn how to open a good pull request.
```

**Comment by magnumripper** [comment]
Found it here https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by magnumripper** [comment]
Perhaps we should drop the issue template in favor of this thing.

**Comment by claudioandre** [comment]
The texts complement each other, or, reinforce each other.

**Comment by claudioandre** [comment]
```
diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
index 84b494f2f..a8c1a7b4b 100644
--- a/CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -7,3 +7,27 @@ When contributing to this repository, please first discuss the change you wish t
 ## Bug Reports
 
 Try to be clear about your environment and what you are doing. If possible, share a sample hash or file that can be used to reproduce.
+
+## Source Code Style
+
+Please refer to `doc/README.coding-style` for information on the subject.
+
+For Jumbo, The maintainer recommends to format code using the following commands:
+```
+$ indent -kr -i4 -ts4 -nlp -nbbo -ncs -l79 -lc79 -bad -il0
+$ astyle --style=kr -t4 -U -H -p -xC79 -c -k3 -z2
+```
+
+## License
+
+John the Ripper is released under GNU GPL v2 "or later", with portions also available under more relaxed terms.
+
+Solar Designer's current preference is that new code contributions be licensed under very liberal terms:
+
+/*
+ * This software is Copyright (c) YEAR YOUR NAME <your at e-mail.address>,
+ * and it is hereby released to the general public under the following terms:
+ * Redistribution and use in source and binary forms, with or without
+ * modification, are permitted.
+ */
+This is a heavily cut-down “BSD license”. You may also include the warranty disclaimer.
```

**Pull request merged**
