### PR TITLE
improved descrypt-ztex

### PR DESCRIPTION
**Pull request by Apingis**
- utilized fpga resources to possible extent (75% LUT)
- 2 on-fpga candidate key generators, 32 cores/fpga
- improved timing of comparator (now using same clock as for pipeline of DES rounds)
- reliably work at 190 MHz (toolset reports 221)
- theoretical performance is 973 Mc/s, measured 950-960 Mc/s regardless of number of hashes to compare
- current consumption: 2.8A, at idle 0.4A

### CODE REVIEW

**Comment by solardiz** [comment]
```
device.c: In function 'device_init_fpgas':
device.c:125:6: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
device.c:134:6: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
device.c:211:7: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
```

I guess for reasons unrelated to this PR's changes, but rather to our const'ification elsewhere in the tree. Yet this needs to be fixed, ideally _not_ by cast'ing the const away but rather by adding some const's to this file as well.

**Comment by solardiz** [comment]
@magnumripper Looks like we have an integer overflow in computing C/s? -

```
$ ./john -form=descrypt-ztex -mask='?a?a?a?a?a?a?a?a' pw-fake-unix
[...]
Loaded 3269 password hashes with 2243 different salts (descrypt-ztex, traditional crypt(3) [DES ZTEX])
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:02  0g/s 0p/s 4938Mc/s 9223372TC/s aaaaaaaa
0g 0:00:00:42  0g/s 0p/s 3919Mc/s 3513665TC/s ###aaaaa
```

That's running on 4 ZTEX boards.

**Comment by solardiz** [comment]
Looks like a mask of 5 lowercase letters is somehow insufficient, provides only 1/4 of the speed:

```
$ ./john -form=descrypt-ztex -mask='tes?l?l?l?l?l' pw-fake-unix
Warning! Section [list.ztex:devices] overridden by john-local.conf
ZTEX 3 bus:2 dev:3 Frequency:190 190 190 190 
ZTEX 1 bus:2 dev:4 Frequency:190 190 190 190 
ZTEX 4 bus:2 dev:5 Frequency:190 190 190 190 
ZTEX 2 bus:2 dev:2 Frequency:190 190 190 190 
Using default input encoding: UTF-8
Loaded 3269 password hashes with 2243 different salts (descrypt-ztex, traditional crypt(3) [DES ZTEX])
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 26 candidates left, minimum 7040 needed for performance.
0g 0:00:00:02  0g/s 0p/s 935938Kc/s 1378MC/s tesaaaaa..tesaaaqa
0g 0:00:00:07  0g/s 0p/s 991246Kc/s 1408MC/s tesaaaaa..tesaaaqa
0g 0:00:00:14  0g/s 0p/s 990397Kc/s 1431MC/s tesaaaaa..tesaaaqa
testtest         (u2781-des)
1g 0:00:00:19  0.05232g/s 0p/s 989906Kc/s 1428MC/s tesaaaaa..tesaaaqa
1g 0:00:00:25  0.03982g/s 0p/s 989956Kc/s 1448MC/s tesaaaaa..tesaaaqa
1g 0:00:00:27  0.03690g/s 438427p/s 987034Kc/s 1438MC/s tes####a..-----
Warning: passwords printed above might be partial
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

**Comment by solardiz** [comment]
I'm often getting these errors right after the "Loaded" line.

```
SN 4 FPGA #2 error: pkt_comm_status=0x01, debug=0x0002
SN 4 error -1 doing r/w of FPGAs (LIBUSB_ERROR_IO)
```

Re-running the command makes them go away. I suspect this is related to what state the FPGAs are left in by the previous session. Maybe a bug that could be fixed.

**Comment by solardiz** [comment]
Puzzling, the overflow is triggered even with 1 hash:

```
$ ./john -form=descrypt-ztex -mask='?l?l?l?l?l?l?l?l' -u=u2781-des pw-fake-unix 
Warning! Section [list.ztex:devices] overridden by john-local.conf
ZTEX 3 bus:2 dev:3 Frequency:190 190 190 190 
ZTEX 1 bus:2 dev:4 Frequency:190 190 190 190 
ZTEX 4 bus:2 dev:5 Frequency:190 190 190 190 
ZTEX 2 bus:2 dev:2 Frequency:190 190 190 190 
Using default input encoding: UTF-8
Loaded 1 password hash (descrypt-ztex, traditional crypt(3) [DES ZTEX])
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:01 3.08% (ETA: 15:44:38) 0g/s 6434Mp/s 6434Mc/s 18446744TC/s aaaaufva
0g 0:00:00:05 9.24% (ETA: 15:44:59) 0g/s 3860Mp/s 3860Mc/s 3689348TC/s aaaakyci
0g 0:00:00:09 16.95% (ETA: 15:44:58) 0g/s 3932Mp/s 3932Mc/s 4099276TC/s aaaayucn
0g 0:00:00:15 27.73% (ETA: 15:44:59) 0g/s 3860Mp/s 3860Mc/s 3689348TC/s aaaawdrs
testtest         (u2781-des)
1g 0:00:00:17 DONE (2019-03-28 15:44) 0.05630g/s 3974Mp/s 3974Mc/s 4340410TC/s testtest
```

**Comment by solardiz** [comment]
Cracked exactly the expected 2197 all-lowercase length 1 to 7 passwords in ~40 minutes on 4 boards:

```
$ fgrep -e -des: pw-fake-unix | cut -d: -f5 | egrep '^[a-z]{1,7}$' | wc -l
2197
$ ./john -show -form=descrypt pw-fake-unix | fgrep -ve -bigcrypt | fgrep : | cut -d: -f2 | wc -l
2197
$ fgrep -e -des: pw-fake-unix | cut -d: -f5 | egrep '^[a-z]{1,7}$' | sort -u | md5sum
722c5a6114318d95b2e37dec418439b8  -
$ ./john -show -form=descrypt pw-fake-unix | fgrep -ve -bigcrypt | fgrep : | cut -d: -f2 | sort -u | md5sum
722c5a6114318d95b2e37dec418439b8  -
```

The command was:

```
./john -form=descrypt-ztex -mask='?l' -min-len=1 -max-len=8 pw-fake-unix
```

and I ran the above checks just when it was about to start length 8.

**Comment by solardiz** [comment]
This works around the overflow, but perhaps @Apingis should adjust the code so that `crypt_all` keeps its updated `*count` and return value within the allowed range. Right now, it returns negative values.

Would limiting it to 2^31-1 hashes per call hurt performance?

```diff
index e8c485c..7d6a90f 100644
--- a/src/cracker.c
+++ b/src/cracker.c
@@ -863,7 +863,7 @@ static int crk_password_loop(struct db_salt *salt)
        match = crk_methods.crypt_all(&count, salt);
        crk_last_key = count;
 
-       status_update_crypts((uint64_t)salt->count * count, count);
+       status_update_crypts((uint64_t)salt->count * (unsigned int)count, count);
 
        if (!match)
                return 0;
```

**Comment by solardiz** [comment]
Alternatively, we may change the formats interface to use `unsigned int` or even `uint64_t` there, but I'm not comfortable making that change now. @magnumripper What do you prefer we do?

**Comment by solardiz** [comment]
The warnings are trivially fixed with:

```diff
index 33dacae..cb22f3d 100644
--- a/src/ztex/device.c
+++ b/src/ztex/device.c
@@ -41,7 +41,7 @@ static int hex_digit2bin(char digit)
 
 // Convert hexadecimal ascii string e.g. \x0c\x00 into binary string
 // TODO: consider moving into src/config.c
-static char *hex_string2bin(char *src, int *len)
+static char *hex_string2bin(const char *src, int *len)
 {
        static char dst[CONFIG_MAX_LEN];
 
@@ -121,7 +121,7 @@ static int device_init_fpgas(struct device *device,
        char default_config1[CONFIG_MAX_LEN], board_config1[CONFIG_MAX_LEN];
        int len_default, len_board, len;
 
-       char *ptr;
+       const char *ptr;
        ptr = cfg_get_param(CFG_SECTION, bitstream->label, "Config1");
        if (ptr) {
                char *hex_str = hex_string2bin(ptr, &len_default);
```

**Comment by solardiz** [comment]
Letting `crypt_all` return negative `*count` also results in negative `crk_last_key` and probably breaks the logic in `crk_get_key2`. Fixing this all to work with unsigned types, and re-testing it all, is probably too much to do now. So @Apingis please suggest if you can reasonably limit your code to 2^31-1 or not. Thanks!

**Comment by Apingis** [comment]
> ```
> SN 4 FPGA #2 error: pkt_comm_status=0x01, debug=0x0002
> SN 4 error -1 doing r/w of FPGAs (LIBUSB_ERROR_IO)
> ```
> Re-running the command makes them go away. I suspect this is related to what state the FPGAs are left in by the previous session. Maybe a bug that could be fixed.
> 
> Edit: also occasionally getting these for the same board & FPGA during cracking. So apparently it's just a weaker FPGA for this clock rate.

It resets all FPGAs with GSR after startup, resetting its state. Memory (e.g. hash storages in comparators) is not reset but it's initialized after the GSR.
It think that's some glitch because of hardware or overclocking.

**Comment by solardiz** [comment]
Tested 200 MHz. 3 FPGAs across 2 boards give occasional timeouts, out of 16 FPGAs total. It's a pity our current formats interface is synchronous, not letting us efficiently run different FPGAs at different clock rates. Anyway, this run cracked exactly the expected 464 passwords in slightly over an hour, at an average speed slightly higher (despite of the occasional timeouts and resets of 2 boards) than what it'd be at 190 MHz:

```
$ ./john -form=descrypt-ztex -inc=lower -min-len=7 -max-len=7 -mask='?w?l?l?l?l' pw-fake-unix
Warning! Section [list.ztex:devices] overridden by john-local.conf
ZTEX 1 bus:2 dev:84 Frequency:200 200 200 200
ZTEX 4 bus:2 dev:85 Frequency:200 200 200 200
ZTEX 2 bus:2 dev:83 Frequency:200 200 200 200
ZTEX 3 bus:2 dev:86 Frequency:200 200 200 200
Using default input encoding: UTF-8
Loaded 3269 password hashes with 2243 different salts (descrypt-ztex, traditional crypt(3) [DES ZTEX])
[...]
120g 0:00:09:13  0.2167g/s 0p/s 4054Mc/s 5730MC/s benaaaa
[...]
461g 0:00:57:11 40.05% (ETA: 21:09:19) 0.1343g/s 937485p/s 3957Mc/s 5655MC/s ykzaaaa
Warning: Only 3497 candidates left, minimum 7040 needed for performance.
awesome          (u539-des)
SN 4 FPGA #2 error: pkt_comm_status=0x20, debug=0x0002
SN 4 error -1 doing r/w of FPGAs (LIBUSB_ERROR_IO)
Found 1 device(s) ZTEX 1.15y
SN: 4 productId: 10.15.0.0 "inouttraffic JtR 1.8.x" busnum:2 devnum:85
SN 4 FPGA #0 error: pkt_comm_status=0x01, debug=0x0002
SN 4 error -1 doing r/w of FPGAs (LIBUSB_ERROR_IO)
462g 0:01:01:50 DONE (2019-03-28 19:48) 0.1245g/s 1734Kp/s 3955Mc/s 5639MC/s qnbaaaa..qnbarny
Found 1 device(s) ZTEX 1.15y
SN: 4 productId: 10.15.0.0 "inouttraffic JtR 1.8.x" busnum:2 devnum:85
SN 3 FPGA #0 fpga_select_setup_io() error: -99
SN 3 error -99 doing r/w of FPGAs (LIBUSB_ERROR_OTHER)
SN 4 FPGA #2 error: pkt_comm_status=0x20, debug=0x0002
SN 4 error -1 doing r/w of FPGAs (LIBUSB_ERROR_IO)
Found 1 device(s) ZTEX 1.15y
SN: 4 productId: 10.15.0.0 "inouttraffic JtR 1.8.x" busnum:2 devnum:85
SN 4 FPGA #0 error: pkt_comm_status=0x01, debug=0x0002
SN 4 error -1 doing r/w of FPGAs (LIBUSB_ERROR_IO)
tequila          (u2775-des)
Found 1 device(s) ZTEX 1.15y
SN: 4 productId: 10.15.0.0 "inouttraffic JtR 1.8.x" busnum:2 devnum:85
463g 0:01:03:04 DONE (2019-03-28 19:49) 0.1223g/s 1700Kp/s 3934Mc/s 5603MC/s qnbaaaa..qnbarny
463g 0:01:03:38 DONE (2019-03-28 19:50) 0.1212g/s 1685Kp/s 3926Mc/s 5591MC/s qnbaaaa..qnbarny
463g 0:01:03:58 DONE (2019-03-28 19:50) 0.1206g/s 1676Kp/s 3921Mc/s 5584MC/s qnbaaaa..qnbarny
Found 1 device(s) ZTEX 1.15y
SN: 3 productId: 10.15.0.0 "inouttraffic JtR 1.8.x" busnum:2 devnum:41
SN 3 FPGA #0 fpga_select_setup_io() error: -4
SN 3 error -4 doing r/w of FPGAs (LIBUSB_ERROR_NO_DEVICE)
463g 0:01:04:25 DONE (2019-03-28 19:50) 0.1197g/s 1664Kp/s 3916Mc/s 5577MC/s qnbaaaa..qnbarny
Found 1 device(s) ZTEX 1.15y
SN: 3 productId: 10.15.0.0 "inouttraffic JtR 1.8.x" busnum:2 devnum:42
463g 0:01:04:34 DONE (2019-03-28 19:51) 0.1194g/s 1660Kp/s 3915Mc/s 5577MC/s qnbaaaa..qnbarny
463g 0:01:04:40 DONE (2019-03-28 19:51) 0.1193g/s 1658Kp/s 3915Mc/s 5577MC/s qnbaaaa..qnbarny
iforget          (u2181-des)
464g 0:01:05:09 DONE (2019-03-28 19:51) 0.1186g/s 1646Kp/s 3915Mc/s 5575MC/s qnbaaaa..qnbarny
464g 0:01:05:43 DONE (2019-03-28 19:52) 0.1176g/s 1631Kp/s 3916Mc/s 5577MC/s jxzvdom..qnbarny
464g 0:01:05:55 DONE (2019-03-28 19:52) 0.1172g/s 1626Kp/s 3916Mc/s 5577MC/s qnbaaaa..qnbarny
464g 0:01:12:22 N/A 0.1068g/s 1849Kp/s 3922Mc/s 5573MC/s qnb####..-----
Warning: passwords printed above might be partial
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

The 120g line showing 4054Mc/s is before the first device timeout. And the average speed, including timeouts and the non-full final buffer, is 3922Mc/s. This is slightly higher than the theoretical maximum for 190 MHz.

**Comment by Apingis** [comment]
> please suggest if you can reasonably limit your code to 2^31-1 or not. Thanks!

I'm adding the limit. It will affect descrypt-ztex with 3+ boards, reducing ```keys_per_crypt```. Currently there's a setting 800 Mc / crypt_all() per board.

**Comment by solardiz** [comment]
BTW, parsing of the below with numbered devices (not original SNs) works fine:

```
[ZTEX:descrypt]
Frequency = 200
Frequency_3_0 = 190
Frequency_4_0 = 190
Frequency_4_2 = 190
```

giving this:

```
ZTEX 1 bus:2 dev:53 Frequency:200 200 200 200
ZTEX 3 bus:2 dev:52 Frequency:190 200 200 200
ZTEX 4 bus:2 dev:54 Frequency:190 200 190 200
ZTEX 2 bus:2 dev:51 Frequency:200 200 200 200
```

Unfortunately, but as expected, the resulting c/s rate is the same as running all FPGAs at 190 MHz. To partially get around that, I'd have to run multiple sessions using two groups of two boards.

BTW, @magnumripper @Apingis, isn't it slightly weird that we still number FPGAs from 0, when we've switched to numbering devices from 1?

Also, @magnumripper, there was no warning about me overriding this section, whereas there was one was the "list" section. Are we printing such warnings for "list" sections only? Maybe extend that to all sections? I mean things like "Warning! Section [list.ztex:devices] overridden by john-local.conf"

**Comment by solardiz** [comment]
@Apingis How much slowdown do you expect at 4 boards (as I understand, limiting them to ~500M candidates each)?

**Comment by Apingis** [comment]
Individual FPGA on the board are numbered starting from 0 in Ztex SDK (docs, java libraries, maintenance utilities). I see no problems to start numbering from 1.

> How much slowdown do you expect at 4 boards (as I understand, limiting them to ~500M candidates each)?

Not much, I think 1% or less. There'll be more substantial decrease on 10+ boards as keys per crypt_all() reduces and communication overhead increases.

**Comment by solardiz** [comment]
FPGA numbers 1 to 4 are printed (silk screened) on the boards themselves. So switching to that numbering makes sense, if you can do it consistently and quickly enough for our upcoming release.

**Comment by solardiz** [comment]
Tried 210 MHz on 2 lucky boards. Got 4 errors on one of the FPGAs in the 8-minute run, but everything got cracked anyway and the average speed is 1015M c/s per board:

```
$ ./john -form=descrypt-ztex -inc=lower -min-len=7 -max-len=7 -mask='?w?l?l?l?l' pw-fake-len7
Warning! Section [list.ztex:devices] overridden by john-local.conf
ZTEX 1 bus:2 dev:69 Frequency:210 210 210 210
ZTEX 2 bus:2 dev:61 Frequency:210 210 210 210
Using default input encoding: UTF-8
Loaded 464 password hashes with 442 different salts (descrypt-ztex, traditional crypt(3) [DES ZTEX])
[...]
107g 0:00:01:51  0.9579g/s 0p/s 2144Mc/s 2289MC/s benaaaa..benarrm
[...]
Warning: Only 3497 candidates left, minimum 3520 needed for performance.
awesome          (u539-des)
tequila          (u2775-des)
iforget          (u2181-des)
464g 0:00:08:41 N/A 0.8905g/s 15417Kp/s 2031Mc/s 2108MC/s iforget..xqj####
```

**Comment by Apingis** [comment]
I'll change numbering of individual FPGAs to start from 1 for the new release.

**Comment by solardiz** [comment]
215 MHz on the luckiest board, no errors:

```
$ ./john -form=descrypt-ztex -inc=lower -min-len=7 -max-len=7 -mask='?w?l?l?l?l' pw-fake-len7
Warning! Section [list.ztex:devices] overridden by john-local.conf
ZTEX 2 bus:2 dev:72 Frequency:215 215 215 215
Using default input encoding: UTF-8
Loaded 464 password hashes with 442 different salts (descrypt-ztex, traditional crypt(3) [DES ZTEX])
[...]
59g 0:00:01:23  0.7051g/s 0p/s 1104Mc/s 1191MC/s benaaaa..benaibg
[...]
Warning: Only 1737 candidates left, minimum 1760 needed for performance.
awesome          (u539-des)
tequila          (u2775-des)
464g 0:00:12:19 N/A 0.6270g/s 10869Kp/s 1098Mc/s 1132MC/s tequila..xqj####
```

**Pull request merged**
