### PR TITLE
Introduce AVX-512's ternary logic instructions

### PR DESCRIPTION
**Pull request by zzlei**
and fix some code targeting AVX512 that's never tested

### CODE REVIEW

**Comment by zzlei** [comment]
Oh, this one failed:
```
Testing: dynamic=md5($p) 32/64 x2 (MD5_body) [dynamic_6000]... FAILED (cmp_all(2))
```

What's the proper name of this format? Neither `md5($p)` nor `dynamic_6000` worked.

**Comment by frank-dittrich** [comment]
`--format=dynamic='md5($p)'`

**Comment by zzlei** [comment]
That error is weird. This formats passes self-test both on my laptop (AVX2, emulated CMOV) and on Power (Altivec, native CMOV).

**Comment by zzlei** [comment]
> `Testing: dynamic=md5($p) [128/128 XOP 4x5]... FAILED (cmp_all(4))`

What exactly are the specs of the test machine? I tried a few machines at hand but just couldn't reproduce this error...

**Comment by magnumripper** [comment]
@zzlei that format failed before your commit, it's unrelated! So if it's just that one, we can merge.

The problem is #1751. I am stumped, I have absolutely no idea where to start looking.

**Pull request merged**
