### PR TITLE
BitLocker-OpenCL password length and common tests

### PR DESCRIPTION
**Pull request by e-ago**
- Max password length extended to 27
- Common BitLocker tests used
- Code cleanup

### CODE REVIEW

**Comment by kholia** [comment]
This pull request tries to add 11 commits to bleeding-jumbo. This is not correct.

I am working on cleaning up this PR. I will also add some test vectors to verify that the changes in this PR work correctly.

**Comment by magnumripper** [comment]
> This pull request tries to add 11 commits to bleeding-jumbo. This is not correct.

That alone is no problem, we could just merge with the "squash and merge" option. However, we do have "This branch cannot be rebased due to conflicts" for some reason.

> I am working on cleaning up this PR. I will also add some test vectors to verify that the changes in this PR work correctly.

👍

**Comment by kholia** [comment]
This commit history of `e-ago:bleeding-jumbo` is quite different. It is no wonder that a PR based on that branch has merge conflicts.

**Comment by magnumripper** [comment]
> This commit history of e-ago:bleeding-jumbo is quite different. It is no wonder that a PR based on that branch has merge conflicts.

@e-ago next time please reset your branch so it's same as upstream before you add new commits and make a PR. This is basic git-fu.

**Comment by kholia** [comment]
The equivalent PR https://github.com/magnumripper/JohnTheRipper/pull/2729 has been merged. Hence, I am closing this one.

**Pull request closed without merging**
