### PR TITLE
Fix a typo in iwork format

### PR DESCRIPTION
**Pull request by kholia**
I wonder why this wasn't caught earlier.

### CODE REVIEW

**Comment by magnumripper** [comment]
Yeah that's strange. Maybe --test-full=0 would have catched it? Don't we have a bot doing that test?

**Comment by jfoug** [comment]
I thought all bots were using -test-full=0  Thats a big reason why they are so much slower (especially the CircleCI since it does about 4 or 5 different builds).

**Comment by kholia** [comment]
Yes, multiple builds in CircleCI do "-test-full=0". However, it seems it is not enough to catch problems like this.

```
$ cat CircleCI-MinGW.sh | grep test-full
/usr/bin/wine john.exe --test-full=0
../run/john -test-full=0
../run/john -test-full=0
../run/john -test-full=0
```

I am merging the fix.

**Comment by magnumripper** [comment]
I get it now. This bug will only trigger on systems that has SIMD_PARA_SHA1 to 2 or higher.

**Pull request merged**
