### PR TITLE
ssh format is dead, use ssh-ng format instead

### PR DESCRIPTION
**Pull request by kholia**
This is ready now for merging.

"Fixes" #1941.

### CODE REVIEW

**Comment by magnumripper** [comment]
Shouldn't this wait until the ng format can do everything this one could? Also, I recall the ng format (long ago) had some problems with FP, are those fixed by now?

**Comment by kholia** [comment]
I haven't seen FPs in the ssh-ng format in a long time. We can surely wait but I don't know how long the wait is going to be.

**Comment by magnumripper** [comment]
We don't need to wait for that. But it would be great[tm] if the ng format could do all the original could.

**Comment by kholia** [comment]
It will do all that, and more ;)

I am away for a month or so. Not much might happen during that time.

**Pull request merged**
