### PR TITLE
For sm_5x, vector operators do a better job in OpenCL sha512crypt.

### PR DESCRIPTION
**Pull request by claudioandre**
* Tested on super.

Not a big deal, but good enough.

### CODE REVIEW

**Comment by magnumripper** [comment]
@claudioandre did you see Solar's recent posting on john-dev, about `ror()` on AMD?

**Comment by claudioandre** [comment]
No, I haven't been in john-dev for a while. And, I'm afraid I'm going to have to travel (again) before I can look at it closely.

Please, open an issue if you think this deserves attention.

**Comment by claudioandre** [comment]
Tested (sha256 and sha512): performance gains, #1707, if all processes cracked at least one password, etc.

```
../run/john ~/testhashes -form=sha512crypt-opencl -fork=5  -dev=2,6,7,1,0 --incremental
```

I failed to see if pot reloading is working (and I was afraid to stress super). I'm sure you guys know if JtR quits by itself when using fork and all passwords are cracked.

**Comment by magnumripper** [comment]
Pot sync should take care of it within a minute or so, with current defaults.

**Comment by claudioandre** [comment]
FYI:

```
$ ../run/john ~/testhashes -form=sha512crypt-opencl -fork=5  -dev=2,6,7,1,0 --incremental
Using default input encoding: UTF-8
Loaded 20 password hashes with 20 different salts (sha512crypt-opencl, crypt(3) $6$ [SHA512 OpenCL])
Node numbers 1-5 of 5 (fork)
[...]
```

* All passwords are cracked:
```
5 4g 0:00:06:52  0.009704g/s 2414p/s 7154c/s 7154C/s mylle22..clyatry
1 8g 0:00:07:01  0.01900g/s 27708p/s 50590c/s 50590C/s mitefuke..mudybing
2 2g 0:00:07:08  0.004672g/s 24112p/s 70728c/s 70728C/s GPU:86°C util:99% fan:67% 0by03..rmdrs
3 1g 0:00:06:38  0.002511g/s 0p/s 18437c/s 18437C/s GPU:79°C util:99% fan:56% 123455..sixpr99
4 5g 0:00:06:48  0.01222g/s 6410p/s 25002c/s 25002C/s mlpru1..2bca2u
```

* Main process knows all is done:
```
1 8g 0:00:07:46 DONE (2015-10-12 01:43) 0.01716g/s 29947p/s 50615c/s 50615C/s bh6r5g..jes37s
Waiting for 4 children to terminate
```

* But all other processes are busy 15 minutes later:
```
2 2g 0:00:22:34  0.001476g/s 58114p/s 72843c/s 72843C/s GPU:83°C util:99% fan:54% kh271a3..klrubyo
3 1g 0:00:22:04  0.000754g/s 12118p/s 18696c/s 18696C/s GPU:78°C util:99% fan:54% jasas6..lc3acj
5 4g 0:00:22:19  0.002987g/s 5726p/s 7185c/s 7185C/s sb590..lbgee
4 5g 0:00:22:15  0.003743g/s 19625p/s 25316c/s 25316C/s sw3tng..083hgb
```

It is still running, please, say so if you need more information.

**Comment by claudioandre** [comment]
More than 30 minutes. I pressed q

```
2 2g 0:00:42:59  0.000775g/s 65737p/s 73473c/s 73473C/s GPU:83°C util:99% fan:53% bmh4lp2..bja10ry
5 4g 0:00:42:44  0.001559g/s 6453p/s 7214c/s 7214C/s llc7jrt..l1llta2
4 5g 0:00:42:42  0.001951g/s 22404p/s 25371c/s 25371C/s jletuc4..lilols9
3 1g 0:00:42:44  0.000389g/s 15564p/s 18963c/s 18963C/s GPU:79°C util:84% fan:54% ths129m..kasth6s
Use the "--show" option to display all of the cracked passwords reliably
Session aborted
```

**Comment by magnumripper** [comment]
I'll have a look at it.

**Comment by magnumripper** [comment]
I did some testing but failed to reproduce. With the john.conf "Save" option set to the default 60 seconds, all processes ended within a minute.

I did a little change in 7565191e just to be safe but I can't really see it making much difference.

**Comment by claudioandre** [comment]
It is not a big deal, anyway, process 2 is failing to remove one hash (see below). 

Note
(1) removed 14 hashes - OK
(2) removed 5 hashes. The correct is 6.

```
[...]
crk_reload_pot(1): potsync removed 3 hashes in 0 ms (0 ms finding salts); Remaining 11 hashes with 11 different salts
[...]
crk_reload_pot(1): potsync removed 5 hashes in 0 ms (0 ms finding salts); Remaining 6 hashes with 6 different salts
[...]
crk_reload_pot(1): potsync removed 2 hashes in 0 ms (0 ms finding salts); Remaining 4 hashes with 4 different salts
[...]
crk_reload_pot(2): potsync removed 5 hashes in 0 ms (0 ms finding salts); Remaining 1 hash
crk_reload_pot(2): potsync removed 0 hashes in 0 ms (0 ms finding salts); Remaining 1 hash
[...]
crk_reload_pot(1): potsync removed 4 hashes in 0 ms (0 ms finding salts); No remaining hashes
1 6g 0:00:04:00 DONE (2015-10-12 22:19) 0.02496g/s 7635p/s 59989c/s 59989C/s phx453..ampold2
Waiting for 1 child to terminate
crk_reload_pot(2): potsync removed 0 hashes in 10 ms (0 ms finding salts); Remaining 1 hash

****
1 6g 0:00:03:59  0.02509g/s 6579p/s 59214c/s 59214C/s 0rgsim..phx451
2 14g 0:00:03:55  0.05937g/s 6670p/s 70038c/s 70038C/s GPU:85°C util:99% fan:57% 01j199..249jzn
```

Trying to debug I noticed that the last hash found returns true here:
```if (crk_remove_pot_entry(ciphertext)) ```:

**Comment by claudioandre** [comment]
How should I debub debug crk_remove_pot_entry().

Where I have to put a insightful printf()?

**Comment by magnumripper** [comment]
`crk_remove_pot_entry()` returns true when all hashes are cracked. I guess you only saw it in process 1.

I have a theory: Until some time ago, we locked the pot file while reading. That lead to performance loss so we don't do that anymore. There is a risk now that once in a while the last line read is not complete (someone is writing at the same time we read). That incomplete hash will never be removed unless we add code to back up to the last CR in the file (and process the complete entry next time).

If this is it, you should see it simply by adding `puts(line);` at cracker.c:552 or so.

**Comment by claudioandre** [comment]
I found it. 

* I will create a new issue and submit a patch.

**Comment by magnumripper** [comment]
Awesome, thanks!

**Pull request merged**
