### PR TITLE
Report tunable costs in OpenBSD-SoftRAID format

### PR DESCRIPTION
**Pull request by kholia**
This should fix issue https://github.com/magnumripper/JohnTheRipper/issues/2614.

### CODE REVIEW

**Comment by kholia** [comment]
This should be safe to merge.

**Comment by frank-dittrich** [comment]
For backwards compatibility, the only cost that has been reported in previous versions  should remain the first cost, even if in this case the 2nd tunable cost factor might be more significant. 

Otherwise, restoring old sessions might have unexpected results if --cost was used.

**Comment by solardiz** [comment]
Thanks for commenting, Frank. I think we don't care about backwards compatibility that much here: there hasn't been a numbered jumbo release since these formats were introduced (although it's high time we make one), and as you say the issue would only occur if `--cost` was used.

**Comment by magnumripper** [comment]
That's good to keep in mind though. I think I might have broken that rule-of-thumb once or twice..

**Pull request merged**
