### PR TITLE
Add GPU support for cracking Bitwarden hashes

### PR DESCRIPTION
**Pull request by kholia**
This doesn't work yet, and I can't spot the problem.

@magnumripper Got any tips? :-) Thanks!

### CODE REVIEW

**Comment by kholia** [comment]
Update:

It seems that the OpenCL kernel is not getting the correct `blob` data. How is this happening?

**Comment by kholia** [comment]
Reordering the salt structure to a previous working configuration seems to have fixed the problem.

```
$ ../run/john --test --format=bitwarden-opencl
Device 6: GeForce GTX TITAN X
Benchmarking: bitwarden-opencl, Bitwarden Password Manager ...
Speed for cost 1 (iteration count) of 5000
Warning: "Many salts" test limited: 14/256
Many salts:	165415 c/s real, 165415 c/s virtual
Only one salt:	163840 c/s real, 163840 c/s virtual
```

**Comment by magnumripper** [comment]
To ensure host and GPU sides doesn't pad the struct differently, I guess it should be "sorted" by alignment, like this:
```c
typedef struct {
	union {
		uint64_t qword[32/8];
		uint8_t chr[32];
	} blob;
	uint32_t rounds;
	uint32_t length;
	uint8_t salt[179];
} bitwarden_salt_t;
```

**Comment by magnumripper** [comment]
Oh, but then we also have this
```c
typedef struct {
	salt_t salt; // this MUST match opencl_pbkdf2_hmac_sha256.cl structure!
	union {
		uint64_t qword[32/8];
		uint8_t chr[32];
	} blob;
} salt_t2;
```
This will end up with padding because of the odd length of `uint8_t salt[179];`. Perhaps bump that one to 180 and things should end up a little more rigid against padding problems.

**Comment by jfoug** [comment]
If we bump that to 180, then it has to be done everywhere it is use.  AND we must use defined constant (179) and not a sizeof.  It obviously can be done, just has to be CAREFUL!

Also, the problem here is that we require 8 byte alignment.   NOTE, the padding SHOULD NOT be a problem.  The compiler DOES know wtf to do, when you tell it.    the problem is when you allocate memory and then USE it like a structure. When you do that, you MUST start the alignment to be at least as good as the compiler would do on the stack.    

If the compiler could not handle odd length char buffers (or things like single chars, shorts, etc), and crash due to alignment problems, then you would not use that compiler anyway.

**Comment by magnumripper** [comment]
...and the extended one obviously should reference the original struct, not copy it. We probably do it wrong in some other formats too. This should be safer from future bugs crawling in:
```c
typedef struct {
	// PBKDF2 salt
	salt_t pbkdf2_salt;
	// bitwarden extension
	union {
		uint64_t qword[32/8];
		uint8_t chr[32];
	} blob;
} bitwarden_salt_t;
```

**Comment by jfoug** [comment]
If this really IS a problem, then we should not access the data in structure form (if the 2 compilers padd differently), but instead pass in the values, and then within the kernel marshal the data into a structure known by the kernel (if required).

**Comment by magnumripper** [comment]
> If we bump that to 180, then it has to be done everywhere it is use. AND we must use defined constant (179) and not a sizeof. It obviously can be done, just has to be CAREFUL!

True.

> NOTE, the padding SHOULD NOT be a problem

It becomes a problem when you have the "same" struct on two different systems (ie. the host and the GPU) and they don't pad it the same. We've had similar problems before in OpenCL formats.

> the problem is when you allocate memory and then USE it like a structure. When you do that, you MUST start the alignment to be at least as good as the compiler would do on the stack.

GPU allocations are guaranteed to have an alignment of at least 32 IIRC, so that's not a problem. But it's obviously important to use sizeof(salt_struct) as opposed to some unpadded sum of member sizes.

**Comment by magnumripper** [comment]
If building for a 32-bit CPU, would the compiler align the uint64_t to 4 or 8? I really don't know but since they "emulate" the 64-bit, it shouldn't really need 8. GPUs are currently always 32-bit. Maybe the 64-bit host pads the union to 8 while the GPU pads to 4.

**Comment by magnumripper** [comment]
BTW if we bump 179 to 180, that's still only an aligment of 4. To get 8, we need 184.

**Comment by jfoug** [comment]
If we do bump it, then do it like this:

```c
#define MAX_SHA256_SALT_SIZE 179
#define SHA256_SALT_PADDING 5\
struct x {
   char salt[MAX_SHA256_SALT_SIZE+SHA256_SALT_PADDING];
   uint32_t other_crap;
}

void valid()  {
   if (salt_length(salt) > MAX_SHA256_SALT_SIZE) 
       return 0;
}
```

No sizeof's can be used any more for the struct.salt part.. ALSO, keeping them as 2 defined constants lists why you are making a buffer larger than required


NOTE, I do not know what is the best way to proceed here.  I am a n00b when it comes to the GPU requirements or how the compiler(s) work or do not work.

**Comment by magnumripper** [comment]
More future-proof 😎 
```
#define MAX_SHA256_SALT_SIZE 179
#define SHA256_SALT_PADDING (8 - MAX_SHA256_SALT_SIZE % 8)
```

**Comment by jfoug** [comment]
Yes, I like that better, self adjusting.  However, each time we increase that buffer it will increase by 64 bytes exactly  😎

**Comment by magnumripper** [comment]
> However, each time we increase that buffer it will increase by 64 bytes exactly 😎

Please elaborate. I see an other bug though - it will add 8 even though 0 is needed. To stop that, we'd do
```c
#define SHA256_SALT_PADDING ((MAX_SHA256_SALT_SIZE % 8) ? 8 - MAX_SHA256_SALT_SIZE % 8 : 0)
```

**Comment by jfoug** [comment]
The size is this:

length(salt) + 1 + 4 + 8 == 0 mod(64)    (The 4 is the round count and the 1 and 8 is the standard MD header bytes, the 0x80 and the 8 bytes of bit count)

So length for pbkdf2 the max salt for 1 limb is 51 bytes (for 1 limb), vs 55 bytes for a 1 limb raw-sha256.

Now for 2 limbs, we can process exactly 64 more bytes (51+64 == 115 and this is where we were at).  For 3 limbs it is 115 bytes + 64 more, or 179 bytes.  But this length will always be 13 bytes short of an even 64 byte length, so your formula will 'always' add 5 to get to an even 8 byte offset, and each of the max length we will use will be 13 bytes short of an even 64 byte buffer, or 5 bytes short of an even 8 byte buffer

**Comment by kholia** [comment]
Thanks for looking into this :+1: 

I have made the following changes,

```
diff --git a/src/opencl/bitwarden_kernel.cl b/src/opencl/bitwarden_kernel.cl
index 1d6792a9b..2d46f7f23 100644
--- a/src/opencl/bitwarden_kernel.cl
+++ b/src/opencl/bitwarden_kernel.cl
@@ -18,11 +18,10 @@
  * but some added stuff can be appended to the original salt structure.
  */
 typedef struct {
-       uint32_t rounds;
-       uint8_t salt[179];
-       uint32_t length;
+        // PBKDF2 salt
+       salt_t pbkdf2_salt;
 
-       // appended stuff
+       // bitwarden extension
        union {
                uint64_t qword[32/8];
                uint8_t chr[32];
diff --git a/src/opencl_bitwarden_fmt_plug.c b/src/opencl_bitwarden_fmt_plug.c
index 3d37281cd..15607ab46 100644
--- a/src/opencl_bitwarden_fmt_plug.c
+++ b/src/opencl_bitwarden_fmt_plug.c
@@ -47,6 +47,8 @@ john_register_one(&fmt_opencl_bitwarden);
 
 typedef struct {
        salt_t salt; // this MUST match opencl_pbkdf2_hmac_sha256.cl structure!
+
+       // bitwarden extension
        union {
                uint64_t qword[32/8];
                uint8_t chr[32];
```

The bumping of `179` to `184` can be done in a later PR. I think that it involves changing multiple formats, and requires more rigorous testing.

**Comment by kholia** [comment]
I am merging this for now. I will start working on the "bumping" idea soon.

**Pull request merged**
