### PR TITLE
Enable fuzzing of racf2john using libFuzzer

### PR DESCRIPTION
**Pull request by kholia**
This commit makes racf2john a standalone program.

Related to https://github.com/magnumripper/JohnTheRipper/issues/2674.

### CODE REVIEW

**Comment by frank-dittrich** [comment]
@magnumripper 

Currently, my legacy build focus is on john itself, because several formats should allow longer passwords in legacy generic builds.  (Not sure when I will have time to compare password lengths of legacy generic builds and autoconf builds.)

I ignore build failures in additional tools for now.

**Comment by magnumripper** [comment]
Perhaps we should drop the legacy Makefile now, forcing dists to use autoconf. @solardiz (and any package maintainer happening to read this) what are your thoughts about this?

**Comment by frank-dittrich** [comment]
Let's make a new issue and discuss advantages and disadvantages of dropping/keeping legacy builds.

E.g., I see possibly longer max. password lengths (with a performance penalty) as an advantage of legacy generic builds.

**Comment by kholia** [comment]
I haven't used the legacy Makefile in years. Wasn't the legacy Makefile deprecated a long time ago?

I am OK with doing minimal work to keep it working (being able to build john binary). I don't see the advantage of being able to build the helper utilities with the legacy Makefile.

In my opinion, the legacy Makefile is just holding back progress at this point.

**Comment by frank-dittrich** [comment]
Do we know which distros use legacy build and install jumbo?
(Ubuntu 16.04 installs core john. This installation also adds /etc/cron.d/john which starts /usr/share/john/cronjob as root!)

**Comment by frank-dittrich** [comment]
Checked again, there are just comments in /etc/cron.d/john, no cron job is started.

**Comment by kholia** [comment]
I have added `racf2john` target back to `Makefile.legacy`. Hopefully this PR request can be safely merged now.

**Comment by magnumripper** [comment]
I didn't actually reject it before, I just commented on it. But I'm glad you fixed legacy for now.

**Comment by kholia** [comment]
Thanks 👍 

I am merging this.

**Pull request merged**
