### PR TITLE
Add support for cracking Telegram Desktop passcodes

### LINKED ISSUE #3280: Add support for cracking Telegram Desktop passcodes
Source code,

* https://github.com/telegramdesktop/tdesktop/tree/dev/Telegram/SourceFiles

* https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/storage/localstorage.cpp

* https://github.com/MihaZupan/TelegramDesktopLocalStorage is great!

From hashcat forums (via MihaZupan),

---

One option the client provides is to set a passcode - any string of any length - that is optionally used to encrypt a part of said local storage.

Testing whether the passcode is valid is a multi-step process (shortened for clarity):
1. Read the salt (32 bytes), encrypted data and sha1 of decrypted data from a file.
2. Compute a PKCS5_PBKDF2_HMAC_SHA1 on the UTF8(passcode), using the salt, 4000 iterations, keysize of 256 bytes
3. Use a Telegram-specific KDF to get the AesKey and AesIV (Relatively cheap - bunch of memcpy and 4x sha1)
4. Perform an AES-IGE-DECRYPT on the encrypted data using the derived key and IV from step 3.
5. Compare sha1 of decrypted data with the sha1 read in step 1. If they match - passcode is correct.

---

### PR DESCRIPTION
**Pull request by kholia**
TODO: OpenMP tuning stuff

Speed,

```
$ ../run/john --test --format=telegram  # i3-4005U CPU
Will run 4 OpenMP threads
Benchmarking: telegram [PBKDF2-SHA1 256/256 AVX2 8x AES]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 4000
Warning: "Many salts" test limited: 2/256
Many salts:	867 c/s real, 230 c/s virtual
Only one salt:	898 c/s real, 227 c/s virtual
```

CC @MihaZupan.

This fixes #3280.

### CODE REVIEW

**Comment by kholia** [comment]
@magnumripper Hi! This format needs a PBKFD2 output of length 136. Is our PBKDF-HMAC-SHA1 OpenCL code flexible enough to accommodate this?

**Comment by kholia** [comment]
Initial speed on GPU,

```
$ ../run/john --test --format=telegram-opencl
Will run 32 OpenMP threads
Device 6: GeForce GTX TITAN X
Benchmarking: telegram-opencl [PBKDF2-SHA1 OpenCL AES]... (32xOMP) DONE
Raw:	84020 c/s real, 44481 c/s virtual, GPU util: 99%
```

The above speeds are for a non-pure OpenCL format. We don't have an AES-IGE OpenCL implementation yet.

**Comment by kholia** [comment]
This PR has no GPU stuff.

**Comment by magnumripper** [comment]
LOL, sorry 'bout that

**Pull request merged**
