### PR TITLE
Mute a compiler warning [-Wmacro-redefined]

### PR DESCRIPTION
**Pull request by claudioandre**
I found no reason for a printf re-definition.

### CODE REVIEW

**Comment by claudioandre** [comment]
I probably miss the point. If anyone want to mute the debug message, why there was a rename?
* Was there a rename, right? wpa_printf() -> printf()
* Mute - Isn't easier just to do `#define wpa_printf(...)`?
* Debug - use the real printf `#define wpa_printf    printf`?

**Comment by magnumripper** [comment]
I have no idea why it's written as it is, but we probably want the current behavior where these messages are never shown.

**Comment by magnumripper** [comment]
> we probably want the current behavior where these messages are never shown.

Note that I didn't really look into this, the above is a guess based on the assumption that we decrypt some data with a key derived from a guess, then try to decode it with this ASN.1 code. We're expecting errors (wrong candidate -> random data fed into ASN.1 decoder) so it should silently reject ASAP.

**Comment by claudioandre** [comment]
Ok, but what is wrong with the original/upstream function name `wpa_printf`?
* the new patch, closer to upstream, might make things clear?

**Comment by magnumripper** [comment]
Nothing is wrong with that, we should go that way. Apparently it's been like this since this file was introduced in 063b838e0 - I guess that better notion came later in upstream. White at it, is there any other improvements in upstream?

**Comment by claudioandre** [comment]
> White at it, is there any other improvements in upstream?

I would say there isn't.

**Pull request merged**
