### PR TITLE
CI: test JtR (also) on a fresh environment

### PR DESCRIPTION
**Pull request by claudioandre**
- Addresses #2303 
- I still have to move to CentOS

### CODE REVIEW

**Comment by jfoug** [comment]
I am not sure we need to do a ASAN on clang or not.

**Comment by claudioandre** [comment]
Since JtR tests on gcc and clang, my preference is to do:
- a complete test using both;
- and test against a LTS and a fresh OS (using the 'default' compiler, at least).

**Comment by claudioandre** [comment]
I created a new branch to allow you guys an easier review process. It adds a new OS on CI but:
- without ASAN on clang and;
- without the ability to disable ASAN using the commit message.

https://github.com/magnumripper/JohnTheRipper/compare/bleeding-jumbo...claudioandre:new_approach?expand=1

**Comment by magnumripper** [comment]
Can't merge this as it contains 5fc8e78 too

**Pull request closed without merging**
