### PR TITLE
KRB5 AS-REP OpenCL format: Do everything on GPU and drop OMP.

### PR DESCRIPTION
**Pull request by magnumripper**
Bot test.

### CODE REVIEW

**Comment by magnumripper** [comment]
So it passes all build bots. It also passes on all devices on my Macbook and it works fine on the old Titan - but it fails on Titan X Maxwell (not only on Super but with newer drivers as well). I'll investigate this a bit more.

**Comment by kholia** [comment]
@magnumripper Hi! Have you tried replacing the optimized `memcmp_pmc` function with a simpler memcpy implementation? I wonder if that would make a difference.

**Comment by kholia** [comment]
Debugging patch,

``` diff
diff --git a/src/opencl/krb5_asrep_kernel.cl b/src/opencl/krb5_asrep_kernel.cl
index eb8d1c5..7d3f7d1 100644
--- a/src/opencl/krb5_asrep_kernel.cl
+++ b/src/opencl/krb5_asrep_kernel.cl
@@ -5,6 +5,7 @@
  * modification, are permitted.
  */
 
+#pragma OPENCL EXTENSION cl_amd_printf : enable
 #include "pbkdf2_hmac_sha1_kernel.cl"
 #define AES_CTS_SRC_TYPE MAYBE_CONSTANT
 #define AES_CTS_DST_TYPE __global
@@ -70,7 +71,13 @@ __kernel void asrep_final(MAYBE_CONSTANT asrep_salt *salt,
 
        plaintext += (salt->edata2len + 31) / 32 * 32 * gid;
        memcpy_macro(base_key, ((__global uchar*)pbkdf2[gid].dk), key_size);
-
+       if (gid == 0) {
+               printf("0 -> %02x %02x %02x\n", base_key[0], base_key[1], base_key[2]);
+       }
+       if (gid == 1) {
+               printf("1 -> %02x %02x %02x\n", base_key[0], base_key[1], base_key[2]);
+       }       
+ 
        dk(base_key, base_key, key_size, co_input, 16);
 
        dk(Ke, base_key, key_size, ke_input, 16);
diff --git a/src/opencl_krb5_asrep_aes_fmt_plug.c b/src/opencl_krb5_asrep_aes_fmt_plug.c
index 5219330..378211f 100644
--- a/src/opencl_krb5_asrep_aes_fmt_plug.c
+++ b/src/opencl_krb5_asrep_aes_fmt_plug.c
@@ -55,9 +55,9 @@ static struct fmt_tests tests[] = {
        // AS-REP-with-PA-unsupported-openwall.pcap
        {"$krb5asrep$18$EXAMPLE.COMlulu$b49aa3de9314e2d8daafe323f2e84b9a4ddc361d99bf3bf3a99102f8bff5368bdefc9d7ae090532fdad2a508ac1271bfbd17363b3a1da23bf9db324a24c238634e3ab28d7f4eca009b4c3953c882f5a4206458a
        // luser-18-12345678.pcap
-       {"$krb5asrep$18$EXAMPLE.COMluser$42e34732112be6cec1532177a6c93af5ec3b2fc7da106c004d6d89ddcb4131092aecbead3e9f30d07b593f4c7adc6478ab50b80fee07db3531471f5f1986c8882c45fef784258f9d43195108b83a74f6dcae1b
+       // {"$krb5asrep$18$EXAMPLE.COMluser$42e34732112be6cec1532177a6c93af5ec3b2fc7da106c004d6d89ddcb4131092aecbead3e9f30d07b593f4c7adc6478ab50b80fee07db3531471f5f1986c8882c45fef784258f9d43195108b83a74f6dca
        // hero-17-abcd.pcap
-       {"$krb5asrep$17$EXAMPLE.COMhero$4e7c79214fd330b2e505a4c75e257e4686029136d54f92ce91bb69d5ffc064e64e925b3ae8bc1df431c74ccaf2075cb4a1a32151b0848964e147bf6f8e4a50caa7931faad50433991e016e312c70ad9007e3816
+       // {"$krb5asrep$17$EXAMPLE.COMhero$4e7c79214fd330b2e505a4c75e257e4686029136d54f92ce91bb69d5ffc064e64e925b3ae8bc1df431c74ccaf2075cb4a1a32151b0848964e147bf6f8e4a50caa7931faad50433991e016e312c70ad9007e38
        {NULL}
 };
```

The PBKDF2 output values between `--device=0` and `--device=1` on `super` seem to match up fine. However, the `Ke` values at `gid == 1` seem to be different.

**Comment by magnumripper** [comment]
> Have you tried replacing the optimized memcmp_pmc function with a simpler memcmp implementation?

Note that nearly all such things are normally inlined (even when not macros) and optimized per instance by the run-time. This means, for example, that alignment-branches and more than half of the code path is optimized away! So these functions should end up simple (unless there's a bug in the optimizer 🙄 ).

> The PBKDF2 output values between --device=0 and --device=1 on super seem to match up fine. However, the Ke values at gid == 1 seem to be different.

I too saw `Ke` end up incorrectly and I've also seen `base_key` **changed** after a call to dk where it was merely read. Sometimes the bug moves or hides when I insert debug prints, which is frustrating but also a sign that a barrier at some place(s) may work around the bug.

**Comment by magnumripper** [comment]
Note to self: Super has nvidia 361.28

**Comment by kholia** [comment]
On a Desktop with `NVIDIA 390.25-0ubuntu0~gpu18.04.1` driver,

```
$ ../run/john --test --format=krb5asrep-aes-opencl
Device 0: GeForce GTX 1050 Ti
Benchmarking: krb5asrep-aes-opencl, Kerberos 5 AS-REP etype 17/18 [PBKDF2-SHA1 OpenCL]... FAILED (cmp_all(1))
```

**Comment by kholia** [comment]
> I too saw Ke end up incorrectly and I've also seen base_key changed after a call to dk where it was merely read (and used as const).

Wow :-(. These OpenCL runtimes (drivers? hardware?) are really weird.

**Comment by magnumripper** [comment]
LOL @ this
```
$ ../run/john -test -form:krb5asrep-aes-opencl -force-vector=2
Device 6: GeForce GTX TITAN X
Benchmarking: krb5asrep-aes-opencl, Kerberos 5 AS-REP etype 17/18 [PBKDF2-SHA1 OpenCL 2x]... DONE
Raw:	265686 c/s real, 262144 c/s virtual, GPU util: 99%
```
Note that only the PBKDF2 kernel is running vectorized - the problematic ASREP kernel runs scalar anyway - still, this works around the bug. But we seem to lose 6% of performance.

**Comment by magnumripper** [comment]
Found a workaround: I simply made `base_key` volatile (`#if HAVE_LUT3` for now)
```
$ ../run/john -test -form:krb5asrep-aes-opencl 
Device 6: GeForce GTX TITAN X
Benchmarking: krb5asrep-aes-opencl, Kerberos 5 AS-REP etype 17/18 [PBKDF2-SHA1 OpenCL]... DONE
Raw:	280868 c/s real, 280868 c/s virtual, GPU util: 99%
```

**Comment by magnumripper** [comment]
This was more boost than expected: I just moved one HMAC-SHA1 and a few block of AES from CPU to GPU. That alone was nearly 2x (on single core) and the missed etype 17 optimization was another 2x 😎

**Pull request merged**
