### PR TITLE
Fix a bug in convert to Windows line feeds

### PR DESCRIPTION
**Pull request by claudioandre-br**

### CODE REVIEW

**Comment by solardiz** [comment]
What issue is this fix fixing?

**Comment by magnumripper** [comment]
If nothing else, we recently talked about making subdirectories under doc, I guess this would needed then.

**Comment by claudioandre-br** [comment]
`../doc/*` picks the extra folder and fails in `$(SED) -i -e 's/\r*$$/\r/' ../doc/*`

**Comment by solardiz** [comment]
> subdirectories under doc

Oh, indeed.

**Comment by solardiz** [comment]
The `sed` commands here wrongly have two "$" signs where there should be only one, and are completely non-working for me. I'll probably send a replacement for this entire set of commands after my testing on Linux, and will expect Claudio to retest on Windows (perhaps on CI).

**Comment by claudioandre-br** [comment]
> The sed commands here wrongly have two "$" signs where there should be only one, and are completely non-working for me. I'll probably send a replacement for this entire set of commands after my testing on Linux, and will expect Claudio to retest on Windows (perhaps on CI).

I do not know why I did this for the first time, but this should run on Windows, not Linux. in a PowerShell + CygWin stack.

BTW: I will remove my fork. GitHub CI build status is useless on my PRs.

**Comment by solardiz** [comment]
Yes, the commands are intended to be run on Windows, but I think we should be able to make them generic and usable on different platforms, which I'd find helpful. And the repeated "$" was a bug anyhow, even if it somehow didn't affect the behavior on Windows.

> I will remove my fork. GitHub CI build status is useless on my PRs.

I don't know what you mean by this.

**Comment by solardiz** [comment]
> Why do we do this conversion at all? Most Windows tools understand LF-only as well.

I guess many Windows text file editors and viewers still don't handle LF-only files well. IIRC, even Notepad did not.

**Comment by claudioandre-br** [comment]
>> I will remove my fork. GitHub CI build status is useless on my PRs.

> I don't know what you mean by this.

I can't merge this PR, it is not reading the CIs build status. Since nothing changed recently, I will remove and recreate my GitHub fork. This PR will be closed automatically.

**Comment by claudioandre-br** [comment]
> Yes, the commands are intended to be run on Windows, but I think we should be able to make them generic and usable on different platforms, which I'd find helpful. And the repeated "$" was a bug anyhow, even if it somehow didn't affect the behavior on Windows.

On a second thought, it is possible I was escaping the "$" for PS.

**Comment by solardiz** [comment]
> On a second thought, it is possible I was escaping the "$" for PS.

Makes sense to me, but I guess when you run "make windows-package" under Cygwin those commands will run under bash, no?

**Comment by solardiz** [comment]
Maybe what happened is you tested these command manually in PS, then put them in Makefile and didn't retest that they still did what's expected from them?

**Comment by solardiz** [comment]
> This PR will be closed automatically.

OK, I'll probably make a PR to replace this one, using my version of the commands, and will expect you to review. Works for you?

**Comment by claudioandre-br** [comment]
> > On a second thought, it is possible I was escaping the "$" for PS.
> 
> Makes sense to me, but I guess when you run "make windows-package" under Cygwin those commands will run under bash, no?

No. PS controls CygWin. Probably, I can improve this, but, without a test machine, I won't soon.

**Comment by claudioandre-br** [comment]
Make your PR and I'll test it inside CI.

**Comment by solardiz** [comment]
The commands I am using now (in bash on Linux):
```
rm ../doc/README
find ../doc ../run/rules -type f -exec sed -i -e 's/\r*$/\r/' {} ';'
sed -i -e 's/\r*$/\r/' ../README.md ../run/*.conf ../run/password.lst
find ../doc -type f -not -name '*.txt' -a -not -name '*.md' -exec mv -v '{}' '{}'.txt \;
```
I intend to put them back into their Makefile form.

**Comment by claudioandre-br** [comment]
As we guessed, it fails:

```diff
diff --git a/src/Makefile.in b/src/Makefile.in
index 69e33ce33..88c4a5ed0 100644
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -988,10 +988,10 @@ peflags:
 windows-package: default
        @echo Deploying for Windows.
        $(MAKE) peflags
-       $(SED) -i -e 's/\r*$$/\r/' ../doc/*
-       $(SED) -i -e 's/\r*$$/\r/' ../run/*.conf
-       $(SED) -i -e 's/\r*$$/\r/' ../run/password.lst
-       $(FIND) ../doc -type f -not -name "*.txt" -exec $(MV) "{}" "{}".txt \;
+       $(RM) ../doc/README
+       $(FIND) ../doc ../run/rules -type f -exec $(SED) -i -e 's/\r*$/\r/' {} ';'
+       $(SED) -i -e 's/\r*$/\r/' ../README.md ../run/*.conf ../run/password.lst
+       $(FIND) ../doc -type f -not -name '*.txt' -a -not -name '*.md' -exec $(MV) -v '{}' '{}'.txt \;
```

```bash
/usr/bin/sed
: -e expression #1, char 8: unterminated `s' command
/usr/bin/sed
```

To fix it, I will have to build based on CygWin bash, not on PS. The problem:
 - it is a Windows package for the Windows world. I created all stuff to be that way: on Windows, for Windows.

**Comment by claudioandre-br** [comment]
As a huge lie, I (the packager), don't need CygWin. I need PS and some `.dlls`.

**Comment by claudioandre-br** [comment]
> Edit: removed unneeded -a (implied), re-tested.

IMO the `-a` makes the logical expression "easier to find and understand". Nitpick.

**Comment by solardiz** [comment]
Thanks for testing this, Claudio! Ideally, we'd support both PS and Cygwin bash builds, because PS became the default shell on Windows only fairly recently and we should also support building on older Windows. Can we? Maybe there's a way to escape the "$" that works equally well for both (even though is unnecessary for bash)?

> IMO the -a makes the logical expression "easier to find and understand". Nitpick.

I think to make that the case we'd need to also place braces, and that means more escaping and higher risk of the command failing under some shell. So I prefer to keep the `-a` dropped.

**Comment by claudioandre-br** [comment]
Let's start again (thinking out loud):

- I'm reading the Makefile generated by Windows. 
- The `make` itself is going to read and parse this file. 
  - Just it, nothing else. 
- Why are we talking about PowerShell? Anything I wrote above is a tattered excuse. 

Why makefile stuff needs to be escaped? `make` runs `sed`. No PS involved.

**Comment by solardiz** [comment]
So what program was the extra "$" for?

**Comment by solardiz** [comment]
I think `make` actually runs shell commands, not the listed programs directly, which is why the shell matters - whatever shell `make` will use, which possibly depends on what shell system() uses in whatever C library `make` was linked against?

**Comment by claudioandre-br** [comment]
> So what program was the extra "$" for?

That is the big question. Of course, I need a real machine to experiment on. But, I can tell you that the extra "$" is for `SED` itself on Windows. As magnum says `sed` (whatever) on Windows is misbehaving.

**Comment by solardiz** [comment]
Does Windows provide its own `sed` now, or are we running Cygwin's `sed`?

**Comment by claudioandre-br** [comment]
> I think make actually runs shell commands, not the listed programs directly, which is why the shell matters - whatever shell make will use, which possibly depends on what shell system() uses in whatever C library make was linked against?

It should call CygWin bash, not a real Windows shell. It is inside a CygWin shell.

**Comment by solardiz** [comment]
> Of course, I need a real machine to experiment on.

Do you intend to get a real machine for this test soon, or should we look for someone else to help here?

> It should call CygWin bash, not a real Windows shell. It is inside a CygWin shell.

That's what I thought when I started commenting on this issue.

**Comment by solardiz** [comment]
I think we also need to retest these commands without the extra "$" in a Makefile on Linux. I did not yet. I only tested them in the command line. Maybe such retesting will uncover the same issue.

**Comment by claudioandre-br** [comment]
You got it

**Comment by claudioandre-br** [comment]
> The sed commands here wrongly have two "$" signs where there should be only one, and are completely non-working for me. I'll probably send a replacement for this entire set of commands after my testing on Linux, and will expect Claudio to retest on Windows (perhaps on CI).

No, they are not. Tested on well.
```
.PHONY: windows-package
windows-package: default
        @echo Deploying for Windows.
        $(RM) ../doc/README
        $(FIND) ../doc ../run/rules -type f -exec $(SED) -i -e 's/\r*$$/\r/' {} ';'
        $(SED) -i -e 's/\r*$$/\r/' ../README.md ../run/*.conf ../run/password.lst
        $(FIND) ../doc -type f -not -name '*.txt' -a -not -name '*.md' -exec $(MV) -v '{}' '{}'.txt \;
```

**Comment by claudioandre-br** [comment]
And it works:
```
claudio@well:~/bleeding/src$ file ../README.md 
../README.md: ASCII text, with CRLF line terminators
```

**Comment by claudioandre-br** [comment]
@magnumripper, please merge.

**Pull request merged**
