### PR TITLE
Keepass OpenCL format.

### PR DESCRIPTION
**Pull request by magnumripper**

### CODE REVIEW

**Comment by magnumripper** [comment]
> Also fixes a bug in shared valid() - it didn't reject unsupported hashes :-(

@kholia this is important. We really **really** need to reject unsupported hashes, always and forever. In this case the [CPU] format would bail out in an awkward way - which is better than nothing - but the correct behavior is **rejecting them in `valid()`**.

**Comment by kholia** [comment]
Thanks @magnumripper. I missed this opportunity to make `valid` correct and safe.

**Comment by magnumripper** [comment]
I really can't see WTH is wrong with this format. On a few devices, it works like a champ. On others it fails. On some it works fine with LWS=1 but not otherwise.

I have stared at the code for 24h to no avail. Something must be amiss, but WHAT!? @kholia can you try it out and see if whatever GPU and driver you use work or not, or if it happens to reveal some clue?

**Comment by magnumripper** [comment]
This is interesting:
```
$ ../run/john -form:keepass-opencl -test=0 -dev=1 
Device 1: HD Graphics 4000
Testing: KeePass-opencl [SHA256 AES/Twofish/Chacha OpenCL]... FAILED (cmp_all(2))
```
Fails a normal test

```
$ LWS=1 ../run/john -form:keepass-opencl -test=0 -dev=1 
Device 1: HD Graphics 4000
Testing: KeePass-opencl [SHA256 AES/Twofish/Chacha OpenCL]... PASS
```
...but passes with LWS=1

```
$ ../run/john -form:keepass-opencl -test-full=0 -dev=1 
Device 1: HD Graphics 4000
Testing: KeePass-opencl [SHA256 AES/Twofish/Chacha OpenCL]... PASS
```
...however when using --test-full instead, it works fine with any LWS!

**Comment by kholia** [comment]
Quick notes,

```
$ ../run/john --format=keepass-opencl --test
Device 0: GeForce GTX 1050 Ti
Benchmarking: KeePass-opencl [SHA256 AES/Twofish/Chacha OpenCL]... FAILED (cmp_all(1))

$ ../run/john --format=keepass-opencl -test-full=0
Device 0: GeForce GTX 1050 Ti
Testing: KeePass-opencl [SHA256 AES/Twofish/Chacha OpenCL]... FAILED (cmp_all(49))
```

```
$ dpkg -l | grep -i nvidia
...
ii  nvidia-375 ... 375.66-0ubuntu0.17.04.1 ...
```

**Comment by magnumripper** [comment]
It works perfectly fine with nvidia drivers 384.90 and 384.111 (Ubuntu packages)

It also works fine with Intel’s CPU driver 1.2.0.42.

I think we’re seeing driver bugs.

**Comment by magnumripper** [comment]
I tried changing to a whole different AES implementation but it didn't change a thing with the failing runtimes.

**Comment by magnumripper** [comment]
@kholia I found that the other AES code we have (introduced with WPA CMAC) is 10x faster. It doesn't seem to fix the issues but anyway I will re-work the whole shebang and issue a new PR later.

**Comment by kholia** [comment]
All the best for the next attempt @magnumripper! I was hoping to trace the OpenCL kernel to see where things are going wrong but I ran out of debugging energy.

**Pull request closed without merging**
