### PR TITLE
OpenCL: SHA256 and SHA512 force tune after fmt_done()

### PR DESCRIPTION
**Pull request by claudioandre-br**
This is harmless and will be needed after J1.

### CODE REVIEW

**Comment by solardiz** [comment]
Why will this be needed?

**Comment by claudioandre-br** [comment]
For autotune, in short. After a `fmt_done()`, all "status" info of the format will be cleaned.

The mandatory `-mask` on benchmark will need it.

**Comment by solardiz** [comment]
> The mandatory `-mask` on benchmark will need it.

Does this imply that we already need this for the optional `-mask` on benchmark?

**Comment by claudioandre-br** [comment]
No. Only after magnun's patch (to force `--mask` or to self-test when `--mask`) it will be required.

**Pull request merged**
